### ISSUE TITLE
Guide for adding a new leaflet plugin?

### ISSUE THREAD

**Issue by mangecoeur** [jupyter-widgets/ipyleaflet#1012]
I would like to add some extra leaflet plugins to the ipyleaflet widget (e.g. leaflet-geoman). I'm assuming I would have to fork ipyleaflet for this to work. Is there a guide or example of how to integrate plugin?

**Comment by davidbrochart** [comment]
Hi @mangecoeur!

> I would like to add some extra leaflet plugins to the ipyleaflet widget (e.g. leaflet-geoman)

That would be awesome! I guess @giswqs would be interested in [this one](https://github.com/geoman-io/leaflet-geoman).

> I'm assuming I would have to fork ipyleaflet for this to work.

That's the typical git workflow if you want to submit a pull request, yes.

> Is there a guide or example of how to integrate plugin?

Not really, but there are examples you can follow. In your case, you might want to look at [DrawControl.js](https://github.com/jupyter-widgets/ipyleaflet/blob/7bc67ab5d0ceb69c745558ee56ad459a4fe3ac3c/js/src/controls/DrawControl.js), and its [Python counterpart](https://github.com/jupyter-widgets/ipyleaflet/blob/8351f11eb347999a252e2036274dbbf2fb8f0ec1/ipyleaflet/leaflet.py#L1758).

**Comment by mangecoeur** [comment]
Great thanks for the quick reply. BTW by 'fork ipyleaflet' I had meant that I assumed you would not want to host extra plugins in the main repo, but it sounds like you actually do so even better! ;)

**Comment by mangecoeur** [comment]
P.S. I will close the issue now since actually adding this will be a separate PR.

**Comment by karelvancamp** [comment]
@mangecoeur 
FYI Turfpy https://turfpy.readthedocs.io/en/latest/
