### ISSUE TITLE
Deleting/Adding to DrawControl Doesn't Render on Map

### ISSUE THREAD

**Issue by CF-FHB-X** [jupyter-widgets/ipyleaflet#1013]
Hi there!

Just trying to understand how the relationship works between the `Map` and `DrawControl`. Our use case allows for users to create/edit/delete polygons by using the `DrawControl` tool. Each polygon gets a new `ipywidgets.Tab` (for adding attribute data) in an `ipywidgets.VBox` below the map.

What I'd like to do is also allow for creating/editing/deleting those polygons from the `VBox` (each `Tab` gets a "Delete" button, for example). Or I would like to programmatically add a polygon to the `DrawControl` when the user adds clicks something like a "Add Polygon" button.

Where I'm running into problems is that I can create/edit/delete the GeoJSON in the `DrawControl.data` list, but the map never changes. Am I missing a `refresh` option for either the `Map` or the `DrawControl` widget?

Thanks in advance!

**Comment by giswqs** [comment]
Relevant issue: https://github.com/jupyter-widgets/ipyleaflet/issues/849

**Comment by davidbrochart** [comment]
@CF-FHB-X I'm suspecting you modify `DrawControl.data` in-place, for instance if you have:
```python
dc.data = [{'type': 'Feature',
  'properties': {'style': {'stroke': True,
    'color': '#0000FF',
    'weight': 4,
    'opacity': 0.5,
    'fill': True,
    'fillColor': None,
    'fillOpacity': 0.2,
    'clickable': True}},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[-78.290075, 34.622152],
     [-78.290075, 34.709432],
     [-78.111588, 34.709432],
     [-78.111588, 34.622152],
     [-78.290075, 34.622152]]]}}]
```
Then `dc.data[0]["geometry"]["coordinates"][0][0][0] = -78.5` will not do anything. You need to assign to `dc.data` as a whole:
```python
dc.data = [{'type': 'Feature',
  'properties': {'style': {'stroke': True,
    'color': '#0000FF',
    'weight': 4,
    'opacity': 0.5,
    'fill': True,
    'fillColor': None,
    'fillOpacity': 0.2,
    'clickable': True}},
  'geometry': {'type': 'Polygon',
   'coordinates': [[[-78.5, 34.622152],
     [-78.290075, 34.709432],
     [-78.111588, 34.709432],
     [-78.111588, 34.622152],
     [-78.290075, 34.622152]]]}}]
```
This is a limitation of traitlets.

**Comment by CF-FHB-X** [comment]
Ah-ha! That did it - thanks!
