### ISSUE TITLE
Unable to load layers

### ISSUE THREAD

**Issue by moovida** [jupyter-widgets/ipyleaflet#1061]
Hi, I am having issues adding even simple layers to the Map object in jupyterlab.

I ended up trying the simple marker example from the docs, but that also fails.
I am not getting any error, just the broser console shows me something is failing with addLayer:

![image](https://user-images.githubusercontent.com/390250/194828116-f3c103c4-dbac-410e-a3a6-b962b2f690d4.png)

Any idea what is going wrong?
Thank you

**Comment by martinRenou** [comment]
Thanks for opening an issue. 

Which ipyleaflet version do you use?

Also can you show us the output of `jupyter labextension list`?

**Comment by moovida** [comment]
I am using ipyleaflet 0.17.1

The extensions list shows me:
```
JupyterLab v3.4.6
~/.local/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyter-leaflet v0.17.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.3 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: ~/.local/share/jupyter/lab
        js v0.1.0 enabled OK
```

**Comment by martinRenou** [comment]
Do you know what this could be?
```
Other labextensions (built into JupyterLab)
   app dir: ~/.local/share/jupyter/lab
        js v0.1.0 enabled OK
```

**Comment by moovida** [comment]
Yes, (or better, I know why it is there), when I was looking for solutions I found a user saying that after installing that js extension, it worked. I had previously installed the other extensions though.

**Comment by martinRenou** [comment]
There should be no need for this.

I'd suggest removing entirely the `~/.local/share/jupyter/labextensions` and `~/.local/share/jupyter/lab` folders, and try again a clean installation with just `pip install ipyleaflet`.

**Comment by moovida** [comment]
ok, will try that. Should I install the jupyter-leaflet extension, or is that no longer necessary?

**Comment by martinRenou** [comment]
Just `pip install ipyleaflet` is enough, there should be no need to run `jupyter labextension install` anymore.

**Comment by martinRenou** [comment]
It's really unclear to me as well, the error message you were getting is nothing that I recognize!

Happy that you could get it to work :)
