### ISSUE TITLE
Error displaying widget: model not found (JupyterLab 3.4.4)

### ISSUE THREAD

**Issue by elisabettai** [jupyter-widgets/ipyleaflet#1062]
Dear @martinRenou and Team, sorry to bring this common issue up again, but I spent a whole day trying to figure out what is going wrong.

This is the code I run in my jupyter notebook (I am using a [JupyterLab service](https://github.com/ITISFoundation/jupyter-math/blob/main/Dockerfile) built in our computational platform).

```
import sys
!{sys.executable} -m pip install ipyleaflet

from ipyleaflet import Map, basemaps, basemap_to_tiles

m = Map(
    basemap=basemap_to_tiles(basemaps.OpenStreetMap.Mapnik),
    center=(48.204793, 350.121558),
    zoom=3
    )
m
```
And I get this error:
`Error: Error displaying widget: model not found`

In the browser logs I see:
`Error: Module jupyter-leaflet, semver range ^0.17 is not registered as a widget module` (and some others)

The output of `!jupyter labextension list` is:
```
JupyterLab v3.4.4
/home/jovyan/.venv/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.1.1 enabled OK
        jupyter-matplotlib v0.10.5 enabled OK
        ipyevents v2.0.1 enabled OK
        jupyterlab-plotly v5.7.0 enabled OK
        jupyter-leaflet v0.17.1 enabled OK
        @krassowski/jupyterlab-lsp v3.10.1 enabled OK (python, jupyterlab-lsp)
        @jupyterlab/latex v3.1.0 enabled OK (python, jupyterlab-latex)
        @jupyterlab/git v0.36.0 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)
        @voila-dashboards/jupyterlab-preview v2.1.5 enabled OK (python, voila)

Other labextensions (built into JupyterLab)
   app dir: /home/jovyan/.venv/share/jupyter/lab


The following source extensions are overshadowed by older prebuilt extensions:
    @jupyter-widgets/jupyterlab-manager
```
Do you see some extension as an obvious culprit?

**Comment by martinRenou** [comment]
Thanks for opening a detailed issue. I don't see any issue so far in your setup.

Could you please provide the full browser logs?

**Comment by elisabettai** [comment]
Thank you @martinRenou for the quick reply. I'm attaching the full browser logs. 
[console-export-2022-10-12_14-49-42_sent.txt](https://github.com/jupyter-widgets/ipyleaflet/files/9764977/console-export-2022-10-12_14-49-42_sent.txt)

**Comment by elisabettai** [comment]
> I don't see how you install ipyleaflet in your Docker file. What is your process to install it?

ipyleaflet is not part of the Docker image. I install it from inside the jupyterlab notebook with:
```
import sys
!{sys.executable} -m pip install ipyleaflet```
```
This should make sure it is installed in the right python environment. I am also attaching the out of `!{sys.executable} -m pip freeze`, in case that helps. 
[pip_freeze.txt](https://github.com/jupyter-widgets/ipyleaflet/files/9765472/pip_freeze.txt)



> Also I'm a bit confused by this part:
> 
> ```
> The following source extensions are overshadowed by older prebuilt extensions:
>     @jupyter-widgets/jupyterlab-manager
> ```
> 
> Are you installing something with the `jupyter labextension install` command? Since JupyterLab 3 we encourage not running this command anymore (it's not supposed to be needed, and it seems to lead to some issues)
Mmh, no. I've checked in the [Dockerfile](https://github.com/ITISFoundation/jupyter-math/blob/main/Dockerfile), and we don't use the `jupyter labextension install` command.

I would need to figure out what cause "...extensions are overshadowed by older prebuilt extensions"

**Comment by martinRenou** [comment]
> ipyleaflet is not part of the Docker image. I install it from inside the jupyterlab notebook with:

Ok. Just in case you didn't do it, you will need to hard refresh your browser page to make sure to pull the latest JS extensions.

**Comment by elisabettai** [comment]
Ooooooh, actually a hard refresh (of our JupyterLab service) fixed it.

Thanks a lot!
