### ISSUE TITLE
Map layers don't appear (blank map) for new installations/updates of ipyleaflet

### ISSUE THREAD

**Issue by radwinskis** [jupyter-widgets/ipyleaflet#1065]
Hi there,

I use ipyleaflet for Earth observations using the geemap package, and recently wanted to update the environment. This has led me to realizing I can't get any layers to appear with any new installation of ipyleaflet. I use jupyter notebooks with VS Code. I have tried creating a new environment using Conda and python 3.9.1 (as well as python 3.9.13) then installed ipyleaflet with Conda using `conda install -c conda-forge ipyleaflet`, but whenever I try to display a map it won't show any layers (see below image as a simple example). Not sure what else to do to get it working and I'd love to figure it out so I can use an updated environment for geemap. 
![image](https://user-images.githubusercontent.com/78708345/196498704-bf7c6179-7ace-46cf-ac31-79d027b36cf2.png)

In case it is helpful, here is the output of `conda list`

>  Name                    Version                   Build  Channel
> asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
> attrs                     22.1.0             pyh71513ae_1    conda-forge
> backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
> backports                 1.0                        py_2    conda-forge
> backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
> branca                    0.5.0              pyhd8ed1ab_0    conda-forge
> ca-certificates           2022.9.24            h5b45459_0    conda-forge
> certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
> colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
> debugpy                   1.6.3            py39h415ef7b_0    conda-forge
> decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
> entrypoints               0.4                pyhd8ed1ab_0    conda-forge
> executing                 1.1.1              pyhd8ed1ab_0    conda-forge
> importlib-metadata        4.11.4           py39hcbf5309_0    conda-forge
> importlib_resources       5.10.0             pyhd8ed1ab_0    conda-forge
> ipykernel                 6.16.0             pyh025b116_0    conda-forge
> ipyleaflet                0.17.1             pyhd8ed1ab_0    conda-forge
> ipython                   8.5.0              pyh08f2357_1    conda-forge
> ipywidgets                8.0.2              pyhd8ed1ab_1    conda-forge
> jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
> jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
> jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
> jupyter_client            7.4.2              pyhd8ed1ab_0    conda-forge
> jupyter_core              4.11.1           py39hcbf5309_0    conda-forge
> jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
> libsodium                 1.0.18               h8d14728_1    conda-forge
> markupsafe                2.1.1            py39hb82d6ee_1    conda-forge
> matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
> nbformat                  5.7.0              pyhd8ed1ab_0    conda-forge
> nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
> openssl                   1.1.1q               h8ffe710_0    conda-forge
> packaging                 21.3               pyhd8ed1ab_0    conda-forge
> parso                     0.8.3              pyhd8ed1ab_0    conda-forge
> pickleshare               0.7.5                   py_1003    conda-forge
> pip                       22.2.2           py39haa95532_0
> pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
> prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
> psutil                    5.9.0            py39h2bbff1b_0
> pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
> pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
> pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
> pyrsistent                0.18.1           py39hb82d6ee_1    conda-forge
> python                    3.9.1                h6244533_2
> python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
> python_abi                3.9                      2_cp39    conda-forge
> pywin32                   303              py39hb82d6ee_0    conda-forge
> pyzmq                     23.2.0           py39hd77b12b_0
> setuptools                63.4.1           py39haa95532_0
> six                       1.16.0             pyh6c4a22f_0    conda-forge
> sqlite                    3.39.3               h2bbff1b_0
> stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
> tornado                   6.2              py39hb82d6ee_0    conda-forge
> traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
> traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
> typing_extensions         4.4.0              pyha770c72_0    conda-forge
> tzdata                    2022e                h04d1e81_0
> vc                        14.2                 h21ff451_1
> vs2015_runtime            14.27.29016          h5e58377_2
> wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
> wheel                     0.37.1             pyhd3eb1b0_0
> widgetsnbextension        4.0.3              pyhd8ed1ab_0    conda-forge
> wincertstore              0.2              py39haa95532_2
> xyzservices               2022.9.0           pyhd8ed1ab_0    conda-forge
> zeromq                    4.3.4                h0e60522_1    conda-forge
> zipp                      3.9.0              pyhd8ed1ab_0    conda-forge

And here is the output of `jupyter-nbextension list`

> Known nbextensions:
>   config dir: C:\Users\NAME\.jupyter\nbconfig
>     notebook section
>       zenmode/main disabled
>       hide_input_all/main enabled
>       - Validating: problems found:
>         - require?  X hide_input_all/main
>       code_prettify/autopep8 disabled
>       execute_time/ExecuteTime enabled
>       - Validating: problems found:
>         - require?  X execute_time/ExecuteTime
>   config dir: C:\Users\NAME\Conda\etc\jupyter\nbconfig
>     notebook section
>       jupyter-js-widgets/extension enabled
>       - Validating: ok

Note: I am able to view layers of ipyleaflet maps when using the old, outdated environment that is using ipyleaflet 0.13.3. I can provide the `conda list` for that environment if that would be helpful.

Thanks for your help in advance and please let me know what else I can provide!

**Comment by ivandigiusto** [comment]
I have a similar problem - not sure if it is exactly like yours.

The map appears fine when I work in Jupyter Notebook (when the map is displayed in a cell).

When I save that map (with m.save(filename)) and try to open it locally or hosted from a web page - all of the basemap layers are either gray or say "May Layer Not Available" on each tile.

I looked at the console output and it appears that the **leaflet is passing NaN for the zoom layer to the mapping provider**.

Browser console window is full of lines like this:
`Failed to load resource: the server responded with a status of 400 ()   tile.openstreetmap.org/NaN/16394/10793.png:1`

As you can see, NaN is being passed as the zoom level, so I don't know what part of js is doing this.

All my map files that were created up to some time last week or before were fine, but every map that I create with ipyleaflet now and save does not work.

Things that I have tried:
- Downgrading from ipyleaflet 0.17.2 to 0.17.0
- Creating a new environment and installing only the minimum packages required for ipyleaflet
- Creating a map with the simplest code - shown below

``` 
from ipyleaflet import Map, basemaps

center = [38.128, 2.588]
zoom = 5

m=Map(basemap=basemaps.OpenStreetMap.Mapnik, center=center, zoom=zoom) 
m.save('my_map.html)
m
 ```

My environment (ipyleaflet 0.17.0 and 0.17.2)
conda --version
conda 22.9.0

jupyter --version
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 5.3.4
ipywidgets       : 7.6.5
jupyter_client   : 6.1.12
jupyter_core     : 4.11.1
jupyter_server   : 1.13.5
jupyterlab       : 3.3.2
nbclient         : not installed
nbconvert        : 5.5.0
nbformat         : 5.5.0
notebook         : 6.4.5
qtconsole        : 5.3.2
traitlets        : 5.1.1

**Comment by martinRenou** [comment]
Can you try passing a `zoom=12` to your Map creation? There is a bug with it. We should fix it.
