### ISSUE TITLE
SplitMapControl not working locally

### ISSUE THREAD

**Issue by raybellwaves** [jupyter-widgets/ipyleaflet#1066]
I tried to run https://ipyleaflet.readthedocs.io/en/latest/controls/split_map_control.html locally

I get a strange behavior where the slider does not work and it only drags the image underneath it. What information can I provide to help debug this?

https://user-images.githubusercontent.com/17162724/196764109-adc7d12d-ebea-4496-8378-006c25897b90.mov

**Comment by martinRenou** [comment]
I can replicate this issue as well. Something may have changed in LeafletJS that broke the SplitMap extension.

**Comment by raybellwaves** [comment]
> I can replicate this issue as well. Something may have changed in LeafletJS that broke the SplitMap extension.

Is there a way to test against different versions of Leaflet? https://github.com/Leaflet/Leaflet/tags

**Comment by martinRenou** [comment]
The only thing you can try is downgrade ipyleaflet until the SplitMap control works again. Unless you want to try and make a dev install of ipyleaflet and downgrade LeafletJS in the source, which I would probably not recommend.

**Comment by giswqs** [comment]
I just ran into the same issue. Waiting for a fix.

**Comment by jportolese** [comment]
Same here.  Has anyone found a version that doesn't have this issue?

**Comment by jportolese** [comment]
I had ipyleaflet 0.17.2 installed and it didn't work
I tried 0.17.0, 16, 15, 14 and none of them make a difference.  That goes back to June 17, 2021.  Has this been an issue for longer than that?

**Comment by BoineeloMoyo** [comment]
Was the issue ever solved..? i have the same problem. What version of ipyleaflet works perfect with the splitmap

**Comment by lachlanfrancis** [comment]
I had this issue; and believe an update to the documentation is required (raised in #1115).  
Adding `dragging = False` to my `Map` allowed the slider to work without trying to drag the base map.

m = Map(center=(42.6824, 365.581), zoom=5, dragging = False)

**Comment by martinRenou** [comment]
https://github.com/QuantStack/leaflet-splitmap has been released with I believe contains the patch required to fix this issue.

ipyleaflet would need to be rebuilt with this new version. Happy to review a PR if someone wants to tackle this!
