### ISSUE TITLE
Gray basemap in HTML exports.

### ISSUE THREAD

**Issue by ehb-res** [jupyter-widgets/ipyleaflet#1069]
This may be the same as, or related to, #1063 or #1048. 

For versions >= 0.17.0, the basemap shows up as gray in HTML exports, e.g.
```
m = Map(basemap=basemaps.OpenStreetMap.Mapnik, zoom=.1, center=(0,0))
m
```
displays the map in a Jupyter notebook, but using
```
m.save('test.html')
```
the map at `test.html` shows only gray when opened in a browser window. 

If layers are added to the map, the layers appear in both the notebook and the exported HTML, but the basemap remains gray in the latter.

This problem goes away after downgrading to `0.16.0`, in which case the basemap, as well as the layers, display as expected in the HTML.

**Comment by martinRenou** [comment]
Should be fixed by #1068
