### ISSUE TITLE
Is it possible to not have a basemap when creating a map?

### ISSUE THREAD

**Issue by Hato1** [jupyter-widgets/ipyleaflet#1073]
When creating a map, a default basemap is used.
In my use case, I wish to use my own png image using ImageOverlay without having the default basemap in the background, leading me to this workaround:
```
from ipyleaflet import Map
m = Map(zoom=4)
m.clear_layers()
m
```
Is there a better way?

**Comment by martinRenou** [comment]
You can maybe have one less line in your sample:
```python
from ipyleaflet import Map
m = Map(zoom=4, layers=[])
m
```

**Comment by Hato1** [comment]
Thanks, @martinRenou, that looks much better
