### ISSUE TITLE
Add study to sample Ag3 metadata 

### ISSUE THREAD

**Issue by alimanfoo** [jupyter-widgets/ipyleaflet#1105]
It would be useful to have a "study" field with the MalariaGEN study ID in the sample metadata.

**Comment by davidbrochart** [comment]
@alimanfoo did you mean to post this issue here?

**Comment by alimanfoo** [comment]
Doh, so sorry - github blindness!

**Comment by alimanfoo** [comment]
Btw thank you for ipyleaflet, so useful!
