### ISSUE TITLE
ipyleaflet not working properly with JupyterLab 4.x

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#1125]
It appears that JupyterLab 4.x breaks some ipyleaflet functionality. Changing map attributes (e.g., zoom, center) has no effect. It works fine in VS Code. 

In JupyterLab:
![Peek 2023-07-14 23-10](https://github.com/jupyter-widgets/ipyleaflet/assets/5016453/5eb3e3ed-54a1-4782-b925-592e980f7c3e)

In VS Code:
![Peek 2023-07-14 23-13](https://github.com/jupyter-widgets/ipyleaflet/assets/5016453/3e12c77f-9bab-4d43-aeb0-faefbf94722e)

**Comment by martinRenou** [comment]
Thank you for opening an issue. Would you be able to provide the JavaScript console errors, if there are any?

**Comment by giswqs** [comment]
See https://github.com/jupyterlab/jupyterlab/issues/14829#issuecomment-1671370797

**Comment by dfguerrerom** [comment]
@giswqs you might want to see https://github.com/openforis/sepal/issues/304.

**Comment by jhgoebbert** [comment]
I came across this fork which claims to run with JupyterLab>4. Perhaps it is possible to merge the commits from there.  
https://github.com/cdanielw/ipyleaflet

**Comment by cdanielw** [comment]
Together with that fork, I uploaded a pre-built release we use in [SEPAL](https://github.com/openforis/sepal/), as an interim solution:

`pip install https://github.com/cdanielw/ipyleaflet/releases/download/0.17.4/ipyleaflet-0.17.4-py3-none-any.whl`

I never bothered to make a pull request, as I assume the ipyleaflet guys are on-top-of this issue. I just needed an immediate way to get this running.

**Comment by martinRenou** [comment]
If you could open a PR that would be great. We need help maintaining this.
