### ISSUE TITLE
JupyterLite demo errors on ipyleaflet.readthedocs.io

### ISSUE THREAD

**Issue by psychemedia** [jupyter-widgets/ipyleaflet#1127]
Trying to run the online demo at https://ipyleaflet.readthedocs.io/en/latest/index.html raises an error.

<img width="1105" alt="image" src="https://github.com/jupyter-widgets/ipyleaflet/assets/82988/0e938190-b02a-4e9c-b9c8-6bfc701f5db1">

**Comment by martinRenou** [comment]
We should probably switch to xeus-python in the jupyterlite demo

**Comment by drf5n** [comment]
This project's main README.md refers from https://github.com/jupyter-widgets/ipyleaflet#documentation directly to the broken https://ipyleaflet.readthedocs.io/en/latest/ page.

If the fix is still in the planning stages, and may continue for another three weeks, at least the https://ipyleaflet.readthedocs.io/en/latest/ front page should have a note or point here to issue https://github.com/jupyter-widgets/ipyleaflet/issues/1127 for status updates.

**Comment by rdhyee** [comment]
FWIW, I was just trying to learn about ipyleaflet today and saw the error under discussion here. Wondering whether this is an issue that is a good one for someone new to the project to try to fix.

**Comment by maartenbreddels** [comment]
It has been broken for quite a while, should we remove it? It does not give a good impression now.

**Comment by drf5n** [comment]
Where is the code that makes that page?    Is it near https://github.com/jupyter-widgets/ipyleaflet/blob/master/docs/source/index.rst

This should be a basic use-case for ipyleaflet and should be repaired rather than removed.

**Comment by martinRenou** [comment]
It should be more stable now

**Comment by drf5n** [comment]
I get this after a click and two shift-returns:

<img width="866" alt="image" src="https://github.com/jupyter-widgets/ipyleaflet/assets/2236516/03ee489b-f2f8-4f74-abba-b27b717157d8">
...or in text form:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /lib/python3.10/site-packages/IPython/__init__.py:44, in patch_asyncio.<locals>.asyncio_call(self, coro)
     41     task.add_done_callback(done_cb)
     43 raw_js_py_callback = pyjs.JsValue(py_callback)
---> 44 js_py_callback = raw_js_py_callback['__usafe_void_val_val__'].bind(raw_js_py_callback)
     45 js_promise = pyjs.js.Promise.new(js_py_callback)
     47 pyjs.js.globalThis.toplevel_promise = js_promise

AttributeError: has no attribute/key 
```

**Comment by rdhyee** [comment]
I can confirm that when I go to https://ipyleaflet.readthedocs.io/en/latest/index.html in a private window, the demo is now working for me.

**Comment by martinRenou** [comment]
Nice! 

Browser caching is known to go in your way when using JupyterLite. Cleaning all data for that webpage or opening from a private windows should prevent that.
