### ISSUE TITLE
Issues with ipyleaflet 0.19 in Colab

### ISSUE THREAD

**Issue by osgeokr** [jupyter-widgets/ipyleaflet#1193]
I currently have ipyleaflet 0.19 installed in Colab, but the map is not displaying.
I checked the version with the code below.
```
import ipyleaflet
print(ipyleaflet.__version__)
```
I am using [geemap](https://geemap.org/), which dependent on ipyleaflet, and I have encountered this error.
For now, I am using the following code to downgrade the version.
```
!pip install -q ipyleaflet==0.18
```

**Comment by schwehr** [comment]
This is a dup of #1192
