### ISSUE TITLE
Geemap/ipyleaflet not displaying map in Jupyter Notebooks

### ISSUE THREAD

**Issue by qtyree** [jupyter-widgets/ipyleaflet#1202]
I am trying to use geemap and visualize maps in Jupyter Notebooks, but I cannot get around this "Failed to load model class 'LeafletMapModel' from module 'jupyter-leaflet'" error message. 

![image](https://github.com/jupyter-widgets/ipyleaflet/assets/161641043/69ac18d6-6270-47dc-9637-eb6af0494c0a)

I have tried several different fixes from other forums, but none have worked. I uninstalled and reinstalled geemap, ipyleaflet, and jupyter-leaflet. And I have run these lines:

``` 
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-leaflet
```

This is what my labextensions look like:

![image](https://github.com/jupyter-widgets/ipyleaflet/assets/161641043/bf3c2360-2eae-479a-91d6-e12b8fea5fbc)

Let me know if there is a way to fix this without creating a new environment. Thank you

**Comment by giswqs** [comment]
Try creating a fresh conda env to install geemap and JupyterLab. 

```python
conda create -n gee python=3.11
conda activate gee
conda install geemap -c conda-forge
```

**Comment by martinRenou** [comment]
I see jupyterlab-plotly and @pyviz/jupyterlab_pyviz in the list of lab extensions, I can't remember which one (the first one?) but IIRC one of those is not updated to work with latest ipywidgets and breaks other widgets. I'd suggest uninstalling it.
