### ISSUE TITLE
ipyleaflet stopped working with VS Code

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#1230]
I am not sure if this is an ipyleaflet issue or VS Code issue. It apprears the ipyleaflet stopped working with the the latest VS Code version 1.93.0. I have tried it on multiple computers and operating systems (Linux and Windows), none of them works. Anyone encountering the same issue?

ipyleaflet                    0.19.1
ipywidgets                    8.1.2
jupyterlab                    4.2.0

> Failed to load model class 'LeafletMapModel' from module 'jupyter-leaflet'
Error: No version of module jupyter-leaflet is registered

![image](https://github.com/user-attachments/assets/379ba425-9220-4d46-a13e-a429678bc61e)

![image](https://github.com/user-attachments/assets/5e7aab24-c933-4bf2-a8cc-7b5adceb72dc)

**Comment by scabecks** [comment]
Yes, same issue, same error message, same VS Code update.

![image](https://github.com/user-attachments/assets/d2da792a-f5fd-424e-b5b8-318fb20f4f1e)

**Comment by martinRenou** [comment]
Should this is issue be transferred to https://github.com/microsoft/vscode-jupyter? We haven't change anything on our end

**Comment by maartenbreddels** [comment]
See
 * https://github.com/microsoft/vscode-jupyter/issues/16008 and
 * https://github.com/microsoft/vscode-jupyter/pull/16018

**Comment by giswqs** [comment]
It has been fixed in vscode-jupyter. Switching to the pre-release solves the issue. Thank you everyone. 
https://github.com/microsoft/vscode-jupyter/issues/16008#issuecomment-2336541224
