### ISSUE TITLE
Marker's rise_on_hover attribute

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipyleaflet#137]
I wanted to use the `rise_on_hover` attribute of Marker class, I thought the marker would enlarge itself when the mouse if at the marker's location if this attribute is enable, but it doesn't. Am I completely wrong concerning the use of `rise_on_hover`?

**Comment by SylvainCorlay** [comment]
Actually, the `rise_on_hover` property appears to be working as expected.

The expected behavior is that if many markers overlap, the one being hovered will only move to the top of the stack.
