### ISSUE TITLE
Changing the zoom attribute of map does nothing

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipyleaflet#157]
Changing the zoom attribute of a map does nothing:

```python
map.zoom = 15
```

**Comment by SylvainCorlay** [comment]
This is not what I am seeing. Is this under specific circumstances.

**Comment by martinRenou** [comment]
I don't think so, I just created a basic map and tried to change the zoom value from the backend.

**Comment by SylvainCorlay** [comment]
It appears to work in the binder but I am AFK at the moment.

**Comment by martinRenou** [comment]
Ok, it looks like I had a broken version of ipyleaflet. It works as expected after reinstallation

**Comment by SylvainCorlay** [comment]
Cool
