### ISSUE TITLE
Map inside a HBox not visible by default

### ISSUE THREAD

**Issue by amarandon** [jupyter-widgets/ipyleaflet#170]
I've noticed a surprising behavior when adding several maps to an ipywidget HBox. Consider this code:

```python
import ipywidgets
from ipyleaflet import Map

center, zoom = [43.6, 1.44], 5
widgets.HBox([Map(center=center, zoom=zoom), Map(center=center, zoom=zoom)])
```
This doesn't show anything visible. The map elements actually do get inserted into the DOM but they have a width of zero.

One possible workaround is to set a layout on the map:

```python
import ipywidgets
from ipyleaflet import Map

center, zoom = [43.6, 1.44], 5
layout = widgets.Layout(width='50%')
widgets.HBox([
    Map(center=center, zoom=zoom, layout=layout),
    Map(center=center, zoom=zoom, layout=layout)
])
```
Now the maps are visible. Should there be a minimum width on maps?

**Comment by SylvainCorlay** [comment]
Thanks for reporting @amarandon !

maybe a good way to deal with this without having to add a min width would be to default the `flex` attribute to `'1'`.

<img width="657" alt="screen shot 2018-06-19 at 10 50 52 am" src="https://user-images.githubusercontent.com/2397974/41587112-b1632528-73ae-11e8-9494-b0d7bd335297.png">
