### ISSUE TITLE
citation for SciPy paper

### ISSUE THREAD

**Issue by jmmease** [jupyter-widgets/ipyleaflet#172]
Hi All, 
I've submitted the first draft of a paper for SciPy 2018 on bringing ipywidgets support to plotly.py.
scipy-conference/scipy_proceedings#395 (Current PDF is attached to main description).

I mention ipyleaflet on the second page:
> The infrastructure behind the built-in ipywidgets is available to library authors and many custom ipywidgets libraries have been developed [Cus]. Three notable data visualization examples include bqplot [bqp] for 2-dimensional Grammar of Graphics [Wil05] style visualizations, ipyvolume [ipyb] for 3-dimensional and volumetric visualizations, and ipyleaflet [ipya] for geographic visualization.

Where the [ipya] reference is https://github.com/jupyter-widgets/ipyleaflet

Let me know if you'd like any changes in the citation, or if you'd suggest a different brief description.

Thanks, and feel free to close this issue if you're fine with what's there, or if you don't care to review it!

**Comment by SylvainCorlay** [comment]
Hi @jmmease thanks for mentioning ipyleaflet! I think that it is looking good!

**Comment by SylvainCorlay** [comment]
Quick remark:

It may make sense to add authors for these references. For example, alphabetical orders for all that have ~100 commits or more on bqplot (then there is a tail of contributions).

And for example for ipyvolume, maybe add Maarten Breddels as the only author.

I was thinking pythreejs and nglview are other notable widget libraries out there.

**Comment by jmmease** [comment]
Great point on authors!  I'll add a note to my corresponding bqplot (bloomberg/bqplot#654), and ipyvolume (maartenbreddels/ipyvolume#134) issues to ask for author suggestions.

Using the ~100 commits threshold would make you the only author for ipyleaflet. I'll go with that unless you'd like to ammend it.

**Comment by SylvainCorlay** [comment]
For ipyleaflet, I think that we should include Brian Granger, who authored the first version of the package before I picked it up.

**Comment by SylvainCorlay** [comment]
For bqplot, we should have Jason Grout included as well.

**Comment by SylvainCorlay** [comment]
Closing!
