### ISSUE TITLE
ipyleaflet 0.8.2 requires xarray, which is not installed

### ISSUE THREAD

**Issue by Juanlu001** [jupyter-widgets/ipyleaflet#185]
I noticed this new failure coming from ipyleaflet:

https://travis-ci.org/satellogic/telluric/jobs/394573045#L816

```
...
../../../virtualenv/python3.5.5/lib/python3.5/site-packages/telluric/plotting.py:12: in <module>
    from ipyleaflet import (
../../../virtualenv/python3.5.5/lib/python3.5/site-packages/ipyleaflet/__init__.py:3: in <module>
    from .leaflet import *
../../../virtualenv/python3.5.5/lib/python3.5/site-packages/ipyleaflet/leaflet.py:214: in <module>
    class Velocity(Layer):
../../../virtualenv/python3.5.5/lib/python3.5/site-packages/ipyleaflet/leaflet.py:224: in Velocity
    data = Dataset().tag(sync=True, to_json=ds_x_to_json)
../../../virtualenv/python3.5.5/lib/python3.5/site-packages/traittypes/traittypes.py:265: in __init__
    import xarray as xr
E   ImportError: No module named 'xarray'
```

Which I think was introduced in https://github.com/jupyter-widgets/ipyleaflet/pull/178. Or perhaps it's an issue in traittypes 0.2.1, released 4 days ago?

**Comment by SylvainCorlay** [comment]
Wow, 0.8.2 was out for 10 minutes before I released 0.8.3!

**Comment by Juanlu001** [comment]
Hah, perfect timing :) Saw that you fixed this in 0.8.3, so closing!

**Comment by stonebig** [comment]
hi, in Velocity.ipynb example, I have a future warning message:
![image](https://user-images.githubusercontent.com/4312421/41812501-251086d2-7724-11e8-8847-0b9461a5effe.png)

**Comment by SylvainCorlay** [comment]
Yes. It is a known issue. There is an issue upstream about  initializing a dataset from a dataset.
