### ISSUE TITLE
[NOT WORKING] Heatmap in Jupiter notebook on a Mac.

### ISSUE THREAD

**Issue by loulouOz** [jupyter-widgets/ipyleaflet#189]
Good morning, 

It looks like heatmap cannot be loaded (defined) in Jupiter notebook on a Mac. (it does work on windows however)

Any help with this please?
Thanks,
Louis

**Comment by SylvainCorlay** [comment]
Hello @loulouOz thanks for reporting?

Can you please report any error message displayed in the notebook and the version of ipyleaflet that you use with both OS X and windows?

**Comment by loulouOz** [comment]
Hi Sylvain,

Of course, the message is "ImportError: cannot import name 'Heatmap' "

Anything else to import from ipyleaflet is fine, only heat map is not working.

Thanks for your help,
Louis

**Comment by SylvainCorlay** [comment]
I suspect you are not using the latest version of the package on OS X. Heatmap is a recent addition.

**Comment by SylvainCorlay** [comment]
```python
import ipyleaflet
ipyleaflet.__version__
```

**Comment by loulouOz** [comment]
and you are right, my apologies, I was checking and for some reason on Mac os, 0.8.4 wouldn't install which is done now and heat map is working thanks to you!

I have 2 other questions you might be able to help with:

is it possible to save a map as an image (png, etc..) or as an html?

for the heat map, I have trouble to 'plot' the heatmap, examples below:

for idx, f in df.iterrows():
    r = Heatmap(locations=[[f.latitude,f.longitude,f.weight] for i in range(max_int)], radius=15,blur=20)
    m.add_layer(r)
### This one above will plot but not in a nice heatmap ways, just superposing blurry stuff ###
or 

r = Heatmap(locations=[[df.latitude,df.longitude,df.weight] for i in range(max_int)], radius=15,blur=20)
m.add_layer(r);
m
### this one above goes in error:  "Can't clean for JSON: 0" ###

Any ideas what I am doing wrong?

Thanks for your help,
Louis

**Comment by SylvainCorlay** [comment]
> r = Heatmap(locations=[[df.latitude,df.longitude,df.weight] for i in range(max_int)],
> radius=15,blur=20)
> m.add_layer(r);
> m

At the moment, the locations are passed as a `List`, so you cannot nest with a numpy array, which is not JSON serializatble. We may want to move to a numpy array trait type eventually.

**Comment by loulouOz** [comment]
Thanks Sylvain. Looking forward to future versions.
