### ISSUE TITLE
Use in Google's Colaboratory (Colab)

### ISSUE THREAD

**Issue by fitoprincipe** [jupyter-widgets/ipyleaflet#195]
Is it possible to use ipyleaflet in Colab? I've tried with no success: https://colab.research.google.com/drive/1qpo6xqxmOKMiyABVnWuqgcYcPozV6ecV

**Comment by SylvainCorlay** [comment]
Thanks for posting here @fitoprincipe . Unfortunately, Colab does not support interactive widgets at the moment.

Maybe @tylere has more information on whether it will be available at some point!

**Comment by fitoprincipe** [comment]
Thank you @SylvainCorlay, when I started playing around with leaflet in colab I soon realize that ipywidgets did not work either. It would be a great feature for colab!

**Comment by SylvainCorlay** [comment]
Closing as it is not really related to ipyleaflet but more to colab.

**Comment by tylere** [comment]
I don't currently have any information on if/when this will be possible in Colab, but I plan on discussing this with the Colab team.

**Comment by sdll** [comment]
Any updates on this?

**Comment by omar-3** [comment]
any updates now?

**Comment by martinRenou** [comment]
You can follow the discussion here: https://github.com/googlecolab/colabtools/issues/60

**Comment by giswqs** [comment]
> You can follow the discussion here: [googlecolab/colabtools#60](https://github.com/googlecolab/colabtools/issues/60)

https://github.com/googlecolab/colabtools/issues/60 has been closed. Now we need to follow https://github.com/googlecolab/colabtools/issues/498

**Comment by timkpaine** [comment]
A helpful related discussion about not trying to build support for proprietary colab APIs one by one into jupyter extensions https://github.com/QuantStack/ipycytoscape/issues/148
