### ISSUE TITLE
wind-global.nc dataset missing from velocity example

### ISSUE THREAD

**Issue by tylere** [jupyter-widgets/ipyleaflet#200]
Users are unable to run the [velocity example](https://ipyleaflet.readthedocs.io/en/latest/api_reference/velocity.html) because of a missing dataset. The example should either include the dataset or give instructions for downloading it from elsewhere.

**Comment by SylvainCorlay** [comment]
Thanks for reporting.

In fact, the velocity example notebook has code to download the dataset.

Maybe we should add a note in the documentation about that.

**Comment by martinRenou** [comment]
Fixed #243
