### ISSUE TITLE
Adding text box to ipyleaflet map

### ISSUE THREAD

**Issue by mdmadhu** [jupyter-widgets/ipyleaflet#203]
Would be grateful if someone could point the way for me to add a text box (that can take some html) on to an ipyleaflet map? I am NOT looking for a popup at a map coordinate, but for something that can be tied to the coordinates of the map window (e.g., always remains at the bottom left).

**Comment by SylvainCorlay** [comment]
You can use the popup widget which accepts any Jupyter interactive widgets as content.

**Comment by martinRenou** [comment]
And if you really don't want to use the popup widget, you can create two textboxes using ipywidgets https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#FloatText, and link the value of those boxes to the latitude/longitude values

**Comment by mdmadhu** [comment]
@SylvainCorlay Thanks! I understand that it is possible to insert other Jupyter widgets into a popup widget, but what if I don't want a popup?

@martinRenou Thanks, but I am not able to understand how you're suggesting I implement it... would you be able to provide me some sample code that implements what you are suggesting and puts a text box on the bottom right of the map produced by the code below... 

```
from ipyleaflet import Map, basemaps

m_top = Map(center=[40, 0], zoom=10, basemap=basemaps.Esri.WorldTopoMap, attribution_control=False, zoom_control=False, layout=widget.Layout(height='800px'))

m_top
```

**Comment by martinRenou** [comment]
You could implement something like that:

```python
from ipyleaflet import Map, basemaps
from ipywidgets import Layout, HBox, VBox, FloatText, jslink

center = [40, 0]

m_top = Map(
    center=center, zoom=10, 
    basemap=basemaps.Esri.WorldTopoMap, 
    attribution_control=False, 
    zoom_control=False, 
    layout=Layout(height='800px')
)

# Create the two text boxes
latitude = FloatText(
    value=center[0],
    description='Lat:',
    disabled=True
)

longitude = FloatText(
    value=center[1],
    description='Lng:',
    disabled=True
)

# Create a callback for when the center of the map has changed
def on_center_change(change):
    new_center = change['new']
    latitude.value = new_center[0]
    longitude.value = new_center[1]

m_top.observe(on_center_change, names='center')

# Create the horizontal container containing the two textboxes
hbox = HBox([latitude, longitude])

# Create the horizontal container containing the map and the horizontal container
vbox = VBox([m_top, hbox])

# And display it
vbox
```
