### ISSUE TITLE
compatibility with Jupyterlab-0.33.2 ?

### ISSUE THREAD

**Issue by stonebig** [jupyter-widgets/ipyleaflet#204]
I get something else than my usual map, when I do this, with bqplot-0.11.0+Jupyterlab-0.33.2:
````
# ipyleaflet (javascript library usage)
from ipyleaflet import (
    Map, Marker, TileLayer, ImageOverlay, Polyline, Polygon,
    Rectangle, Circle, CircleMarker, GeoJSON, DrawControl
)
from traitlets import link
center = [34.6252978589571, -77.34580993652344]
m = Map(center=[34.6252978589571, -77.34580993652344], zoom=10)
dc = DrawControl()

def handle_draw(self, action, geo_json):
    print(action)
    print(geo_json)
m
m
````
![image](https://user-images.githubusercontent.com/4312421/43360215-b8945e08-92b1-11e8-982b-6a8c7af073ff.png)

**Comment by jasongrout** [comment]
Do standard widgets work for you?

**Comment by stonebig** [comment]
I just feeded this issue: https://github.com/jupyter-widgets/ipywidgets/issues/2153

does it answer the question ?

**Comment by stonebig** [comment]
error found: "jupyter labextension list" was not including jupyterlab-manager
