### ISSUE TITLE
MarkerCluster sample has wrong coordinates

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#205]
The official MarkerCluster example, https://ipyleaflet.readthedocs.io/en/latest/api_reference/marker_cluster.html, somehow results in a cluster of merkers displayed on readthedocs.io, but the coordinates used are very suspicious, and one might better subtract 360 from their longitudes, to get values in the likely more expected interval (-180, 180).

```python
from ipyleaflet import Map, Marker, MarkerCluster
m = Map(center=(50, 354), zoom=5) # notice longitude
marker1 = Marker(location=(50, 354)) # notice longitude values
marker2 = Marker(location=(52, 356))
marker3 = Marker(location=(48, 352))
marker_cluster = MarkerCluster(markers=(marker1, marker2, marker3))
m.add_layer(marker_cluster);
m
```

**Comment by SylvainCorlay** [comment]
Thanks, feel free to correct the coordinates to be around 0.

**Comment by deeplook** [comment]
Ok, will do...
