### ISSUE TITLE
Seeking recommendations for "streaming layers"

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#208]
I'm interested in building maps showing streaming content that gets updated to reflect changing data coming from somewhere. At the moment I'm doing this using what seems to me like a clunky workaround, namely, I'm generating layers and add/remove them to/from the map. This works better than I had expected, but the code is ugly and I assume there must be some performance losses with constantly creating new layer objects. I've put some code in [this gist](https://gist.github.com/deeplook/d4e5c77a1493b6dc3eaaa4304ef5f0a9) to illustrate this a little better than with prose.

Before I dig deeper into layers I just want to know if there is a chance to add the proper logic into the layer itself such that the map will also show the updates, because there is some wiring between both? Thanks!

**Comment by SylvainCorlay** [comment]
Hey @deeplook we already support a Video layer, which may fit some of your needs.

Also, there is ongoing work to enable the streaming of any widget content as webrtc, and included video stream into other widgets.

Finally, to merely update values of a layer like a heatmap, that should not be too hard to implement on the JS side.

**Comment by martinRenou** [comment]
Well that's actually a bug of `Heatmap`. Changing the `locations` attribute of your heatmap should work, no need to replace completely the widget .

This should work but doesn't:
```python
from ipyleaflet import Map, Heatmap
from random import uniform
import time

def create_random_data(length):
    "Return a list of some random lat/lon/value triples."
    return [[uniform(-80, 80), 
             uniform(-180, 180), 
             uniform(0, 1000)] for i in range(length)]

m = Map(center=[0, 0], zoom=2)

heat = Heatmap(locations=create_random_data(1000), radius=20, blur=10)
m.add_layer(heat)

for i in range(100):
    heat.locations = create_random_data(1000)
    time.sleep(0.1)

m
```

**Comment by martinRenou** [comment]
[This](https://github.com/jupyter-widgets/ipyleaflet/pull/211) should fix it, now keep in mind that you would have to replace the entire list of locations if you want the update to reflect on the map, it means that:
```python
heat.locations[36] = [36, 56, 223]
```
won't work. That's a limitation of traitlets.

**Comment by deeplook** [comment]
Thanks, that's already helpful. I've picked the Heatmap example because it's nice to see these changes there. But for my own stuff I need more to update markers and polygons. I've put some examples in this notebook, like isolines around locations (sadly with empty output cells because of credentials issues). To be continued... Looking forward to the future releases of ipyleaflet. Closing this now.
