### ISSUE TITLE
Add support for IGN tile layers

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipyleaflet#213]
https://geoservices.ign.fr/documentation/utilisation_web/wmts-leaflet.html

**Comment by SylvainCorlay** [comment]
I opened and issue with the geoportal folks here: https://github.com/IGNF/geoportal-extensions/issues/260

**Comment by HaudinFlorence** [comment]
A PR adding most of the GeoportailFrance wmts layers has just been merged on xyzservices depo : https://github.com/geopandas/xyzservices/pull/126. So these tilelayers may be soon available in ipyleaflet.
