### ISSUE TITLE
Zoom by scrolling with mouse wheel

### ISSUE THREAD

**Issue by fitoprincipe** [jupyter-widgets/ipyleaflet#214]
Is there a way to zoom by scrolling with the mouse wheel?

**Comment by SylvainCorlay** [comment]
Yes!

Setting `scroll_wheel_zoom=True` on the map should do it.

**Comment by fitoprincipe** [comment]
Oh! I usually check all class's methods before I ask, but missed that one. Sorry!

**Comment by Khirod1999** [comment]
Can you provide me the full code to support this?

**Comment by martinRenou** [comment]
```python
from ipyleaflet import Map

m = Map(scroll_wheel_zoom=True)
display(m)
```

**Comment by Khirod1999** [comment]
![15918618628297577041821478600304](https://user-images.githubusercontent.com/66769657/84359550-6d221780-abe6-11ea-9b4d-263b24efd437.jpg)
It says the following as shown in picture.

**Comment by martinRenou** [comment]
Please make sure to install ipyleaflet. If you have difficulties installing ipyleaflet you can ask for help on https://gitter.im/jupyter-widgets/Lobby or open another issue.
