### ISSUE TITLE
MarkerCluster's maxClusterRadius doesn't work

### ISSUE THREAD

**Issue by paulo-raca** [jupyter-widgets/ipyleaflet#216]
Hello,
I'm trying to adjust the `maxClusterRadius` argument of a MarkerCluster, but nothing seems to change.
I'm guessing this arguments isn't supported? Or am I doing something wrong?

```
        marker_cluster = MarkerCluster(
        maxClusterRadius=5,
        markers=[
            Marker(
                title=loc[0],
                location=loc[1], 
                #draggable=False,
                #radius=10,
                #stroke=False,
                #fill_opacity=1,
                #fill_color=matplotlib.colors.to_hex(color)
            )
            for loc in locs
        ])`
```

I also tried `max_cluster_radius`

Thank you

**Comment by martinRenou** [comment]
Hi, this attribute of MarkerCluster is not implemented in ipyleaflet. I'll take a look at this.
If you would like to implement it and know how to do it, feel free 😊
