### ISSUE TITLE
DrawControl: edit layers button not working

### ISSUE THREAD

**Issue by DavideDeMarchi** [jupyter-widgets/ipyleaflet#218]
Clicking button "Edit layers" on the DrawControl gives an error: Cannot read property 'className' of undefined on line leaflet.draw.js:8 and no edit is possible.
We are using version 0.9.0 of ipyleaflet.

Any idea on how to solve it?
Thanks!

![drawcontrol](https://user-images.githubusercontent.com/12296193/44768153-b06ddc00-ab60-11e8-953a-b00ecc6a7c78.png)

**Comment by Juanlu001** [comment]
I confirm that this is still the case with the latest version on the classical notebook.

**Comment by martinRenou** [comment]
Apparently, the `edit` button does work for editing circles or squares. But if you draw an arbitrary polygon, it doesn't work anymore. Maybe it's a version issue between the `Leaflet.draw` package and the base `Leaflet` package. I need to check.

**Comment by Kirill888** [comment]
I think this is due to using really old version of `leaflet-draw` plugin, I have tested it with version `1.0.4` and was able to edit just fine. This is using local "dev" install.

**Comment by martinRenou** [comment]
Fixed by #344
