### ISSUE TITLE
How to know when all tiles have loaded?

### ISSUE THREAD

**Issue by fitoprincipe** [jupyter-widgets/ipyleaflet#219]
Hi there,

I am making an interactive map visualizer for python's Google Earth Engine API, which is available in the `ui` module of [geetools](https://github.com/gee-community/gee_tools). 

If any of you have used GEE in the [code editor](https://code.earthengine.google.com/) before have seen that when a tile layer is loading, there is like a 'float progress' widget besides each layer label. I know it's ambitious because I haven't even seen that implemented on leaflet (may be it is), but it would be great to have something like that. I'd be happy if only I could know when the tile has finished loading, like a binary state (loading/loaded).

Another issue related to `geetools` development is [this](https://github.com/jupyter-widgets/ipyleaflet/issues/167).

Thank you!

**Comment by martinRenou** [comment]
Hi,

You can know when all the tiles are loaded for a `TileLayer`. Using the `on_load` method you can add a callback for when it finished loading:

```python
from ipyleaflet import *

m = Map(center=(52, 10), zoom=8, basemap=basemaps.Hydda.Full)

def handle_loaded(**kwargs):
    print("loaded!")

m.layers[0].on_load(handle_loaded)

m
```

Your callback will be triggered only when all tiles are loaded.

**Comment by fitoprincipe** [comment]
That's excellent, I'll make use of it. Thank you @martinRenou!
