### ISSUE TITLE
Supporting vector tiles?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#226]
What's the perspective for supporting vector tiles, anytime soon? This seems to be a working Leaflet plugin that renders Mapbox Vector Tiles on HTML5 Canvas (sort of a standard in the geo industry): https://github.com/SpatialServer/Leaflet.MapboxVectorTile

**Comment by martinRenou** [comment]
What do you think about this one: https://github.com/Leaflet/Leaflet.VectorGrid?
The package you linked to does not support `Leaflet` 1.x apparently https://github.com/SpatialServer/Leaflet.MapboxVectorTile/issues/78

**Comment by deeplook** [comment]
@martinRenou I've looked at a local version of their `docs/demo-vectortiles.html` file which sort of seems like the right thing, although I have not inspected the tile sources, yet.

**Comment by deeplook** [comment]
Is there any way to build more momentum for this? I can see nice examples like these for vector data on a map (in this case GeoJSON) as well as vector tiles in the basemap itself. And especially the latter would be a very nice feature for ipyleaflet.

- http://leaflet.github.io/Leaflet.VectorGrid/demo-geojson.html
- http://leaflet.github.io/Leaflet.VectorGrid/demo-vectortiles.html

**Comment by deeplook** [comment]
I think we can close this now as there is a vector tile implementation...
