### ISSUE TITLE
Max limit of points in Heatmap and Marker Cluster?

### ISSUE THREAD

**Issue by paul-harambee** [jupyter-widgets/ipyleaflet#238]
I am working in Jupyter Lab, when adding multiple points to either the Heatmap or Marker Cluster renderer, if I have more than a few 100 points, the map renders, but doesn't draw the layer. Dialing back the number of points results in the layer drawing on the map. Is this a Jupyter Lab specific thing? My thinking would be that if an upper limit is reached regarding the number of points these layers can support, then an error or warning should be thrown.

I have also tried adding a time.sleep() before calling the map view, but that doesn't seem to help the situation.

Any work around?

**Comment by martinRenou** [comment]
Are you sure about this number? A hundred points don't seem to be too much. The Heatmap example on the repo is using a thousand points, and I'm pretty sure it can do a lot more (I just tried it and it works fine to dynamically update 10 000 points for the heatmap layer).
Do you have a code example that replicates the issue you are seeing?

**Comment by martinRenou** [comment]
![test_heatmap](https://user-images.githubusercontent.com/21197331/49745919-540e7280-fca0-11e8-8475-c4be37dd9fce.gif)

**Comment by paul-harambee** [comment]
My apologies, I have figured out what caused this. My data is sitting in a pandas DataFrame. Some of the records have NaNs for their latitudes and longitudes (the joy of dirty data). It seems as though when these NaNs are used to construct points that feed the renderer it simply fails to draw the whole thing. Removing these records has solved the issue for me.

**Comment by martinRenou** [comment]
Ok :) Glad you found your issue!
