### ISSUE TITLE
[Question / Documentation] Difference with Folium package

### ISSUE THREAD

**Issue by mazzma12** [jupyter-widgets/ipyleaflet#240]
Hi,

I came to see ipyleaflet extension using jupyterlab to display raw geojson file and I wonder what are the main differences versus Folium. From my experience Folium is also integrated into jupyter notebooks and it also wraps leaflet package. 
I searched for 'folium' in the documentation and issues, but could not find hints about it.

**Comment by SylvainCorlay** [comment]
Hi @mazzma12 the main difference is the ipyleaflet is a widget library, so that you can

 - update what is in a map dynamically by changing its state
 - take input from the user on the map, or change the state from the front-end.
 - bind it to other widgets

while folium is "display only" .

**Comment by mazzma12** [comment]
Thank you for this very fast answer @SylvainCorlay !

That's really interesting, it enables way more possibilities regarding the integration. I have a few more questions regarding internal behaviour: 
* Are the API similar? 
* Can you convert a Folium map into an ipyleaflet widget seamlessly? 
* Are there things you can do with Folium that you cannot do with ipyleaflet

I guess I will find out trying but don't hesitate if you have time for a few more hints!

**Comment by SylvainCorlay** [comment]
> Are the API similar?

they are not similar

> Can you convert a Folium map into an ipyleaflet widget seamlessly?

nope

> Are there things you can do with Folium that you cannot do with ipyleaflet

maybe - I am not a user, but anything missing should be easily added to ipyleaflet.

**Comment by SylvainCorlay** [comment]
Also, ipyleaflet works with JupyterLab & Voila.

There is also a c++ backend called xleaflet to make maps in C++.
