### ISSUE TITLE
DivIcon layer

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipyleaflet#246]
It would be nice to have a `DivIcon` layer. This is a bit related to #207.
https://leafletjs.com/reference-1.3.4.html#divicon

**Comment by omanges** [comment]
@martinRenou  I would like to work on this issue for the JupyterCon sprint, please assign this to me 😊

**Comment by martinRenou** [comment]
Thks!

**Comment by martinRenou** [comment]
Fixed! Thanks @omanges
