### ISSUE TITLE
Improve support for marker & popup

### ISSUE THREAD

**Issue by galleon** [jupyter-widgets/ipyleaflet#25]
I would like to improve support for popup. I have seen that for popup you can create them but not much more. Can someone clarify what the initial intent was - and the foreseen associated syntax?

**Comment by SylvainCorlay** [comment]
@galleon it does not seem to be supported at the moment (I just got into this code base too). What we should probably do is have the popup hold a child `DOMWidget`, that could be any other DOMWidget... This is what we do in bqplot for tooltips.

**Comment by SylvainCorlay** [comment]
If you want to give it a try, the way to do this is to add

- a child widget on the Python side, serialized with `widget_serialization` (imported from ipywidgets)

```
class Popup(UILayer):
    _view_name = Unicode('LeafletPopupView').tag(sync=True)
    _model_name = Unicode('LeafletPopupModel').tag(sync=True)
    popup_content = Instance(DOMWidget, allow_none=True).tag(sync=True, **widget_serialization)
```

- the counterpart default value in `LeafletPopupModel`, set to `undefined` on the js side.
- Add the logic for rendering the child in the `LeafletPopupView`. For this, you can look at the ProxyView in ipywidgets to see how this works.

**Comment by galleon** [comment]
@SylvainCorlay I was looking at what was done in `bqplot` for tooltips and at `jupyter-widget-example` to try understand the philosophy. There seems to be 2 use-cases for the popups:
1. attachment to an object - the popup open/close on the object on click
2. or directly to a map - the popup has its own position

Will follow the steps describe previously

**Comment by SylvainCorlay** [comment]
👍

**Comment by galleon** [comment]
@SylvainCorlay I started playing with popups for the time being my content is a simple Unicode. Is there any doc on how event are managed? Currently events seem to be handled only for GeoJSON layers - am I correct?

**Comment by SylvainCorlay** [comment]
That is right. I introduced it in PR #17 fir thw sake of the bayeshack
hackathon. If the approach applies to more layer types we could move it up
to a base class..

**Comment by SylvainCorlay** [comment]
@galleon any news on this one?

**Comment by galleon** [comment]
@SylvainCorlay Sorry not much progress yet but my requirements are still there ... Still not clear on the connection with Python. Will share my code tomorrow - would you ahve time on gitter?

**Comment by bensteers** [comment]
Looking through the src, it seems like there hasn't been any progress on popup support. Are there plans for this in the near future?

**Comment by sherl0cks** [comment]
If anyone else stumbles on this, be advised that [folium](https://github.com/python-visualization/folium) provides this feature, as seen [here](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb)
