### ISSUE TITLE
WMSLayer(crs=...) param fails

### ISSUE THREAD

**Issue by eran-pinhas** [jupyter-widgets/ipyleaflet#255]
Hey guys, 

when using the `crs` param to WMSLayer the leaflet-src.js file gets it as string but expecting and object. so it errs :(

**Comment by SylvainCorlay** [comment]
Thanks @eran-pinhas!

This should be an easy fix. Feel free to open a PR.

**Comment by SylvainCorlay** [comment]
Great! For a development installation of ipyleaflet, you need

- an environment with core ipywidgets installed
- then install ipyleaflet in dev mode

```
pip install -e .  # install the python package in development mode from source directory
jupyter nbextension install --py --sys-prefix --symlink js  # symlink the ipyleaflet notebook extension in the jupyter config directory
jupyter nbextension enable --py --sys-prefix js  # enable the ipyleaflet notebook extension
```

then any npm install from the `js` dir will rebuild the bundle.

**Comment by eran-pinhas** [comment]
I have problems with configuring the environment...

but using by observation seems that this:

https://github.com/jupyter-widgets/ipyleaflet/blob/81a27020465a0cdc260bad1909ea391d6a3da5cb/js/src/jupyter-leaflet.js#L329-L337

should be something like this: 
```javascript
 var LeafletWMSLayerView = LeafletTileLayerView.extend({ 
     var options = this.get_options();
     if(options.CRS) {
          options.CRS = L.CRS[options.CRS]
     }

     create_obj: function () { 
         this.obj = L.tileLayer.wms( 
             this.model.get('url'), 
             options
         ); 
     }, 
 }); 
```

**and In addition** - the documentation should mention that the crs value should be on of [Earth, EPSG3395, EPSG3857, EPSG4326, Base, Simple]

BR

**Comment by martinRenou** [comment]
Thanks for reporting! Your bugfix looks good to me :)
Also, we should add a default value on the Python side:
https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L253
```python
crs = Unicode(allow_none=True, default_value=None).tag(sync=True, o=True)
```
should be:
```python
crs = Unicode("EPSG3857").tag(sync=True, o=True)
```
Then your wouldn't need the `if(options.CRS) {` check on the Javascript side.
Feel free to open a PR with this fix :)
