### ISSUE TITLE
Embedding widgets in Popups?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#256]
I wonder if there is already any support for embedding widgets in popups? Like in this use case on [mapnificent.net](http://www.mapnificent.net):

<img width="587" alt="screen shot 2019-01-02 at 23 56 29" src="https://user-images.githubusercontent.com/1001778/50617039-7a17e300-0eeb-11e9-8af9-bde1d4631e22.png">

**Comment by deeplook** [comment]
So awesome, thanks!!

**Comment by deeplook** [comment]
I've tried putting a Map into a Popup. Works, but seems to need heavy layouting specifications. If desired I can create another ticket with an example.

**Comment by martinRenou** [comment]
Yes, please do :) I had the same issue with a plot using bqplot. We need the popup size to adapt to the widget's size.
