### ISSUE TITLE
Serve local tiles with notebook

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-widgets/ipyleaflet#257]
Today it is not possible to set a path to local tiles, with something like:
```python
l = {'url': 'file:///home/user/path/to/tiles/{z}/{x}/{y}.png'}
m.add_layer(l)
```
Instead, the directory of the tiles has to be served with e.g.:
```bash
python -m http.server --bind 127.0.0.1
```
And the URL has to be set to `http://127.0.0.1:8000/{z}/{x}/{y}.png`.
Could it be done transparently with the notebook server?

**Comment by martinRenou** [comment]
I guess it depends on the browser you are using. Are you using Chrome/Chromium? I suppose it would work on Firefox. I can be wrong though.

**Comment by davidbrochart** [comment]
I tried with Firefox but it doesn't work either. Anyway, that would only work if the notebook server and client are on the same machine, because the URL is sent as-is to Leaflet, right?

**Comment by martinRenou** [comment]
Yes, it is sent to Leaflet as it is. Do you think it would be a good idea to replace `file://` by the exact URL of the notebook server before giving the URL to Leaflet? I guess it would work then. Now the question is: "How to get the URL of the Notebook server? Is there a good way to do that from Python?". I know that we can do that in Javascript, I think it's a better solution.

**Comment by davidbrochart** [comment]
It looks like the URLs of the Notebook servers can be retrieved with:
```python
from notebook import notebookapp
list(notebookapp.list_running_servers())
```
So we can take e.g. the first one with `[0]['url']` and append `/files/path_to_tiles/{z}/{x}/{y}.png`. `path_to_tiles` is relative to the directory where the notebook was launched.

**Comment by davidbrochart** [comment]
And yes, if the URL contains `file://` we resolve the following path relative to the notebook directory, which can be retrieved with `list(notebookapp.list_running_servers())[0]['notebook_dir']`. What do you think?

**Comment by davidbrochart** [comment]
But in the end, I'm not sure this has to go into IPyLeaflet. The workaround is easy enough.

**Comment by martinRenou** [comment]
I think it would make sense to add it to ipyleaflet, as a new layer `LocalTilesLayer`? Or as a helper function `get_local_tiles_url(tiles_path)`? I guess some people would be happy to have it in ipyleaflet
