### ISSUE TITLE
Click on map to add a marker?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#258]
I'm looking for a way to manually click on a map to create a marker at that location, but so far in vain. Is there any way to do that?

**Comment by martinRenou** [comment]
I think this should work:
```Python
def handle_click(**kwargs):
    if kwargs.get('type') == 'click':
        m.add_layer(Marker(location=kwargs.get('coordinates')))

m.on_interaction(handle_click)
```

**Comment by SylvainCorlay** [comment]
Closing!

**Comment by deeplook** [comment]
Thx!

**Comment by tsktsktsk123** [comment]
Thank you for your comment! I've been looking for a long while now in how to find the coordinates from a click event and this finally did the trick! It'd be an enormous help if the documentation shed some light on the possibilities of the .on_interaction method. Thanks enormously for this project, it's of great help.

**Comment by martinRenou** [comment]
>  It'd be an enormous help if the documentation shed some light on the possibilities of the .on_interaction method.

Indeed!
