### ISSUE TITLE
Polylines extending beyond map borders get filled incorrectly

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#259]
All the polylines I'm using are systematically filled incorrectly when the entire polyline does not fit anymore on the map, but extends into the non-visible area outside. See attached GIF.

![2019-01-09 11 25 05](https://user-images.githubusercontent.com/1001778/50893507-4bc16880-1401-11e9-9595-567a3b37b034.gif)

**Comment by martinRenou** [comment]
Weird... Is it really associated to the map? I mean, if you unzoom a bit do you still see this issue? I suspect this would be an issue of LeafletJS. But I'm unsure what causes this. Do you mind giving an example code that replicates the issue? 
My first guess would be that it has something to do with the [`fillRule` option](https://leafletjs.com/reference-1.4.0.html#polygon-fillrule) from `Path`. Unfortunately, this option is not in ipyleaflet. I could try adding it quickly and see if I can fix this issue changing the value.

**Comment by deeplook** [comment]
It's part of a much more elaborate isoline example I can donate later, maybe in a few days. In the meantime you can try with this simple code:

```python
from ipyleaflet import Map, Polyline
m = Map(center=(52.5, 13.4), zoom=11)
m += Polyline(
    locations=[(52.45, 13.35), (52.55, 13.45), (52.55, 13.35), (52.45, 13.35)],
    fill=True)
m
``` 

If you zoom out on the map or move it up/down so you see only a small part of it on the map you see the same behaviour. The effect seems to be worse if the polyline is not "closed" by itself (first point equals last), despite the `fill`flag used in both cases. I'm surprised nobody else noticed before. ;)

**Comment by deeplook** [comment]
@martinRenou I've committed the more complex use case here (you'll need credentials to retrieve the isoline data, though): https://github.com/deeplook/herestapis/blob/master/advanced_isolines.ipynb. Pointing to the gif (without rendering issues) here, too:

![image](https://github.com/deeplook/herestapis/raw/master/images/advanced_isolines.gif)

**Comment by martinRenou** [comment]
At this point I'm just trying things :P Can you try setting the `no_clip` attribute of the `Polyline` to `True`? In the example you gave me, something like this seems to work:
```Python
from ipyleaflet import Map, Polyline
m = Map(center=(52.5, 13.4), zoom=11)
p = Polyline(
    locations=[(52.45, 13.35), (52.55, 13.45), (52.55, 13.35), (52.45, 13.35)],
    no_clip = True,
    fill=True)
m += p
m
```
I guess that the clipping is a bit buggy in LeafletJS.

**Comment by deeplook** [comment]
The `no_clip=True` seems to do it, thanks! I could not find it documented on https://ipyleaflet.readthedocs.io/en/latest/index.html, though.

Polyline vs Polygon: I guess a Polygon would make sense when there could be wholes in it which in this case I don't expect, but I'll check again. Any other reason to prefer a Polygon? I don't see additional value like being able to do point in polygon tests, etc.

**Comment by SylvainCorlay** [comment]
@deeplook these are really cool examples!

**Comment by martinRenou** [comment]
Well, in your use case you will only use closed shapes, right? That's the reason I see for using `Polygon` :) I would use `Polyline` only if I want to draw line segments (and filling the line segments doesn't make sense to me, I guess it should not be filled by default).

**Comment by deeplook** [comment]
Ok, I guess I'll change to Polygon, then! ;) @SylvainCorlay, thanks!

**Comment by martinRenou** [comment]
Thanks for reporting the issue :) 
I think we should set `no_clip` to `True` by default, as it doesn't work well when some points are not displayed on the `Map` anymore.

**Comment by SylvainCorlay** [comment]
By the way, if you find fields that are undocumented, drop-by contributions to add them are always super welcome!

**Comment by deeplook** [comment]
Sure. Looking at https://leafletjs.com/reference-1.4.0.html#polyline I wonder if there is any convention for mapping leafletjs option names to ipyleaflet keyword argument names? In this case `noClip` to `no_clip`? I rememeber some months ago I wanted to do some GeoJSON styling in ipyleafet and I sort of gave up finding out what works and how it works.

Otherwise thanks again, and please feel free to close this...

**Comment by SylvainCorlay** [comment]
Yes, for widget attributes mapping to leaflet properties, we automatically convert `snake_case` to `camelCase`.
