### ISSUE TITLE
Maps inside Popups are not displayed as expected

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#260]
As marker popups can contain widgets you can put a map there, too. In principle this works, but the result is unexpected and the styling needs to be improved. You can also add the same map to the popup that contains the marker, building a "recursive map", but you probably should not do it as this seems to eat memory (tested only briefly on mybinder.org).

```
# maps inside maps ;)

from ipyleaflet import Map, Marker, Popup

center = (52.5, 13.4)
m = Map(center=center, zoom=12)
marker = Marker(location=center, popup=Map())
m += marker
m
```

![screen shot 2019-01-11 at 20 33 16](https://user-images.githubusercontent.com/1001778/51055450-2dfe2a00-15e0-11e9-8d00-b2e28b54062d.png)

**Comment by martinRenou** [comment]
> You can also add the same map to the popup that contains the marker, building a "recursive map"

Ahah! That's a crazy idea :P Funny that it works! I guess it's expected that it eats memory.

Thanks for reporting! I think it's not too difficult to fix, it must a CSS attribute to add or something like that.

**Comment by martinRenou** [comment]
I added more controls on the Popup size in [this PR](https://github.com/jupyter-widgets/ipyleaflet/pull/275), do you think it fixes your use case?

**Comment by deeplook** [comment]
Looks good to me!
