### ISSUE TITLE
Maps in VBox are only shown when also in HBox

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#263]
I noticed that Maps in VBox are only rendered when contained in an HBox, too. I would not expect this. See visual below. Maybe also related to #170.

<img width="773" alt="screen shot 2019-01-17 at 12 14 56" src="https://user-images.githubusercontent.com/1001778/51315270-14cb0280-1a52-11e9-879a-5ec5785aebbf.png">

**Comment by martinRenou** [comment]
Weird, I think @VasavanThiru also had this issue on his laptop, but I can't reproduce it.

**Comment by SylvainCorlay** [comment]
Ah, I can reproduce with Firefox. This might be due to the buggy implementation of the CSS flexbox in Firefox. We should be able to work around it.

**Comment by deeplook** [comment]
Yes, sorry I didn't mention I was on Firefox...
