### ISSUE TITLE
Custom marker icons

### ISSUE THREAD

**Issue by antonia-had** [jupyter-widgets/ipyleaflet#276]
Hi, 

Are custom icons for markers not working? It hasn't been working for me and it doesn't seem to work on the documentation example either: [https://ipyleaflet.readthedocs.io/en/latest/api_reference/icon.html](https://ipyleaflet.readthedocs.io/en/latest/api_reference/icon.html)

**Comment by martinRenou** [comment]
Thanks for the report! I'll try to fix it and make a release soon
