### ISSUE TITLE
Fullscreen control

### ISSUE THREAD

**Issue by fsteinmetz** [jupyter-widgets/ipyleaflet#284]
Adding a fullscreen button to a Map would be very useful, similarly to [Folium's fullscreen plugin](https://python-visualization.github.io/folium/docs-v0.6.0/plugins.html#folium.plugins.Fullscreen).

**Comment by martinRenou** [comment]
There is [three plugins](https://leafletjs.com/plugins.html#fullscreen-controls) for LeafletJS that does that, I guess [this one](https://github.com/Leaflet/Leaflet.fullscreen) is fine :) There is also a `fullscreenchange` event which will allow us to know the state of the control and update it on the Python side

**Comment by fsteinmetz** [comment]
Awesome, thanks!

**Comment by fsteinmetz** [comment]
However, I get "Error displaying widget"
```python
from ipyleaflet import Map, FullScreenControl
m = Map()
m.add_control(FullScreenControl())
m
```

**Comment by martinRenou** [comment]
Also, if you installed the extension using `jupyter nbextension install --py --symlink --sys-prefix ipyleaflet` some time ago, you need to rebuild the JavaScript using `cd js && npm install` from the root directory of the project.

**Comment by fsteinmetz** [comment]
Ok my bad, it works, at least in the notebook !
I just tried to `pip install git+https://github.com/jupyter-widgets/ipyleaflet.git` but I should have read the readme more carefully. I was a bit lost in the nbextension, labextension and how to properly install them.
Many thanks again !!!

**Comment by martinRenou** [comment]
If I have time I'll make a release this week with the new feature and the bug fixes. So you'll be able to install it with conda or pip :)

**Comment by fsteinmetz** [comment]
Great ! Then I may submit another feature request, just in case ;)

**Comment by martinRenou** [comment]
Feel free to open Pull Requests too :) I would be happy to merge them!

**Comment by fsteinmetz** [comment]
Yes sure, will do if I can ;)
