### ISSUE TITLE
Custom controls

### ISSUE THREAD

**Issue by fsteinmetz** [jupyter-widgets/ipyleaflet#288]
Is it possible to add custom widgets (ie, any ipywidget) as a control ?
I see I can add an ipywidget in a Popup, but adding it as a control would open nice possibilities, like color bars, legends...

**Comment by martinRenou** [comment]
That is a really nice idea, I never thought about it. It should not be too difficult to do it. We could name it something like `WidgetControl` on the Python side, and for the frontend we need to create a custom LeafletJs control. Maybe we can check how it's done in the [fullscreen control JS implementation](https://github.com/Leaflet/Leaflet.fullscreen/blob/gh-pages/dist/Leaflet.fullscreen.js) for creating a Contol.

**Comment by fsteinmetz** [comment]
Wow, awesome !!!
Thanks 👍
