### ISSUE TITLE
ipyleaflet draws

### ISSUE THREAD

**Issue by feraku** [jupyter-widgets/ipyleaflet#290]
If I draw  circles with map control in a map, how can I store in a variable?
I would like to save all circles that I draw in a geopandas dataframe
Thanks

**Comment by martinRenou** [comment]
Hi @feraku, did you try the draw control example of the repo? You can try it on mybinder: https://mybinder.org/v2/gh/jupyter-widgets/ipyleaflet/stable?filepath=examples

You can define a callback that will be called whenever you draw something on the map, here it is named `handle_draw`:
```python
dc = DrawControl(marker={'shapeOptions': {'color': '#0000FF'}},
                 rectangle={'shapeOptions': {'color': '#0000FF'}},
                 circle={'shapeOptions': {'color': '#0000FF'}},
                 circlemarker={},
                 )

def handle_draw(self, action, geo_json):
    print(action)
    print(geo_json)

dc.on_draw(handle_draw)
m.add_control(dc)
```
In this example it only prints the shape when you draw it, but you can get access to more information about the shape, location, size etc. from the `geo_json` parameter

**Comment by feraku** [comment]
First of all thanks for the reply
I try this:
```
dc = DrawControl(marker={'shapeOptions': {'color': '#0000FF'}},
                 rectangle={'shapeOptions': {'color': '#0000FF'}},
                 circle={'shapeOptions': {'color': '#0000FF'}},
                 circlemarker={},
                 )
poly_union = geopandas.GeoDataFrame()

def handle_draw(self, action, geo_json):
    print(action)
    print(geo_json)
    my_poly=dc.last_draw['geometry']['coordinates'][0]
    geom = Polygon(my_poly)
    poly_union=pandas.concat([poly_union,geom],sort=False)  
dc.on_draw(handle_draw)
m.add_control(dc)
```
But it doen't work, I would also have repeated edited objects

**Comment by martinRenou** [comment]
What is `Polygon` in your code? Is it the `ipyleaflet` class?

**Comment by feraku** [comment]
Thanks Martin, it seems that it already works

> from ipyleaflet import Map, basemaps, basemap_to_tiles, DrawControl, WMSLayer
> from shapely.geometry.polygon import Polygon
> import geopandas as gpd, pandas as pd
> 
> m = Map(center=(37, -1), zoom=14)
> wms = WMSLayer(url='http://www.ign.es/wms-inspire/pnoa-ma', 
>                layers='OI.OrthoimageCoverage',opacity=0.5,name="PNOA EBA")
> m.add_layer(wms)
> draw_control = DrawControl()
> draw_control.circle = {
>     "shapeOptions": {
>         "fillColor": "#efed69",
>         "color": "#efed69",
>         "fillOpacity": 0.5
>         }
>     }
> m.add_control(draw_control)
> poly_union = gpd.GeoDataFrame()
> def handle_draw(self, action, geo_json):
>     global poly_union
>     my_poly=draw_control.last_draw['geometry']['coordinates'][0]
>     geom = Polygon(my_poly)
>     #print(action)
>     print(geom)
>     poli= gpd.GeoDataFrame(geometry=[geom]) 
>     poly_union=pd.concat([poly_union,poli],sort=False) 
> #draw_control.on_draw(handle_draw)
> m

But the edit bottom doen`s work, thanks

**Comment by martinRenou** [comment]
Yeah the edit button is a known issue #218, we'll try to find time for fixing it. Happy that you found a solution to your problem! Is it fine for you if I close the issue?

**Comment by feraku** [comment]
Great Martin, thanks again
