### ISSUE TITLE
Use global L if it exists, or use noConflict()

### ISSUE THREAD

**Issue by drwelby** [jupyter-widgets/ipyleaflet#294]
When ipyleaflet loads, Leaflet takes over the global `L` variable. If Leaflet has already been loaded by another (non-ipyleaflet) cell, any other Leaflet plugins or controls that were also loaded disappear because their old Leaflet context is hijacked for `noConflict()`. 

Is it possible to conditionally load Leaflet (i.e. like `L = L || require('../leaflet');`) or otherwise isolate them (by using `noConflict()`)?

**Comment by martinRenou** [comment]
Sure :) Would you mind opening a PR for that? Leaflet is loaded in [this file](https://github.com/jupyter-widgets/ipyleaflet/blob/master/js/src/leaflet.js)

**Comment by drwelby** [comment]
OK, PR to master branch?

https://github.com/jupyter-widgets/ipyleaflet/commit/3db5ae4cb4e113bee3106021a8f52e69fcbd7671

**Comment by drwelby** [comment]
OK, PR to master?

**Comment by SylvainCorlay** [comment]
Sure, a PR to master wouod be great!

**Comment by drwelby** [comment]
ok, enjoy!

**Comment by martinRenou** [comment]
Fixed #295 thanks @drwelby !
