### ISSUE TITLE
allow xarray>0.11 in same environment as ipyleaflet

### ISSUE THREAD

**Issue by scottyhq** [jupyter-widgets/ipyleaflet#297]
It would be great to relax the upper bound on [xarray](https://github.com/pydata/xarray/releases) in setup.py to allow for more recent versions. Or as mentioned in this issue #212, it seems possible that the requirement can be dropped altogether. This change would allow both excellent packages to be installed up to their most recent versions in conda enviornments.

https://github.com/jupyter-widgets/ipyleaflet/blob/15f33691edf07438bfa9534f9c6949d529119632/setup.py#L139

**Comment by jhamman** [comment]
I took a look at the source code and I don't think the use of xarray warrants a strict version requirement. I think just requiring a xarray>=0.10 should be fine (could probably go back further if you wanted). The usage in ipyleaflet is pretty simple so I'd be surprised if version churn xarray impacted this project going forward.

**Comment by jhamman** [comment]
BTW, xarray v0.12 is due out in the next week or so. Another reason to not put a upper version limit...

**Comment by SylvainCorlay** [comment]
That would make sense to me as well.

**Comment by martinRenou** [comment]
Fixed #299
