### ISSUE TITLE
Create a web page showing all basemaps?

### ISSUE THREAD

**Issue by raybellwaves** [jupyter-widgets/ipyleaflet#302]
I'm trying to decide which basemap to use (https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py). If would be great is there was a webpage where I could simply scroll through to see them all.

**Comment by martinRenou** [comment]
Indeed, that would be a nice addition to the documentation. Also, that would be easier to keep track on which basemaps are not up to date (I'm thinking about your other issue #303)

**Comment by VasavanThiru** [comment]
Maybe this link will help you both, but I think that we will have to add some new maps in Ipyleaflet.

[All Maps](https://leaflet-extras.github.io/leaflet-providers/preview/)

@martinRenou 
@raybellwaves
