### ISSUE TITLE
basemap=basemaps.OpenMapSurfer returns empty

### ISSUE THREAD

**Issue by raybellwaves** [jupyter-widgets/ipyleaflet#303]
I was testing the basemaps and basemap=basemaps.OpenMapSurfer.Roads returns an empty map
![screen shot 2019-03-03 at 12 29 37 am](https://user-images.githubusercontent.com/17162724/53691417-74a01300-3d4b-11e9-8434-8aaf0dd65646.png)

As well as basemap=basemaps.OpenMapSurfer.Grayscale

**Comment by martinRenou** [comment]
Thanks for the report! Maybe the host is down, or the urls for OpenMapSurfer are not up to date
