### ISSUE TITLE
Capability Question: Is it possible to start an ipyleaflet instance from an *.py file and use it interactively?

### ISSUE THREAD

**Issue by rachelglenn** [jupyter-widgets/ipyleaflet#308]
Hi. I would like to open an ipyleaflet instance from my *.py program and then let the user use it interactively selecting points. The points that the user selects would then be feed back to the *.py program and processed, then updating the map.

-Rachel

**Comment by martinRenou** [comment]
Hi @rachelglenn, I think it is possible :)
As long as your user uses the Notebook or JupyterLab for interactions with the Map it is definitely possible.
You can create your *.py file next to the Notebook, and your user can import it from the Notebook and use the functions that are inside. If you need some help feel free to ask.

**Comment by martinRenou** [comment]
Closing, if you have any question don't hesitate to ask here
