### ISSUE TITLE
Add tms and zoomOffset options to TileLayer

### ISSUE THREAD

**Issue by kidpixo** [jupyter-widgets/ipyleaflet#31]
I'm trying to use some tiles I generated with custom maps. 

I already implemented a pure leaflet test [Leaflet Map Test](http://mariodamore.brapi.net/leaflet/map.html) and I was really excited to get all this in notebooks!

The biggest problem is that the `ipyleaflet.leaflet.TileLayer` cannot change all the parameter `leaflet.tilelayer` ([here](http://leafletjs.com/reference.html#tilelayer)) would accept. 

In particular, the `tms` and `zoomOffset` are critical to my application , I manages to hack the parameter directly in the js code from [jupyter-leaflet](https://www.npmjs.com/package/jupyter-leaflet) on my machine. 

![screen shot 2016-06-06 at 13 32 08](https://cloud.githubusercontent.com/assets/2255209/15820735/99adec22-2beb-11e6-8a90-b491d4368e7e.png)

Would be hard to implement this in ipyleaflet? In the js code the parameter are there, but commented out.
I haven't enough knowledge of the jupyter widget mechanism  and javascript to make this change.
![screen shot 2016-06-06 at 13 32 28](https://cloud.githubusercontent.com/assets/2255209/15820743/a2a30bdc-2beb-11e6-9c70-fa59f602321f.png)

Adding the `tms=true` paramter to `ipyleaflet.leaflet.TileLayer` inizialization doesn't affect the instantiated object, I guess while the class `TileLayer(RasterLayer)` in [leaflet.py](https://github.com/ellisonbg/ipyleaflet/blob/master/ipyleaflet/leaflet.py) doesn't have this parameter declared and cannot pass it further.

**Comment by Gerw88** [comment]
Hi, linking MapBox styles worked for me. (hope this helps). Described here:
https://github.com/rjleveque/geohack-2016/issues/1#issuecomment-296407866

**Comment by martinRenou** [comment]
The `tms` parameter has been added, we could add the `zoomOffset` and close this issue, see https://leafletjs.com/reference-1.7.1.html#tilelayer-zoomoffset

**Comment by jthetzel** [comment]
Another way to make this work with TMS schema as opposed to XYZ schema is to substitute `/{z}/{x}/{y}` with `/{z}/{x}/{-y}`.

Thanks to @[fasiha](https://gist.github.com/fasiha)
https://gist.github.com/tmcw/4954720?permalink_comment_id=3768325#gistcomment-3768325

**Comment by ned2** [comment]
@martinRenou would it take much work adding support for the `zoomOffset` param? if it's fairly straightforward, I'd be up for having a go at a PR. 

I'm trying to get support for 512px tiles from Mapbox, which requires setting `tile_size=512` to prevent super tiny fonts, but this in turn requires being able to add a `zoom_offset=-1` otherwise the map is all corrupted. 

See these links for background on this situation:
https://stackoverflow.com/questions/37040494/street-labels-in-mapbox-tile-layer-too-small
https://stackoverflow.com/questions/70389638/tilesize-at-512-causes-missing-bottom-half-of-tiles-and-shifting-coordinates

**Comment by ned2** [comment]
Heya @martinRenou, just submitted #1023 to add support for `zoomOffset`. Looks like it was just as simple as adding the param to both the Python and JS class. With this I was able to get Mapbox working with 512px tiles.

I haven't contributed to ipyleaflet before, so please lemme know if there's anything else I need to do!
