### ISSUE TITLE
add functionality from js library (polygon cluster, prune cluster)

### ISSUE THREAD

**Issue by koren88i** [jupyter-widgets/ipyleaflet#313]
I want to use 

1) https://github.com/SINTEF-9012/PruneCluster
2) http://jsfiddle.net/ve2huzxw/237/
3) https://js.do/code/165930

How can I create a new feature in ipyleaflet from vanilla js or a library on js leaflet?
Is that possible? Using custom ipywidgets?

**Comment by martinRenou** [comment]
It is possible. You can find the js package under `ipyleaflet/js`. Feel free to open a PR with your changes. And if you need some help for specific things, feel free to ask for help :)

**Comment by koren88i** [comment]
So you mean literally add new stuff to ipyleaflet?

I can't just "hook" some is code (library / function) to python code (like with custom widget in ipywidgets)

**Comment by martinRenou** [comment]
Yeah :) I mean, why not? If it makes sense to have it in ipyleaflet and could be useful for others, then yes. 

If PruneCluster is a lot faster, well made, and not too big, then maybe it's a good replacement for the default MarkerCluster library?

You can technically create your own custom widget. With the help of https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Custom.html, but instead of inheriting from base widgets classes you would inherit from ipyleaflet classes. I can help you through it if you want.

**Comment by koren88i** [comment]
got it.
I did not test prune vs. marker but from what I read it's suppose to be faster.
I do not think it has to replace markercluster but maybe have two options :)

Regarding the custom widget, I did the "hello world" example. But I do not really understand how to use that in the making of "polygon cluster".
I need to literally render the map in the backend js side and send it to the frontend python side. it's not a simple string value :) 

I'm more a data-engineer-ml guy but I am willing to dive in and add those two features to ipleaflet. But I would need help and guideness (js knowledge = 2/10 compared to java / python). 

How would you like to proceed?

thank you for answering btw!

**Comment by martinRenou** [comment]
> I need to literally render the map in the backend js side and send it to the frontend python side. it's not a simple string value :)

It's actually the opposite that's happening, the Python code is running on the back-end, and the JavaScript code on the front-end. The Map is living on the web-page (JS), only the map model containing the center position/zoom level... is living on the server (Python). And don't worry you don't need to render the map yourself, you can just reuse what's already done in ipyleaflet by creating classes that inherits from ipyleaflet classes.

[This file](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py) in ipyleaflet is where all the Python magic is happening, and [this folder](https://github.com/jupyter-widgets/ipyleaflet/tree/master/js/src/layers) is where all the actual JavaScript implementation is for each different layer (including polygon and markercluster).

If you would like to start with the polygon cluster I suggest you look at how `MarkerCluster` is implemented in Python. You would see that it's litteraly four lines of code, but the JavaScript code is longer and contains the actual creation of the cluster. I guess what you would need to do is create a new `ClusterablePolygon` class which inherits from `Polygon` and a new `PolygonCluster` class which inherits from `Layer`. It should be easy to implement the Python code. The JavaScript code will be trickier. But this should be a start (you would need to do something equivalent for `ClusterablePolygonModel` and `ClusterablePolygonView`): 

```Javascript
%%javascript
define('PolygonCluster', ["ipyleaflet"], function(ipyleaflet) {
    var PolygonClusterModel = ipyleaflet.LayerModel.extend(...);

    var PolygonClusterView = ipyleaflet.LayerView.extend({
        // Render the view.
        create_obj: function() {
            // Create here you polygon cluster
            this.obj = ...
        },
    });

    return {
        PolygonClusterModel: PolygonClusterModel,
        PolygonClusterView: PolygonClusterView
    };
});
```

**Comment by martinRenou** [comment]
Closing, if you have any question do not hesitate to ask :)
