### ISSUE TITLE
Anaconda Cannot Find ipleaflet module

### ISSUE THREAD

**Issue by perchslayer** [jupyter-widgets/ipyleaflet#320]
My `ipleaflet` module that I installed using the conda command can't be found by either the Jupyter Notebook or by Python 3.7 at the Anaconda Prompt:

`(base) C:\>python
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipleaflet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ipleaflet'
>>>`

I am running Anaconda on Windows 7.

**Comment by martinRenou** [comment]
It's ipyleaflet :)
Does `import ipyleaflet` work?

**Comment by martinRenou** [comment]
Closing it, feel free to any other question :)
