### ISSUE TITLE
Document the support for "simple" CRS's

### ISSUE THREAD

**Issue by eteq** [jupyter-widgets/ipyleaflet#327]
Perhaps I missed it, but I could not find any way to create an `ipyleaflet` `Map` that uses the built-in leaflet CRS's.  In particular I'm interested in the "simple"  one (E.g., https://leafletjs.com/examples/crs-simple/crs-simple.html). The idea here is that applying leaflet to more generic datasets than geo maps (my specific interest is a variety of astronomy applications) is a lot easier with the `Simple` CRS.

Depending on the answer, this issue could be either  "feature request", "where would I look to access the JS code that initializes map so that I can make a PR", or "the explanation of how should be in the docs".

Note this is a bit distinct from #70 mainly because that's a much more general thing.  This is about the built-in leaflet CRS's (especially `simple`)

**Comment by martinRenou** [comment]
What ipyleaflet version are you using? It has been introduced in the latest ipyleaflet release (0.10.1) a week ago.
You should be able to do: (It is not in the documentation though, we should add it)
```python
from ipyleaflet import Map

m = Map(crs="Simple")
```

**Comment by eteq** [comment]
Oh, that's fantastic, thanks @martinRenou!  I was working from a version I installed just a couple weeks ago and foolishly didn't think to check for a very recent update.

I will give it a try then. I'll also rename this issue to be about documenting that feature (will try to make a PR to do that myself, but might take a bit to get to it).

**Comment by martinRenou** [comment]
Perfect :) A PR would be awesome! Thanks for reporting

**Comment by pllim** [comment]
I can probably make a quick doc update if you tell me which page it should be in.

**Comment by martinRenou** [comment]
I guess it would be this page: https://ipyleaflet.readthedocs.io/en/latest/api_reference/map.html. Adding one line for the CRS attribute

**Comment by EvertWydoodt** [comment]
When trying to implement the solution suggested above:
` m = Map(crs="Simple")`
I get the following error: "TraitError: The 'crs' trait of a Map instance expected a dict, not the str 'Simple'.".
Which dictionary can I use in order to make the example work again?

**Comment by EvertWydoodt** [comment]
> When trying to implement the solution suggested above: ` m = Map(crs="Simple")` I get the following error: "TraitError: The 'crs' trait of a Map instance expected a dict, not the str 'Simple'.". Which dictionary can I use in order to make the example work again?

This fixed the issue. Could this be updated in the documentation?
```
from ipyleaflet.projections import projections
m = Map(crs = projections.Simple)
```

**Comment by martinRenou** [comment]
Thanks for reporting back!
