### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by pllim** [jupyter-widgets/ipyleaflet#332]
Hi. How do I get the cursor position out of the map? Thank you.

**Comment by martinRenou** [comment]
There is a notebook on the repo that does it:
```Python
from ipywidgets import Label
from ipyleaflet import Map

m = Map()

label = Label()
display(label)

def handle_interaction(**kwargs):
    if kwargs.get('type') == 'mousemove':
        label.value = str(kwargs.get('coordinates'))

m.on_interaction(handle_interaction)

m
```

**Comment by pllim** [comment]
Thanks for the quick response. What if I don't want the Earth coordinates, but rather raw offset values from the viewer's `(0, 0)`?

**Comment by martinRenou** [comment]
I guess you would need to compute them yourself, given the cursor position, the `south`, `north`, `east` and `west` Map attributes. If what you want is pixel coordinates it would also depend on the Map size in the DOM.

**Comment by pllim** [comment]
@eteq just told me about #327 and I think that is closer to what I actually need. Thank you!

**Comment by martinRenou** [comment]
Oh yeah, definitely!

**Comment by stepsbystep** [comment]
This is just great, amazing, so simple, thank you @martinRenou!!!
