### ISSUE TITLE
Errors when `@jupyterlab/geojson-extension` and `jupyter-leaflet` are both enabled

### ISSUE THREAD

**Issue by Kirill888** [jupyter-widgets/ipyleaflet#337]
Not sure where to report this issue as it is an interaction between

```
@jupyterlab/geojson-extension v0.18.1
jupyter-leaflet v0.10.1
```
using:

`jupyter-lab --version` is `0.35.4`

Individually both extensions work so long as the other one is disabled (I'm disabling at user level), but if both are enabled none work. They break with different error messages to the javascript console.

I'm not trying to use both in one notebook, separate notebooks

- Test notebook for GeoJSON
```python
from IPython.display import GeoJSON
GeoJSON({
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [-118.4563712, 34.0163116]
    }
})
```
- Test notebook for ipyleaflet
```python
from ipyleaflet import Map
Map(zoom=2)
```

Looks like some sort of vendor package clashing issue.

Links:
- https://github.com/jupyter-widgets/ipyleaflet
- https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension
- https://github.com/jupyterlab/jupyter-renderers/issues/189

**Comment by martinRenou** [comment]
Could you please share the error messages?

**Comment by Kirill888** [comment]
```bash
#!/bin/bash
set -e -u
env_path="$(pwd)/jup"
python3 -m venv "${env_path}"
source "${env_path}/bin/activate"
which pip
pip install --upgrade pip
pip install jupyterlab ipywidgets ipyleaflet
jupyter-labextension install --no-build @jupyter-widgets/jupyterlab-manager
jupyter-labextension install --no-build jupyter-leaflet
jupyter-labextension install --no-build @jupyterlab/geojson-extension
jupyter lab build
```

```

**Comment by martinRenou** [comment]
I think this is related to the changes you made @drwelby, would you mind taking a look at it?

**Comment by drwelby** [comment]
@Kirill888 can you also post the error message from the GeoJSON extension?

**Comment by Kirill888** [comment]
@drwelby 

```
index.js:220 TypeError: Cannot read property 'DomEvent' of undefined
    at NewClass.addHooks (leaflet.draw.js:9)
    at NewClass.enable (leaflet-src.js:5722)
    at NewClass.addHandler (leaflet-src.js:3736)
    at NewClass.init (leaflet-src.js:385)
    at NewClass.proto.callInitHooks (leaflet-src.js:357)
    at NewClass.initialize (leaflet-src.js:3148)
    at new NewClass (leaflet-src.js:301)
    at Object.createMap [as map] (leaflet-src.js:4709)
    at new RenderedGeoJSON (index.js:66)
    at Object.createRenderer (index.js:145)
```

**Comment by martinRenou** [comment]
Do you have it working in your use case @drwelby ?

**Comment by drwelby** [comment]
I haven't had a chance to try to reproduce, and I also don't know if JupyterLab loads extensions differently than Jupyter.

I assume the problem is the same as what my changes were trying to solve, where multiple extensions are trying to load Leaflet and they fight over the global `L`. In this case, either my solution isn't quite right, or the GeoJSON extension needs to follow the same pattern.

I'm going to open a Leaflet ticket asking for what's the best practice when multiple Leaflet libraries are loaded.

**Comment by drwelby** [comment]
There is an good response from core Leaflet dev Ivan Sanchez here:

https://github.com/Leaflet/Leaflet/issues/6624#issuecomment-486955984

I think he correctly identifies the problem as how plugins are loaded, and it matches with the error messages posted above with Leaflet.Draw not being found.

If I can find some time I'll investigate further but I could use some help looking for a good solution we can apply to all the Jupyter extensions that use Leaflet.

**Comment by Kirill888** [comment]
@drwelby I stepped through in the debugger, and the issue is that `L` already refers to a valid leaflet library (loaded by the other extension), and "previous" value of `L` is actually `undefined` (it is cached within leaflet library in variable `oldL`), so when you call `L.noConflict()` it replaces `window.L` with `undefined` and then plugins break.

**Comment by drwelby** [comment]
@Kirill888 good debugging work and I like your solution.
