### ISSUE TITLE
leaflet-draw plugin version is too old

### ISSUE THREAD

**Issue by Kirill888** [jupyter-widgets/ipyleaflet#342]
Current version of `leaflet-draw` on npm is `1.0.4`, but `ipyleaflet` is using version `0.4.14` 

Looks like `leaflet` changed enough to make this version break, see #218 for example. I have tried newest version of `leaflet-draw` in dev mode and it seems to work fine, so maybe worth upgrading. I have only tested draw control though, not sure what other parts are affected by this plugin.

- https://www.npmjs.com/package/leaflet-draw

**Comment by martinRenou** [comment]
I guess it's fine to update `leaflet-draw`, only the DrawControl layer depends on it if I'm correct. So if when updating we have everything working with DrawControl that is perfect. Would you like to open a PR?

**Comment by Kirill888** [comment]
@martinRenou sure, will do,  how do I update `package-lock.json`? Is it just the matter of having new enough npm? I'm not really familiar with js ecosystem.

**Comment by martinRenou** [comment]
I suppose you found the answer, `package-lock.json` is generated automatically by npm when doing `npm install`

**Comment by martinRenou** [comment]
Fixed by #344
