### ISSUE TITLE
Resizing via `m.layout.height = ..` doesn't resize actual map

### ISSUE THREAD

**Issue by Kirill888** [jupyter-widgets/ipyleaflet#345]
Enclosing container for leaflet map remains always at 400px

I believe this is due to this css rule (line 2):

https://github.com/jupyter-widgets/ipyleaflet/blob/fffb6e5197b856e6dc11d8d7f2e420b33bb09be7/js/src/jupyter-leaflet.css#L1-L5

This is on `master` branch.

**Comment by martinRenou** [comment]
Is the behavior on `master` different from the last release?

**Comment by Kirill888** [comment]
I think it was changing size correctly before I switched to master.
I think solution is to use `100%` instead of `400px`

**Comment by martinRenou** [comment]
Thanks for looking at it and for reporting the issue!

There were some recent changes on the layout, so it is possible that `master` is broken. Also, we need to check that ipyleaflet still works fine using a side-pane view or jupyterlab-sidecar, those features might also be broken.

**Comment by Kirill888** [comment]
But then you have to set default `height` via usual widget layout mechanisms, otherwise you get empty maps within HBox/VBox

**Comment by martinRenou** [comment]
This should be fixed on current master

**Comment by AndrewAnnex** [comment]
I am seeing this issue with 0.13.6, although I have a complicated jupyterlab/conda setup that maybe interfering. if other jupyter installs and conda environments should not matter then something is wrong
