### ISSUE TITLE
Support SVG marker icons

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#346]
It would be gorgeous to have SVG marker icons following like implemented in this component for leaflet: https://github.com/iatkin/leaflet-svgicon (screenshot from the linked example). Can anybody outline the work necessary to get there?

![Screenshot 2019-05-03 at 11 14 51](https://user-images.githubusercontent.com/1001778/57128802-db19cf80-6d94-11e9-88b8-1c9aba3397fe.png)

**Comment by martinRenou** [comment]
You could do something equivalent as the `Icon` class by creating a new `SVGIcon`, both from the [Python side](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L147) and from the [JavaScript side](https://github.com/jupyter-widgets/ipyleaflet/blob/master/js/src/layers/Icon.js). You would need to change the type of the [Marker.icon](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L167) attribute, by allowing `SVGIcon` instances.

**Comment by sackh** [comment]
@martinRenou - I would like to work on this issue, please assign this to me.

**Comment by martinRenou** [comment]
Great thanks a lot!

**Comment by deeplook** [comment]
Maybe this has become superfluous now with https://github.com/jupyter-widgets/ipyleaflet/pull/727?

**Comment by martinRenou** [comment]
I guess yes. Let's close it then :)
