### ISSUE TITLE
Layers control disappear when adding a layer

### ISSUE THREAD

**Issue by fitoprincipe** [jupyter-widgets/ipyleaflet#348]
Basically, if you first add the `LayersControl` first and then you add a layer, the controls disappear. To reproduce:

``` python
from ipyleaflet import *
m = Map(center=(52, 10), zoom=8, basemap=basemaps.Hydda.Full)
m
```
``` python
# Adding the control
m.add_control(LayersControl())
```
``` python
strata_all = basemap_to_tiles(basemaps.Strava.All)
m.add_layer(strata_all)
```

I found this (bad) behavior a while a go, but I though it could have something to do with me trying to contribute (modifying the code), but today I have tested it on binder (to be sure it's not my environment) and the bug appears too. There are no errors in the console, so it's hard to debug.

**Comment by fitoprincipe** [comment]
I've tested it at each release. It broke between version 0.9.2 and 0.10.0

**Comment by martinRenou** [comment]
> I've tested it at each release. It broke between version 0.9.2 and 0.10.0

Woaw, thanks for that! Maybe there was some changes related to `LayersControl` (LeafletJS version?) between those two versions

**Comment by fitoprincipe** [comment]
I've checke commit by commit, and the one that breaks it is https://github.com/jupyter-widgets/ipyleaflet/commit/c8b193f55b398f7c5a0a65d25b9dcbbb0c970f5d

**Comment by martinRenou** [comment]
Mmmh ok, I'm not sure I understand why

**Comment by fitoprincipe** [comment]
I added the removed code and worked again..

``` javascript
create_obj: function () {
        var that = this;
        return Promise.all(this.map_view.layer_views.views).then(function(views) {
            var baselayers = views.reduce(function (ov, view) {
                if (view.model.get("base"))
                {
                    ov[view.model.get("name")] = view.obj;
                }
                return ov;
            }, {});
            var overlays = views.reduce(function (ov, view) {
                if (!(view.model.get("base")))
                {
                    ov[view.model.get("name")] = view.obj;
                }
                return ov;
            }, {});
            that.obj = L.control.layers(baselayers, overlays);
            return that;
        }).then(function() {
               that.obj.addTo(that.map_view.obj);
        });
    }
```

**Comment by martinRenou** [comment]
Ok :D Well sorry for that. Is it the same for `MeasureControl` which I changed in the same commit?

**Comment by fitoprincipe** [comment]
Nop, `MeasureControl` works fine and worked fine before too

**Comment by fitoprincipe** [comment]
Hi @martinRenou, do you want me to open a PR for this? or will you review the commit?

**Comment by martinRenou** [comment]
If you would like to open a PR for this I would be happy to press the green merge button :) I really don't get what the issue is here. I guess I would need to dig a bit in the LeafletJS code to understand what is going wrong. Maybe the `LayersControl.addTo(Map)` does something different than the `Map.addControl(LeafletControl)` which is called.

**Comment by fitoprincipe** [comment]
What I've seen is that every time you add a layer, the function `create_obj` of `LeafletLayersControlView` is executed, goes over each `layer_view` adding all layers to the control.. so that is why I called the PR `add layers control to map every time a layer is added`, because I **guess** this is what the added lines are doing

**Comment by martinRenou** [comment]
Hum I see... So every single time there is a new layer the Control must be removed by LeafletJS, and we add it again, is that it?

**Comment by fitoprincipe** [comment]
Seems to work like that.. can't be sure though

**Comment by fitoprincipe** [comment]
@martinRenou, I have a simple question that does not deserve a new issue.. what is the plan for a new release? Are there milestones? I'd like to `pip install -U` in my other projects.. My be I could help to reach a new release =)

**Comment by martinRenou** [comment]
I can make a release right now :) There are no real plans. I only try to make releases often enough. There were some bug fixes and your new `MapStyle` feature since the last release, I guess it is fine to do it now.

**Comment by martinRenou** [comment]
Making a release :) You should be able to install 0.10.2 soon. We would need to update the documentation.
