### ISSUE TITLE
Please document Choropleth parameters

### ISSUE THREAD

**Issue by kannes** [jupyter-widgets/ipyleaflet#361]
https://github.com/jupyter-widgets/ipyleaflet/blob/master/docs/source/api_reference/choropleth.rst says 

`geo_data`: Data dictionary

`choro_data`: Choropleth data dictionary

but has no details as to what should be in those dictionaries and how they should be structured. Please link to some references "upstream" if available or document their structure right there. Thank you!

**Comment by VasavanThiru** [comment]
Hi kannes, 

`geo_data`  is a dictionary that takes these arguments as keys :  

{"type": "FeatureCollection",
 "features":[ {"type":"Feature",
                      "id":"AL",
                      "properties":{"name":"Alabama"},
                       "geometry":{"type":"Polygon",
                                           "coordinates": [[[-87.359296,35.00118]]]  ...

You can check this link for seeing the file that was used :

[https://raw.githubusercontent.com/jupyter-widgets/ipyleaflet/master/examples/us-states.json](url)

 `choro_data` is also a dictionary that takes 'id' as key and a float as value, it's for building colormap scale, like this : 

{'AL': 7.1,
 'AK': 6.8 }                             
 
Finally, you can launch the binder link for seeing these dictionaries in Choropleth.ipynb : 

[https://mybinder.org/v2/gh/jupyter-widgets/ipyleaflet/stable?filepath=examples](url)

**Comment by VasavanThiru** [comment]
[Raw dictionary](https://raw.githubusercontent.com/jupyter-widgets/ipyleaflet/master/examples/us-states.json)

[Binder Link](https://mybinder.org/v2/gh/jupyter-widgets/ipyleaflet/stable?filepath=examples)

**Comment by martinRenou** [comment]
I just want to add that `geo_data` is basically your GeoJSON data, using the [GeoJSON specification](https://geojson.org/), you can also look at this [wikipedia link](https://en.wikipedia.org/wiki/GeoJSON).

We should improve the documentation before closing this issue

**Comment by martinRenou** [comment]
This is a bug, when the Choropleth layer computes the `value_min` and `value_max` I suppose it should cast it to float.

**Comment by bill-coman** [comment]
Any thoughts on the workaround? I had the Choropleth working yesterday with the same data.  Bizarre right?

**Comment by martinRenou** [comment]
What is the type of your `theData1` variable? I suspect it contains `numpy.int64`s. Maybe you can try converting them as floating point values?

**Comment by bill-coman** [comment]
That is actually the most probable issue.  I was working with population density yesterday but population today.  

You the man!

Thanks for the input.

**Comment by martinRenou** [comment]
Sure! :) It should be fixed in the Choropleth layer though. I'll open an issue, thanks a lot for reporting!

**Comment by bill-coman** [comment]
No problem, I noticed one other issue yesterday which I can report if you want.

Will take me a moment to recreate it.

Is there a limit to the size/length of the geoJSON data?

**Comment by martinRenou** [comment]
> I noticed one other issue yesterday which I can report if you want

That would be awesome! Also if you are comfortable with or want to learn JavaScript/Python, please consider opening Pull Requests as well, that would be even more awesome :)

> Is there a limit to the size/length of the geoJSON data?

There is no limit. At least ipyleaflet will not prevent you to pass a huge GeoJSON.
