### ISSUE TITLE
Using circle markers for GeoJSON Points?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#362]
Is there a way to use circle markers instead of the normal "pin" markers when rendering GeoJSON Points or MultiPoints? I have some hope that this might be rendered more efficiently for a large amount of points. And, yes, I know about the existing clustering. ;)

**Comment by bjorm** [comment]
My solution so far looks like this:
![geojson points with CircleMarker](https://i.postimg.cc/44mwWdyF/2019-11-04-13-37-10-127-0-0-1-a07562bd1314.png)

You can pass all options listed at https://leafletjs.com/reference-1.5.0.html#circlemarker. If you don't pass `point_style` it will fall back to the pin marker. It also works for `MultiPoints`

Maybe this could solve #188 as well

**Comment by drf5n** [comment]
Does this work with GeoData as well?

**Comment by martinRenou** [comment]
Closing as fixed.
