### ISSUE TITLE
LayerGroup not rendering?

### ISSUE THREAD

**Issue by Kevin-McIsaac** [jupyter-widgets/ipyleaflet#37]
I wanted to use LayerGroup()  to create a  layer of markers, however I can't get it to render on the map. 

After extensive reading of the python and java script to understand how this might be done, my code looks like this.

```
center = [-33.858840, 151.206701]
zoom = 0
map_nsw = ll.Map(default_tiles=ll.TileLayer(opacity=1.0),
           center=center, zoom=zoom)

lg = ll.LayerGroup()
mark = ll.Marker(location=center)
c = ll.Circle(location=center)
lg.layers = [mark, c]
map_nsw += lg
map_nsw
```

What have I missed or isn't LayerGroup implemented.

**Comment by SylvainCorlay** [comment]
Thanks for looking into this!
