### ISSUE TITLE
[Question] How to add onclick-popups to GeoJson (and Choropleth or GeoData) layer? 

### ISSUE THREAD

**Issue by ookgezellig** [jupyter-widgets/ipyleaflet#371]
As I have not been able to find an answer anywhere, please let me ask here. 

I've made a map very similar to the one in https://ipyleaflet.readthedocs.io/en/latest/api_reference/geodata.html (but in my case for 355 municipalities in The Netherlands).  Now I would like to add on-click popups to each country, in which population and land area figures for each country are displayed. Is this even possible?

I've mananged to add popups to individual circles/squares/markers in a [LayerGroup ](https://ipyleaflet.readthedocs.io/en/latest/api_reference/layer_group.html), so I suspect it should also be possible to add a popup to 1 individual GeoJson municipality geoshape, and then grouping 355 municipality geoshapes into one layer, but that seems overcomplicating things, and it will probably be slow to render.

I notice that the [GeoJSON layer](https://ipyleaflet.readthedocs.io/en/latest/api_reference/geo_json.html) has the on-click method enabled, so i tried something like  geojsonlayer.on_click=HTML("Popup contents"), but this fails (as does my Leaflet knowledge here)

Any tips or insights how to possibly tackle this?

**Comment by kgiacobbi** [comment]
Hi, 
The `on_click` method is working like this:
```
def my_method(**kwargs):
    #do your code here

geosonlayer.on_click(my_method)
```

**Comment by martinRenou** [comment]
You have an example on the repo here: https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/CountriesGeoJSON.ipynb. It's using `on_hover` but you can achieve something similar with the `on_click`.

**Comment by dwr-psandhu** [comment]
@martinRenou on_hover and on_click events calls have very different arguments. I used the above example and changed on_hover to on_click and there is no reference to the geojson feature that was clicked on ? Just the coordinates and event. Should I open an issue?

**Comment by martinRenou** [comment]
Oh yeah sorry. I think it makes sense to open an issue for that. It should
have the same API as on_hover.

**Comment by martinRenou** [comment]
Closing. This would need some changes in the code base for the `on_click` to work properly in your use-case. Sorry we could not give a proper response to your question.

**Comment by karmalegend** [comment]
Quite late to it but i was dealing with the same problem and i found a solution (atleast one that works for me)

`TypeError                                 Traceback (most recent call last)
TypeError: click_handler() got an unexpected keyword argument 'type'`

Every "unexpected keyword argument" can be bypassed if you set the argument in the function as follows
`def click_handler(type=None,arg2=None,arg3=None)`

and so forth, it's not pretty but atleast that way you can use it.
