### ISSUE TITLE
In the geojson layer the on_hover and on_click events calls have very different arguments.

### ISSUE THREAD

**Issue by dwr-psandhu** [jupyter-widgets/ipyleaflet#373]
@martinRenou on_hover and on_click events calls have very different arguments. I used the above example and changed on_hover to on_click and there is no reference to the geojson feature that was clicked on ? Just the coordinates and event. Should I open an issue?

To reproduce change the on_hover function in example above to be called on_click and click on any geojson feature
```javascript
def click_handler(event=None, id=None, properties=None):
    label.value = properties['geounit']

layer.on_click(click_handler)
```
...
```
TypeError                                 Traceback (most recent call last)
TypeError: click_handler() got an unexpected keyword argument 'type'
```

_Originally posted by @dwr-psandhu in https://github.com/jupyter-widgets/ipyleaflet/issues/371#issuecomment-500142571_

**Comment by dwr-psandhu** [comment]
Additional Info: On click the handler gets called twice. I suspect its once from the leaflet geojson registration with the expected set of arguments and then again from the Map registration with only {type:'click', coordinates:...} arguments. 
Workaround: in click handler code check if properties is None and return to avoid second call.

**Comment by martinRenou** [comment]
Mmmh. I see what's wrong now.

The `Layer` class registers the click, but the `GeoJSON` class does it as well. We need to fix this.
