### ISSUE TITLE
Concept of tiling and/or level of detail for data layers?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#374]
I'd like to have some concept of "level of detail" which would allow to show data layers depending on the zoom level, which then would need to be "tiled data" in some sense, too. I'm able to show this with a funky tile server in the attached example serving tiles alternating between two basemaps, but ideally this would work for data layers, like GeoJSON rendered with a level of details depending on the zoom level.

It could be doable now with some more manual work if there is a hook I can use when the zoom level changes. Maybe I have to dig a bit deeper. But the map is kind of neat so I'm posting it here... ;)

```python
import multiprocessing, requests, flask, ipyleaflet
app = flask.Flask(__name__)

@app.route("/scramble/<int:z>/<int:x>/<int:y>")
def scramble(z, x, y):
    urls = [ipyleaflet.basemaps.Esri[name]['url'] for name in ['WorldStreetMap', 'WorldTopoMap']]
    img = requests.get(urls[(x + y) % 2].format(x=x, y=y, z=z)).content
    return flask.Response(img, mimetype='image/png')

multiprocessing.Process(target=app.run).start()
ts = {'url': 'http://localhost:5000/scramble/{z}/{x}/{y}', 'attribution': 'Scrambled Tiles'}
ipyleaflet.Map(center=(48.86, 2.34), level=10, basemap=ts)
```

<img width="837" alt="Screenshot 2019-06-09 at 21 13 42" src="https://user-images.githubusercontent.com/1001778/59163050-b6371b80-8afb-11e9-92b5-73bb7209b3ef.png">

**Comment by deeplook** [comment]
Ok, thanks to @martinRenou I realize I can use this hook to implement the feature manually.I'll experiment with that and see if any generalization is possible/desireable...

```python
def on_zoom_change(*args, **kwargs):
    pass

map.observe(on_zoom_change, 'zoom')
```

**Comment by martinRenou** [comment]
I suppose we should put in the documentation a link to `traitlets` and `ipywidgets`, the fact that `ipyleaflet` uses `traitlets` is an important information for knowing how to use it for dynamic updates/callbacks on attribute change
