### ISSUE TITLE
Not compatible with ipywidgets 7.5.0rc0

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipyleaflet#396]
Doing a quick test after on the `BaseMap.ipynb` example after `pip install ipywidgets==7.5rc0`.

```
utils.js:91 Error: Could not create a model.
    at utils.js:91
kernel.js:1007 Couldn't process kernel message TypeError: n._deserialize_state is not a function
    at l._make_model (manager-base.js:206)
```

**Comment by jtpio** [comment]
Same for `ipyvolume`, testing in the classic notebook.

cc @SylvainCorlay who was I think talking about an upcoming rc1 release

**Comment by stonebig** [comment]
apparently, same problem with ipywidgets-7.5.0rc1

**Comment by jtpio** [comment]
I think it's related to https://github.com/jupyter-widgets/ipywidgets/issues/2470

**Comment by stonebig** [comment]
ipyleaflet-0.10.8 + Jupyter-leaflet-0.10.7 seems still not ok with ipywidgets-7.5.0 on jupyterlab-1.0.0

**Comment by jtpio** [comment]
@stonebig should now be fixed with ipyleaflet 0.11.0 which brings:

- https://github.com/jupyter-widgets/ipyleaflet/commit/45f0f512d814c893f121166c49088dad5a2add3f
- https://github.com/jupyter-widgets/ipyleaflet/commit/a2c383d73884bf2f05f7ef4987248876171d993b

**Comment by stonebig** [comment]
hum, something is not right on my test bed... "Error displaying widget: model not found"
![image](https://user-images.githubusercontent.com/4312421/60547443-f74bd580-9d1f-11e9-8ac8-96d34252d80b.png)

**Comment by martinRenou** [comment]
Did you forget to run 
```
jupyter labextension install jupyter-leaflet bqplot
```
?

**Comment by stonebig** [comment]
will retry with Jupyterlab-1.0.1

**Comment by stonebig** [comment]
I don't find what's the issue with me:
![image](https://user-images.githubusercontent.com/4312421/60681371-4b28fc80-9e8f-11e9-8c7d-16d7e1757f0a.png)

![image](https://user-images.githubusercontent.com/4312421/60681358-364c6900-9e8f-11e9-814c-330af875d64f.png)

**Comment by stonebig** [comment]
now it's ok with 
![image](https://user-images.githubusercontent.com/4312421/60687278-c8636a00-9ead-11e9-9e33-18aa9c9c3e21.png)

**Comment by martinRenou** [comment]
Happy you could make it work! I'm not sure ipympl is working in your
environment though. You need jupyter-matplotlib 0.3.1 if you have JLab 1.0

**Comment by stonebig** [comment]
well, I noticed I don't test it, 
![image](https://user-images.githubusercontent.com/4312421/60687623-ea5dec00-9eaf-11e9-9dab-75c03a086ed3.png)
