### ISSUE TITLE
Plot shapefile or KMZ in ipyleaflet

### ISSUE THREAD

**Issue by tgrout** [jupyter-widgets/ipyleaflet#411]
Is there a way to plot a shapefile or a KMZ located on my local machine on a map without using geopandas?  Thanks

**Comment by tgrout** [comment]
I have a solution in case any other newbie has this same issue.  
Convert your shapefile to a GeoJson file.  This can be done using Arcpy (arcpy.conversion.FeaturesToJSON), I am sure there other ways to do it if you don't have access to arcpy.

Once the GeoJson is created (in WGS84 coordinate system), then type the following:

from ipyleaflet import Map, GeoJSON
import json

with open(Your_GeoJSON_file,'r') as f:
  data = json.load(f)
center = (35.362, -97.549) #or your desired coordinates
m = Map(center=center, zoom=15)
geo_json = GeoJSON(data=data, style = {'color': 'Blue', 'opacity':1, 'weight':1.9, 'dashArray':'9', 'fillOpacity':0.1})
m.add_layer(geo_json)
m

![image](https://user-images.githubusercontent.com/48166521/62262911-fb7f1780-b3df-11e9-8411-3124c439136c.png)

**Comment by jasongrout** [comment]
Cool! Thanks for posting an answer for future readers.
