### ISSUE TITLE
Animated / moving markers

### ISSUE THREAD

**Issue by psychemedia** [jupyter-widgets/ipyleaflet#412]
Is there a way of animating one or more markers using `ipyleaflet`?

For example, suppose I have a dataframe containing `lat`, `lon` and `timestamp` columns, could that easily be rendered as a moving marker, either with or without a t(r)ail?

Or alternatively, a dataframe containing `lat`, `lon`, `timestamp` and `group` columns, rendered as separate moving markers, either with or without distinctly coloured t(r)ails?

Poking around, there seem to be a few related *leaflet.js* plugins, eg https://github.com/mohsen1/leaflet-moving-marker or https://github.com/IvanSanchez/Leaflet.Polyline.SnakeAnim ,  though none with notebook demos that I've yet found.

**Comment by martinRenou** [comment]
Because ipyleaflet is based on ipywidgets, markers can already be moved dynamically from Python. It is just a matter setting the new location to your `Marker`(s), and you will see it updates. If you want to create a small animation you would need to create it from Python, using a small `for` loop:

```python
from time import sleep
from ipyleaflet import *

m = Map(center=(52, 10), zoom=8, basemap=basemaps.Hydda.Full)

start_location = (51.5, 10)
end_location = (52.2, 10)

mark = Marker(location=start_location)
m.add_layer(mark)

# Animation part
nb_steps = 10
step = 0.1

for i in range(nb_steps + 1):
    percentage_animation = i / nb_steps
    
    a = 1 - percentage_animation
    b = percentage_animation
    
    mark.location = (a * start_location[0] + b * end_location[0], a * start_location[1] + b * end_location[1])
    
    sleep(step)
```

You could make it an `animate` function that takes a `marker`, a `start_location` and `end_location`, a `nb_steps` and `step` arguments. And I'm almost sure nothing stops you from spawning this `animation` function in a separate thread if you don't want it to stop your main Python thread, or want to animate multiple markers at once.

**Comment by psychemedia** [comment]
That looks really handy... will give it a go... thanks...

**Comment by martinRenou** [comment]
If you can come up with a nice example using your dataframes with multiple markers moving at the same time, please consider contributing to the notebook examples in ipyleaflet! :)

**Comment by psychemedia** [comment]
Will do... just about to break for a holiday (well away from keyboard..) but will try to pop something together when I get back...

**Comment by martinRenou** [comment]
Thanks! Closing this issue. Feel free to ask other questions concerning the marker animation here if need be :)

**Comment by omar-3** [comment]
Anyone hacked his way around that? @martinRenou example didn't work on my machine

**Comment by martinRenou** [comment]
What is not working? Do you have an error message?

**Comment by omar-3** [comment]
@martinRenou I took the code as it is and copied in a jupyter notebook and nothing happens at all.

Just the static map with a pointer at one location.

Any ideas?

**Comment by martinRenou** [comment]
Yes, I suspect you are putting the entire code in one single cell, which means the map will be displayed after the animation is finished.

Try putting the map creation in the first cell, and the animation's for-loop in the second cell.

**Comment by omar-3** [comment]
@martinRenou still nothing at the output too

**Comment by martinRenou** [comment]
Could you share with me the Notebook you are using? So that I can debug it :)

**Comment by omar-3** [comment]
sorry for the delay, here is the notebook

https://gist.github.com/omar-3/e2b6c011c613725c14914e9534b847f0

**Comment by omar-3** [comment]
> Could you share with me the Notebook you are using? So that I can debug it :)

I made it work, thank you
