### ISSUE TITLE
DeprecationWarnings about traits

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#414]
I keep getting warnings like these (using `traitlets 4.3.2`). Should these be addressed? 

```
.../lib/python3.7/site-packages/ipyleaflet/leaflet.py:587: DeprecationWarning: 
    Traits should be given as instances, not types (for example, `Int()`, not `Int`).
    Passing types is deprecated in traitlets 4.1.
    options = List(trait=Unicode).tag(sync=True)

.../lib/python3.7/site-packages/ipyleaflet/leaflet.py:434: DeprecationWarning:
    metadata {'trait': <traitlets.traitlets.Instance object at 0x121d827f0>} was set from the constructor.
    With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
    markers = Tuple(trait=Instance(Marker)).tag(sync=True, **widget_serialization)
```

**Comment by martinRenou** [comment]
Thanks for the report. It should be easy to address.

**Comment by martinRenou** [comment]
Fixed by #420, thanks @stephaniegott :)

**Comment by xoolive** [comment]
Any plan to make a release which includes this fix?

**Comment by martinRenou** [comment]
Doesn't 0.11.2 include this fix already?

**Comment by xoolive** [comment]
doesn't seem so... 😞

**Comment by martinRenou** [comment]
I'll have a look at it tomorrow 😊 I might make a release

**Comment by xoolive** [comment]
The day after tomorrow is fine as well!

But it's weird: if I only import ipyleaflet, I don't get the warning. I only get if leaflet is imported through an extra library...

<img width="713" alt="Capture d’écran 2019-10-04 à 22 09 22" src="https://user-images.githubusercontent.com/1360812/66236917-001fbf00-e6f4-11e9-9692-44e5a1373ac1.png">

**Comment by martinRenou** [comment]
`0.11.3` is out :)

You should be able to install it with pip already. The conda package will come today.

**Comment by xoolive** [comment]
Thanks, there are indeed many less warnings!
But still some :)

In leaflet.py, there are few (3 or 4) such lines which raise a warning:
```python
Tuple(trait=Instance(Marker)).tag(sync=true, etc.)
```

to be replaced by 

```python
Tuple().tag(trait=Instance(Marker)sync=true, etc.)
```

For example: https://github.com/jupyter-widgets/ipyleaflet/blob/d73bf9a0872f90f74f4b956709c8e46f753591e6/ipyleaflet/leaflet.py#L442

There is also another warning raised by Dataset() but the error comes from https://github.com/jupyter-widgets/traittypes/blob/0a030b928991dec732c17a7a1cb13acbcd7650a2/traittypes/traittypes.py#L269 where dtype should be part of tag as well:

```
site-packages/ipyleaflet/leaflet.py:316: DeprecationWarning: metadata {'dtype': None} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  data = Dataset().tag(dtype=None, sync=True, to_json=ds_x_to_json)
```

**Comment by martinRenou** [comment]
Would you like to open a Pull Request fixing them?

**Comment by xoolive** [comment]
Sure I can fix these (tonight or tomorrow), but then I am not sure about the traittypes one...
