### ISSUE TITLE
Any plans to add tooltips or on_click events for layers?

### ISSUE THREAD

**Issue by dprophet** [jupyter-widgets/ipyleaflet#415]
@SylvainCorlay 

Sylvain! Old friend! How is it going?

Any plans on adding tooltips or on_click events to Polylines, Polygons, etc?

I see that Leaflet supports HTML() on pretty much any map layer.

Why I am asking, is I used Jupyter and hooked it directly to the Bloomberg Data API. Have a lot of data on the ipyleaflet map but its all just lines without a good tooltip on-click or on-hover.

Erik

**Comment by dprophet** [comment]
I see that there is an on_click

line = ipy.Polyline(
                        locations=locations,
                        color=color,
                        id=prev_imo,
                        fill=False)
line.on_click(self.click_handler)

def click_handler(self, **kwargs):

I could use this as a way to create my own tooltips. However the only kwargs coming in are
key=event, val=interaction
key=type, val=click
key=coordinates, val=[71.20958974114295, 29.05178514864729]

I have a lot of polylines so I need an ID of the item that I clicked on.

**Comment by martinRenou** [comment]
If you want to create your own tooltips using an HTML widget, the easiest way is to set the `popup` attribute of your `line` variable this way:

```python
line = ipyleaflet.Polyline([...])

line.popup = HTML('Hello World!!')
```

But it would show up on click only.

**Comment by ponaie** [comment]
I attach extra parameters to the callback function. 
```
line = ipyleaflet.Polyline(
                        locations=locations,
                        color=color,
                        id=prev_imo,
                        fill=False)
# add attribute to callback function
self.click_handler.id = id
line.on_click(self.click_handler)

def click_handler(self, **kwargs):
```
I hope it can help you.

**Comment by jakuboo** [comment]
If the on_click can return reference of the feature clicked on that would be awesome.
