### ISSUE TITLE
Fix up in documentation

### ISSUE THREAD

**Issue by bjornasm** [jupyter-widgets/ipyleaflet#426]
In the documentation for ipyleaflet, specifically when it comes to a circle marker - there is no mention what kind of reference system is used when placing the circle marker. Needless to say this is extremely frustrating. Is it lat long? Is it an x,y axis system in reference to the canvas?

**Comment by martinRenou** [comment]
It is lat long, as for all the locations parameters in ipyleaflet. PR welcome for improving the documentation!

**Comment by martinRenou** [comment]
Closing as all docstrings seem to specify the lat/long requirement
