### ISSUE TITLE
Allow nans in choropleth to be mapped to its own unique color and opacity

### ISSUE THREAD

**Issue by dwr-psandhu** [jupyter-widgets/ipyleaflet#428]
branca colormap doesn't deal with nans. A better option would be to allow nans to be mapped to their own unique color and opacity.
See here for [folium option](https://python-visualization.github.io/folium/modules.html#folium.features.Choropleth)

**Comment by martinRenou** [comment]
Thanks for filling this report :)

At some point, I wonder if we'll not drop the branca dependency though. And use bqplot's scales. But dealing with NaNs will still be relevant.

**Comment by martinRenou** [comment]
Should be fixed by https://github.com/jupyter-widgets/ipyleaflet/pull/972
