### ISSUE TITLE
DrawControl: keeping track of edited geometries

### ISSUE THREAD

**Issue by SimSmith** [jupyter-widgets/ipyleaflet#445]
I want to keep track of all currently drawn geometries. This can almost be done with on_draw. The problem is when a geometry is edited, there is no way of knowing which geometry was changed.

Example code where `action == 'edited'` does not know how to edit `positions`:
```python
from ipyleaflet import Map, DrawControl

open_map = Map(center=(-2.49921, 121.38695))
draw_control = DrawControl()

positions = []

def handle_draw(self, action, geo_json):
    coor = geo_json['geometry']['coordinates']
    if action == 'deleted':
        positions.remove(coor)
    elif action == 'created':
        positions.append(coor)
    elif action == 'edited':
        pass  # ?

draw_control.on_draw(handle_draw)
open_map.add_control(draw_control)

open_map
```

Am I missing something here or is this currently a limitation of DrawControl?

**Comment by giswqs** [comment]
See https://github.com/jupyter-widgets/ipyleaflet/issues/849#issuecomment-1025069614
