### ISSUE TITLE
Unreasonable requirement of 'id' property in GeoJSON for choropleth

### ISSUE THREAD

**Issue by andrhua** [jupyter-widgets/ipyleaflet#446]
Currently ipyleaflet obligates a geojson passed to `Choropleth` constructor to have 'id' property on each `feature` as mentioned in #361:
```
 {"type": "FeatureCollection",
"features":[ {"type":"Feature",
"id":"AL",
"properties":{"name":"Alabama"},
"geometry":{"type":"Polygon",
"coordinates": [[[-87.359296,35.00118]]]
```
I find this at least obscure, since now I have to waste my time assigning these ids when they are already present in `feature`, just going by the other name in its properties! Why can't we just use name provided by user himself as `id`?

**Comment by martinRenou** [comment]
Hello @andrhua and thanks for opening an issue. Would you like to open a PR for fixing this? The `id` key is used here: https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L578.

Adding a customizable `name` trait is indeed a good idea.

**Comment by andrhua** [comment]
Hey @martinRenou, I'm surely gonna take a look, just need some time to read code carefully.

**Comment by martinRenou** [comment]
I feel like we should follow what Folium does with the `key_on` parameter.

**Comment by martinRenou** [comment]
@omanges would you like to give this one a try? As it is pretty related to what you've done.

**Comment by omanges** [comment]
@martinRenou Yes, I can look into this. So here we need to first check whether the `name` is present and if not `id` is used. So either name or id is needed right?

**Comment by martinRenou** [comment]
I would say we stick to the Folium API. Adding a `key_on` Unicode attribute, which would be `"id"` by default. And then users can set it to whatever they want :)

**Comment by omanges** [comment]
Ohh cool :), you can assign this issue to me I can work on this.

**Comment by martinRenou** [comment]
Thanks very much for your work! It's really appreciated :)

**Comment by martinRenou** [comment]
Fixed by https://github.com/jupyter-widgets/ipyleaflet/pull/537
