### ISSUE TITLE
marker with auto_close option

### ISSUE THREAD

**Issue by PBrockmann** [jupyter-widgets/ipyleaflet#447]
How to have multiple popup for markers with an auto_close set option ?
I would like to have simultaneaous popup when user clicks on markers.

Size of the popup associated to a marker cannot be sized.

```python
from ipywidgets import HTML

from ipyleaflet import Map, Marker, Popup, CircleMarker

center = (52.204793, 360.121558)

m = Map(center=center, zoom=9, close_popup_on_click=False)

#=============================================
marker1 = Marker(location=(52.1, 359.9))
m.add_layer(marker1)

message1 = HTML()
message1.value = "Hello 1"

marker1.popup = message1

#=============================================
marker2 = Marker(location=(52.1, 360.9))
m.add_layer(marker2)

message2 = HTML()
message2.value = "Hello 2"

marker2.popup = message2

m
```

**Comment by PBrockmann** [comment]
Have found this hack http://bl.ocks.org/mpmckenna8/9395643
but from leaflet.js 

How to include this to ipyleaflet ?

**Comment by martinRenou** [comment]
So there is an `auto_close` option on the `Popup` class. Did you try using an intermediate `Popup` instance?
Something like:
```python
marker2 = Marker(location=(52.1, 360.9))
m.add_layer(marker2)

message2 = HTML()
message2.value = "Hello 2"

marker2.popup = Popup(child=message2, auto_close=True)
```
I suspect this would not work, I think I see a bug in the implementation. But it's worth giving it a try :)

**Comment by PBrockmann** [comment]
Indeed. Not working.

**Comment by martinRenou** [comment]
We should add support for assigning a `Popup` instance to the `Layer`'s `popup` trait

**Comment by PBrockmann** [comment]
It would be nice indeed.
An example on how to control the width of the popup would be usefulll as well
