### ISSUE TITLE
Splitmap Control in context of image processing

### ISSUE THREAD

**Issue by kolibril13** [jupyter-widgets/ipyleaflet#453]
Hi, 
I am really amazed by the [SplitMap Control function](https://ipyleaflet.readthedocs.io/en/latest/api_reference/split_map_control.html)  from the ipyleaflet package.

I think that would have also great use in other situations, for example in image processing to have a fast option to see the "previous/after" change.
To get concrete, it could look like this:
```py
from skimage import data
from skimage.util import random_noise
import matplotlib.pyplot as plt
import numpy as np

img = data.chelsea()
noisy_img = random_noise(img, var=0.02)

fig1= plt.figure()
plt.imshow(img)
plt.axis('off')
fig2= plt.figure()
plt.imshow(noisy_img)
plt.axis('off')

#new part (does not exist yet):
from ipywidgets import SplitMapControl
control = SplitMapControl(left_layer=fig1, right_layer=fig2)
m.add_control(control)
m
```

![neue](https://user-images.githubusercontent.com/44469195/71660160-73b08700-2d4a-11ea-9838-7dedb2a40f1f.png)

I ask people from matplotlib https://github.com/matplotlib/matplotlib/issues/16064 , and they think this feature could be  "a reasonable downstream package rather than a base feature".
My idea where this feature could fit in would be [ipywidgets](https://github.com/jupyter-widgets/ipywidgets).

**Comment by martinRenou** [comment]
Indeed that could be a good idea for a custom interactive widget :) I wonder if you could (and if it would be a good idea because the code is not super clean IMO) reuse some code from the SlipMap implementation https://github.com/QuantStack/leaflet-splitmap.

Another idea would be to use your cat images as `TileLayer`s in ipyleaflet. Allowing to compare your two images. I know it is possible in LeafletJs to create a `TileLayer` from non-geographical data (see https://leafletjs.com/examples/crs-simple/crs-simple.html). I wonder if it's possible in ipyleaflet though.

**Comment by martinRenou** [comment]
I guess it is possible in ipyleaflet, we have the `crs.Simple` option and you can use `ImageOverlay`s on each side of the `SplitMap` ;)

**Comment by martinRenou** [comment]
BTW that would be a great addition to the examples on the ipyleaflet repo, so if you come up with a Notebook, that would be awesome to contribute to the examples gallery :)

**Comment by kolibril13** [comment]
Thanks for your reply!
I found the `ImageOverlay` option, and my result looks now like this:
```py
from ipyleaflet import Map,  ImageOverlay, SplitMapControl
url="https://raw.githubusercontent.com/kolibril13/tricks_for_python/master/image_processing/testimages/"
img_name1= "milkeyway601x601.png"
img_name2= "woman2222x2222.jpg"

my_map = Map(center=(25, -115), zoom=4, crs="Simple", dragging=False,zoom_control=False)
img1 = ImageOverlay(
    url=url+img_name1,
    bounds=((13, -130), (32, -100)))

img2 = ImageOverlay(
    url=url+img_name2,
    bounds=((13, -130), (32, -100)))

#from ipywidgets import 
control = SplitMapControl(left_layer=img1, right_layer=img2)
my_map.add_control(control)
my_map
```
and my output looks like this:
![bla](https://user-images.githubusercontent.com/44469195/71852141-51b35d80-30d8-11ea-9d13-8308ccefccaf.png)
It works fine for the right, but the left image is not shown. :thinking: 
Also, there are some points where I don't know how to approach this problem:
* In this example, I have png images, but in the cat example I have the DataType `matplotlib.image.AxesImage`
* Also with crs="Simple", there is still the map somewhere in the background, and the lable at the left bottom, it feels like a very unclean solution.

I am quit experienced in python programming. 
In your [leflet-splitmap example](https://github.com/QuantStack/leaflet-splitmap), it looks like I need javascript to program this jupyter widget, which I never used before.
![aa](https://user-images.githubusercontent.com/44469195/71852683-9c81a500-30d9-11ea-8f08-be9533dd0877.png)
But I am curious about trying new things, therefore two questions:
* What is a good resource to get started to learn things to implement this slider widget for this `matplotlib` widgets?
* Is this something, one could probably do in one weekend?

**Comment by martinRenou** [comment]
In order to get rid of the underlying map you need to remove the `TileLayer` that is added by default by setting the `layers` attribute to an empty list:
```Python
my_map = Map(layers=[], center=(25, -115), zoom=4, crs="Simple", dragging=False, zoom_control=False)
```

> What is a good resource to get started to learn things to implement this slider widget for matplotlib widgets? Is this something, one could probably do in one weekend?

I don't know, I am not a matplotlib developer myself. Maybe ask this question on the matplotlib repo/gitter discussion if there is one.

I suspect it would be Python only if you make it a matplotlib "plugin"

**Comment by martinRenou** [comment]
> It works fine for the right, but the left image is not shown.

This looks like a bug to me...
