### ISSUE TITLE
ipywidgets 8.0 breaks ipyleaflet

### ISSUE THREAD

**Issue by mwcraig** [jupyter-widgets/ipyleaflet#457]
The `on_displayed` method has been removed from ipywidgets (https://github.com/jupyter-widgets/ipywidgets/pull/2021), which breaks the `Map` class in ipyleaflet.

**Comment by jasongrout** [comment]
Thanks for pointing this out. I was looking for places where it might have been used.

It's used here:

https://github.com/jupyter-widgets/ipyleaflet/blob/4557bda4843f77a94653e0f43b2961c1d9d1c93b/ipyleaflet/leaflet.py#L922

**Comment by jasongrout** [comment]
CC @martinRenou - I think this call isn't needed? I don't think any children actually use this?

**Comment by martinRenou** [comment]
Indeed, it looks like old code that is never used.

**Comment by martinRenou** [comment]
Thanks a lot for opening the issue Matt!

**Comment by SylvainCorlay** [comment]
Thanks!
