### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipyleaflet#463]
We should got through the documentation and see what is missing.

On top of my head:
- AntPath layer
- ZoomControl
- AwesomeIcon
- loading attribute for TileLayer

We might want to automatically generate the docs at some point

**Comment by fitoprincipe** [comment]
If you want, I can try to update docs for *loading attribute for TileLayer* and upload an example

**Comment by martinRenou** [comment]
That would be great!
