### ISSUE TITLE
HTML embed loses theme data

### ISSUE THREAD

**Issue by ian-r-rose** [jupyter-widgets/ipyleaflet#468]
I'm not sure what the intended behavior of the JupyterLab theming is on HTML export of ipyleaflet maps is, but when I tried it today, I found that popups lose some of their CSS and can become illegible.

Here is a minimal example:
```python
import ipyleaflet
import ipywidgets
import ipywidgets.embed

m = ipyleaflet.Map()
marker = ipyleaflet.Marker()
marker.popup = ipywidgets.HTML(value="Hello, World")
m.add_layer(marker)
display(m)
ipywidgets.embed.embed_minimal_html('embed.html', views=[m])
```
![image](https://user-images.githubusercontent.com/5728311/72193790-e01d2d00-33bf-11ea-9bf4-1142670b15ae.png)

Is there a way to also bundle appropriate values for the JupyterLab theme variables with the export?

**Comment by martinRenou** [comment]
Which versions of ipyleaflet and ipywidgets do you have? Latest versions should work I think..

**Comment by martinRenou** [comment]
You especially need to be sure to update the html-manager (which comes with ipywidgets), see https://github.com/jupyter-widgets/ipyleaflet/pull/466 for a fix I did a few days ago on the ipyleaflet documentation for the exact same issue.

**Comment by ian-r-rose** [comment]
The above was generated with `0.11.6`. I will try with `0.11.7` to see if that fixes it. Thanks @martinRenou!

**Comment by martinRenou** [comment]
It should work with 0.11.6 too...

**Comment by ian-r-rose** [comment]
Hmm, in that case the above code snippet reproduces the issue for me. Based on poking around the HTML export with the inspector, the theme CSS variables aren't making it on the page.

**Comment by martinRenou** [comment]
Which version of ipywidgets do you have?

**Comment by ian-r-rose** [comment]
I have `7.5.0`.

**Comment by ian-r-rose** [comment]
It seems like upgrading to ipywidgets `7.5.1` fixes the issue. Thanks @martinRenou!

**Comment by martinRenou** [comment]
Sure! 😊
