### ISSUE TITLE
`ViirsTrueColorCR` results in black (empty tiles) in the basemap gallery

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipyleaflet#490]
There might be an issue with the URL.

**Comment by martinRenou** [comment]
It was working on Monday. So maybe we can just wait a bit until it works again.

We actually receive tiles from the server, but they are entirely black (no 404 error).

**Comment by martinRenou** [comment]
I actually see it working again, maybe there was a temporary issue on the server.
