### ISSUE TITLE
How can I stop the map from grouping close markers into one?

### ISSUE THREAD

**Issue by danielp3011** [jupyter-widgets/ipyleaflet#498]
Hi there,

I have a map with around 100 marks. Right now, the library groups close marks and just says the number of marks which were grouped to one mark.
How can I stop that from happening?

I could not find it in the documentation.

Thanks a lot!

Best regards,
Daniel

**Comment by martinRenou** [comment]
Hi! I suppose you are using a `MarkerCluster` if they are grouping? If you don't want this behavior simply don't use this class.

So this code:
```python
from ipyleaflet import Map, Marker, MarkerCluster

m = Map(center=(50, 0), zoom=5)

marker1 = Marker(location=(48, -2))
marker2 = Marker(location=(50, 0))
marker3 = Marker(location=(52, 2))

marker_cluster = MarkerCluster(
    markers=(marker1, marker2, marker3)
)

m.add_layer(marker_cluster);

m
```

becomes:
```python
from ipyleaflet import Map, Marker

m = Map(center=(50, 0), zoom=5)

marker1 = Marker(location=(48, -2))
marker2 = Marker(location=(50, 0))
marker3 = Marker(location=(52, 2))

m.add_layer(marker1)
m.add_layer(marker2)
m.add_layer(marker3)

m
```

**Comment by danielp3011** [comment]
super, vielen dank :)
