### ISSUE TITLE
caption

### ISSUE THREAD

**Issue by quertenmont** [jupyter-widgets/ipyleaflet#50]
Is it possible to add a caption or a legend to the map
(for instance to indicate marker meaning)

Thanks,
Loic

**Comment by Fubukimaru** [comment]
The issue is a bit old, but I believe that this should be addressed as it is relevant to know what do the colors in the map represent.

**Comment by dwr-psandhu** [comment]
I was able to add the color legend using the WidgetControl with OutputWidget and embedding the display of the colormap into it.
```javascript
legend=linear.RdBu_11.scale(0,10)
layer.colormap=legend
out = widgets.Output(layout={'border': '1px solid black'})
with out:
    display(legend)
widget_control = ipyleaflet.WidgetControl(widget=out, position='topright')
m.add_control(widget_control)
display(m)
```

**Comment by amarandon** [comment]
FWIW a new extension has just been released for this: https://pypi.org/project/ipyleaflet-legend/

**Comment by martinRenou** [comment]
The ipyleaflet-legend plugin has been included in core ipyleaflet, and it is indeed possible to add your own legend or colormap inside of a WidgetControl now.
