### ISSUE TITLE
Version of jupyter-manager in postBuild causes Binder build error

### ISSUE THREAD

**Issue by banjaxedben** [jupyter-widgets/ipyleaflet#501]
In my own Jupyter notebook project, I copied "postBuild" and "environment.yml" from https://github.com/jupyter-widgets/ipyleaflet/ in order to support remote execution on Binder.
The Binder Build Log shows:
> ValueError:
> "@jupyter-widgets/jupyterlab-manager@0.38.1" is not compatible with the current JupyterLab
> Conflicting Dependencies:
> JupyterLab              Extension      Package
> >=1.2.1 <1.3.0          >=0.19.1 <0.20.0@jupyterlab/application
> >=3.2.0 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/coreutils
> >=1.2.2 <1.3.0          >=0.19.1 <0.20.0@jupyterlab/notebook
> >=1.2.1 <1.3.0          >=0.19.1 <0.20.0@jupyterlab/rendermime
> >=4.2.0 <4.3.0          >=3.0.0 <4.0.0 @jupyterlab/services
> See the log file for details:  /tmp/jupyterlab-debug-scikqqjo.log

**Comment by martinRenou** [comment]
I see this `0.38.1` requirement comes from #328. What happens if you remove `@0.38.1` from the postBuild file?

**Comment by banjaxedben** [comment]
Yes, when I remove the "@0.38" the Binder build log is clean - at least, there are no errors from the `RUN ./postBuild` step.

However, the next step (`Building jupyterlab assets (build:prod:minimize)`) never returned.
That may be completely unrelated of course, because I have seen Binder do this before.
And the build did work. On a refresh, I got "Found built image" and everything seems fine.

**Comment by martinRenou** [comment]
Yes, it also happened to me that it stopped sending logs while it actually finished building it!

I guess it is safe to close this issue now, but feel free to ask more questions! Thanks a lot for your feedback :)
