### ISSUE TITLE
Edit external GeoJSON data using DrawControl 

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#508]
It would be great to be able to use a DrawControl not only for drawing new shapes, but also for loading and editing existing ones in order to save them as well. I've done some experiments along these lines, but it seems like the existing DrawControl is too limited to allow for this. Here some sample snippets (with no effect):

```python
import requests
from ipyleaflet import Map, DrawControl

m = Map(center=[41.0462, 20.1388], zoom=6)
dc = DrawControl()
m += dc
display(m)
url = 'https://github.com/jupyter-widgets/ipyleaflet/raw/master/examples/europe_110.geo.json'
albania_feature = requests.get(url).json()["features"][0]
dc.last_draw = albania_feature  # has no effect
```

```python
import requests
from ipyleaflet import Map, DrawControl, GeoJSON

m = Map(center=[41.0462, 20.1388], zoom=6)
dc = DrawControl()
m += dc
url = 'https://github.com/jupyter-widgets/ipyleaflet/raw/master/examples/europe_110.geo.json'
albania_feature = requests.get(url).json()["features"][0]
m += GeoJSON(data=albania_feature)  # shows Albania as expected
display(m)
```

I could also not find any handle in the DrawControl instance to any “drawn” shape other than the last one. So it could well be that the wrapped Leaflet DrawControl is lacking this feature. This could also be related to #358.

**Comment by exospatial** [comment]
It used to be possible using the layer attribute like this:
```
dc = DrawControl()
dc.layer = GeoJSON(data=albania_feature)
```
The reasons for the layer attribute being removed are listed in this issue #68
I did use the feature and would be happy to help implement a replacement but could do with some pointers from someone familiar with the internals of the ipyleaflet

**Comment by dbergh** [comment]
I added PR #826 addressing this issue.

**Comment by giswqs** [comment]
I have implemented this in [leafmap](https://github.com/giswqs/leafmap/). You can now edit existing vector data interactively. 

https://user-images.githubusercontent.com/5016453/151687188-bdf136d0-d70f-4acb-86b6-cff580971d65.mp4
