### ISSUE TITLE
CircleMarker style not working?

### ISSUE THREAD

**Issue by lecardozo** [jupyter-widgets/ipyleaflet#51]
Apparently, none of the style parameters for **CircleMarker** shown in the [primitives example](https://github.com/ellisonbg/ipyleaflet/blob/master/examples/Primitives.ipynb) are working

When I run:
```python
    m = Map(center=[34.6252978589571, -77.34580993652344], zoom=10)
    mark = CircleMarker(location=m.center, radius=5, color="#000000", fill_color="#ff0000")
    m.add_layer(mark)
    m
```
the marker doesn't change the default radius, color and fill color.

These parameters do work when plotting **Circle** instead of **CircleMarker**, though.

Am I missing something?

**Comment by martinRenou** [comment]
This was fixed in a previous version of ipyleaflet, your code example works fine
