### ISSUE TITLE
Including the setUrl function to ImageOverlay

### ISSUE THREAD

**Issue by sdxlzxjh** [jupyter-widgets/ipyleaflet#514]
Hi, I'm trying to plot a sequence of images as a controlled animation. What I have tried is to link the "url" property of the ImageOVerlay instance to the "value" property of a play widget of ipywidgets. But this results in the flicker of the view like this:

![Peek 2020-03-11 12-05](https://user-images.githubusercontent.com/12840485/76410755-c2a11b00-6390-11ea-85e7-a8967a28c7dd.gif)

My guess of the reason behind is that every time the url is updated, a new "img" DOM is initialized instead of redrawing the old one. In this case, the [setUrl](https://leafletjs.com/reference-1.6.0.html#imageoverlay-seturl) function is more suitable. Is there any plan to include the setUrl function for ImageOverlay?

**Comment by davidbrochart** [comment]
It could be nice to have, I will look into that.
