### ISSUE TITLE
Layer not being displayed in Jupyter using Ipyleaflet but no error thrown

### ISSUE THREAD

**Issue by benratkin** [jupyter-widgets/ipyleaflet#520]
_First time ever posting an issue on Github so be gentle, pedants!_

I'm trying to create my own custom GeoDataFrame and then display it using Ipyleaflet in a Jupyter notebook. Unfortunately, the basemap displays but my layer isn't shown and there are no errors thrown to point out any issues.

Here's my code:
```python
# General python libraries
import json
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import pickle
import re

# Geo mapping libraries
import geopandas as gpd
from shapely.geometry import Point, Polygon
from ipyleaflet import Map, GeoData, basemaps, LayersControl, Choropleth
from ipyleaflet import WidgetControl, GeoJSON 
from ipywidgets import Text, HTML
import geopandas

# Create my own geodataframe using lats/longs to create the cells
def create_geobins(df_lat_ser, df_long_ser, n_lats, n_longs):
    polygons = []
    max_lat = df_lat_ser.max()
    min_lat = df_lat_ser.min()
    max_long = df_long_ser.max()
    min_long = df_long_ser.min()
    lat_step = abs((max_lat - min_lat)) / n_lats
    long_step = abs((max_long - min_long)) / n_longs
    for this_lat in np.arange(min_lat, max_lat, lat_step):
        for this_long in np.arange(min_long, max_long, long_step):
            polygons.append(Polygon([(this_lat, this_long),
                                     (this_lat + lat_step, this_long),
                                     (this_lat + lat_step, this_long + long_step),
                                     (this_lat, this_long + long_step),
                                     (this_lat, this_long)
                                     ]
                                    )
                            )
    return gpd.GeoDataFrame(polygons, columns=['geometry'])

# Create custom GeoDataFrame
geobins = create_geobins(map_df.lat, map_df.long, 10, 6)

# Create basemap, add layer
geobins_layer = GeoData(geo_dataframe=geobins, name='cells')
m = Map(center=(47.5391,-122.070), zoom=9)
m.add_layer(geobins_layer)
m.add_control(LayersControl())
m
```

The map with base layer is shown and I can even toggle the 'cells' layer on the control but no polygons are displayed.

For debugging:

--type(geobins_layer)
ipyleaflet.leaflet.GeoData

--geobins_layer.data:
{'type': 'FeatureCollection',
 'features': [{'id': '0',
   'type': 'Feature',
   'properties': {},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[47.1559, -122.512],
      [47.218070000000004, -122.512],
      [47.218070000000004, -122.3125],
      [47.1559, -122.3125],
      [47.1559, -122.512]]]}},
  {'id': '1',
   'type': 'Feature',
   'properties': {},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[47.1559, -122.3125],
      [47.218070000000004, -122.3125],
      [47.218070000000004, -122.113],
      [47.1559, -122.113],
      [47.1559, -122.3125]]]}},
  {'id': '2', ...

--conda list
...
ipyleaflet                0.12.3                     py_1    conda-forge
...

**Comment by martinRenou** [comment]
> First time ever posting an issue on Github so be gentle, pedants!

:smile: 

Just so you know, you can enable code highlighting in a code block specifying the language: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting 

Do you have a small dataframe that I can use so I can reproduce your issue? For `map_df`

**Comment by martinRenou** [comment]
Oh and do you have a JavaScript error in the console? `ctrl shift J` on Chrome/Chromium or `ctrl shift K` on Firefox to see the JavaScript console

**Comment by benratkin** [comment]
The full dataset as well as a Jupyter notebook that isolates the issue titled "ipyleaflet_issue.ipynb" is available at https://github.com/benratkin/module_2_project.

Here's a screenshot of the javascript console. The screenshot includes all output after running every code cell in ipyleaflet_issue.ipynb.

![Screenshot_20200318_112334](https://user-images.githubusercontent.com/59036096/76994291-621f5a00-690b-11ea-8759-6830ad414259.png)

**Comment by martinRenou** [comment]
I'll try to have a look.

In the meantime, did you try switching latitude and longitude when creating your Polygon? It might be that your dataset uses longitude/latitude and not latitude/longitude

**Comment by benratkin** [comment]
I'm pretty sure I didn't mix them up but here's a printout of the first polygon and the plotted grid with Lat/Long ticks on axes. The grid is supposed to be approximately centered over Seattle washington area (47.5391,-122.070).

![Screenshot_20200319_095254](https://user-images.githubusercontent.com/59036096/77092849-6b6dfc80-69c7-11ea-896c-72d1cd429e80.png)

**Comment by martinRenou** [comment]
Could you show me the result of `print(geobins_layer.data)`?

**Comment by benratkin** [comment]
You were correct. Shapely Polygons are in order (x, y) meaning (Long, Lat) rather than (Lat, Long). Thank you very much for the quick attention though! Excited to use Ipyleaflet more! I'll post the final fixed result.

```python
# Create my own geodataframe using lats/longs to create the cells, need id
def create_geobins(df_lat_ser, df_long_ser, n_lats, n_longs):
    polygons = []
    max_lat = df_lat_ser.max()
    min_lat = df_lat_ser.min()
    max_long = df_long_ser.max()
    min_long = df_long_ser.min()
    lat_step = abs((max_lat - min_lat)) / n_lats
    long_step = abs((max_long - min_long)) / n_longs
    for this_lat in np.arange(min_lat, max_lat, lat_step):
        for this_long in np.arange(min_long, max_long, long_step):
            polygons.append(Polygon([
                (this_long, this_lat),
                (this_long, this_lat + lat_step),
                (this_long + long_step, this_lat + lat_step),
                (this_long+long_step, this_lat),
                (this_long, this_lat)
            ]))

# Incorrect lat/long order for Shapely Polygon objects
#             polygons.append(Polygon([(this_lat, this_long),
#                                      (this_lat + lat_step, this_long),
#                                      (this_lat + lat_step, this_long + long_step),
#                                      (this_lat, this_long + long_step),
#                                      (this_lat, this_long)
#                                      ]
#                                     )
#                             )
    return gpd.GeoDataFrame(polygons, columns=['geometry'])
                            
geobins = create_geobins(map_df.lat, map_df.long, 10, 6)

# Create basemap, add choro_layer
m = Map(center=(47.5391,-122.070), zoom=9)
geobins_layer = GeoData(geo_dataframe=geobins,
                       style={'color': 'black'},
#                        hover_style={'fillColor': 'red' , 'fillOpacity': 0.2},
                       name = 'cells')
m.add_layer(geobins_layer)
m.add_control(LayersControl())
m
```

![Screenshot_20200319_100453](https://user-images.githubusercontent.com/59036096/77094018-18954480-69c9-11ea-8bcb-cd6c6e61c4fe.png)

**Comment by martinRenou** [comment]
> You were correct. Shapely Polygons are in order (x, y) meaning (Long, Lat) rather than (Lat, Long). Thank you very much for the quick attention though! Excited to use Ipyleaflet more!

Ahah great!
