### ISSUE TITLE
More generic styling for GeoJSON and GeoData?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#524]
It's great to have https://github.com/jupyter-widgets/ipyleaflet/pull/518 accepted for adding more generic styling to `Choropleth` objects! This kind of leads to the question if this could be generalized to `GeoJSON` and `GeoData` objects since they also use a `style` attribute. The callback computing the style could receive a feature or row attribute to compute the style from, respectively. This might reduce the value of the `Choropleth` class tremendously since it could perhaps be entirely replaced with the `GeoJSON` one. Any thoughts, @martinRenou @omanges?

**Comment by omanges** [comment]
Actually, in #518 the style_callback is added to the `GeoJSON` class so that the user will receive a feature object in the style callback.

**Comment by deeplook** [comment]
Ooups, my bad...
