### ISSUE TITLE
setUrl function in imageOverlay disables opacity

### ISSUE THREAD

**Issue by FionaLippert** [jupyter-widgets/ipyleaflet#526]
I've been experimenting with the Image_slider.ipynb example (#516) using the new setUrl function in imageOverlay. But I noticed that updating the url results in a fixed opacity of 1 in the output map. The attribute io.opacity still has the value with which the layer has been initialized, but it seems like it's not passed correctly to leaflet anymore as soon as setUrl has been used.

**Comment by martinRenou** [comment]
@davidbrochart maybe resetting the opacity (maybe all options?) after setting the URL would fix this issue?

It might be an issue with LeafletJS itself

**Comment by davidbrochart** [comment]
@FionaLippert the fix for `setUrl` has not been released yet.

**Comment by martinRenou** [comment]
Maybe it was using a development version from master?

**Comment by davidbrochart** [comment]
I tried it and it works fine.

**Comment by FionaLippert** [comment]
Yes I use the latest development version from master. I just double checked, it's the version including `this.obj.setUrl(url)` in ImageOverlay.js.

**Comment by davidbrochart** [comment]
Did you run `npm run build` in the `js` directory?

**Comment by FionaLippert** [comment]
yes I did

**Comment by martinRenou** [comment]
Could you provide a small snippet of code that reproduce the issue?

**Comment by FionaLippert** [comment]
```python
import numpy as np
from matplotlib import cm
from PIL import Image
from ipyleaflet import Map, ImageOverlay, WidgetControl
import os
from base64 import b64encode
from ipywidgets import SelectionSlider

# create random images and save them as png
t_range = range(10)
os.makedirs('./png', exist_ok=True)
for t in t_range:
    im = Image.fromarray(np.uint8(cm.rainbow(np.random.rand(100,100))*255))
    im.save(f'png/{t}.png','PNG')
    
# set up map with slider
center = [51.164878, 5.295410]
bounds=((center[0]-5, center[1]-5), \
        (center[0]+5, center[1]+5))
m = Map(center=center, zoom=5)
slider = SelectionSlider(description='time step:', 
                   options=t_range, 
                   orientation='horizontal')
widget_control = WidgetControl(widget=slider, position='topright')
m.add_control(widget_control)


# update functions
io = None
def update_png(t):
    global io
    
    filename=f'png/{t}.png'
    with open(filename, 'rb') as f:
        d = b64encode(f.read())
    d = d.decode('ascii')
    p = 'data:image/png;base64,' + d

    if io is None:
        io = ImageOverlay(url=p, bounds=bounds, opacity=0.3)
        m.add_layer(io)
    else:
        io.url = p
        
def show(change):
    update_png(change.new)

# show map
slider.observe(show, 'value')
update_png(0)
display(m)
```

this produces the following output for time step 0 with opacity 0.3:
![Screenshot from 2020-03-25 12-00-04](https://user-images.githubusercontent.com/35309385/77529914-cf456900-6e90-11ea-9a5b-b1c0f305e9d8.png)

and as soon as I move the slider the opacity is 1:
![Screenshot from 2020-03-25 12-00-10](https://user-images.githubusercontent.com/35309385/77529983-ebe1a100-6e90-11ea-8e3b-cfb2b543aa55.png)

**Comment by martinRenou** [comment]
Thanks a lot, I'll look into it

**Comment by martinRenou** [comment]
Using master. I don't see the issue you describe.
![io](https://user-images.githubusercontent.com/21197331/77530538-cacd8000-6e91-11ea-9f1b-9461de56786d.gif)

How did you install ipylealfet?
If you use the classic Jupyter Notebook please be sure you installed the nbextension with the `--symlink` option if you want to apply the changes when doing only `npm run build`
```
jupyter nbextension install --py --symlink --sys-prefix ipyleaflet
jupyter nbextension enable --py --sys-prefix ipyleaflet
```

Do you use JupyterLab? Please be sure to rebuild JupyterLab with your changes
```
jupyter labextension install js
```

**Comment by martinRenou** [comment]
If you did all this already but you still see the issue, could you check the JavaScript console?

**Comment by FionaLippert** [comment]
Ah I didn't rebuild JupyterLab. That fixed it, thank you!

**Comment by martinRenou** [comment]
Sure!
