### ISSUE TITLE
The self keyword issue of the handle_draw() function for the DrawControl

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#527]
I am trying to incorporate the following `handle_draw(self, action, geo_json)` function into the [Map](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L108) class in the [geemap](https://github.com/giswqs/geemap) Python package. The goal is to allow users to draw shapes and automatically convert shapes to Earth Engine Geometry objects and add them as a new layer to the LayerControl. In this way, users don't have to write the `handle_draw()` function themselves. However, the `handle_draw()` function has a `self`keyword, which conflicts with the `self` keyword of the [`__init__(self, **kwargs)`](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L117) function for the Map class. I can't access the Map class within the `handle_draw()` function as the `self` keyword is being overwritten. Any advice on how to resolve this issue will be greatly appreciated! 

 The following code snippet is from this [notebook](https://github.com/giswqs/geemap/blob/master/examples/notebooks/ipyleaflet_draw_control.ipynb).
```
dc = Map.draw_control
feat_list = []
# Handle draw events
def handle_draw(self, action, geo_json):

    geom = geojson_to_eegeometry(geo_json, False)
    feature = ee.Feature(geom)
    feat_list.append(feature)
    collection = ee.FeatureCollection(feat_list)  
    Map.layers = base_layers[:3]
    Map.addLayer(collection, {}, 'EE Geometry')

dc.on_draw(handle_draw)
```

**Comment by martinRenou** [comment]
I am not sure I understand your issue. Your `handle_draw` is a function, not a method. So having `self` as the first argument will not give you the map.

Your map being defined outside of your function you can still access it.

**Comment by martinRenou** [comment]
Oh, I think I understand now. What if you call it `target` instead of self?

```python
dc = Map.draw_control
feat_list = []
# Handle draw events
def handle_draw(target, action, geo_json):

    geom = geojson_to_eegeometry(geo_json, False)
    feature = ee.Feature(geom)
    feat_list.append(feature)
    collection = ee.FeatureCollection(feat_list)  
    target.layers = base_layers[:3]
    target.addLayer(collection, {}, 'EE Geometry')

dc.on_draw(handle_draw)
```

**Comment by giswqs** [comment]
@martinRenou Thanks for the suggestion. Problem solved. I thought the first argument of the `handle_draw` function had to be called `self`. I did not know that it can be named something else.

**Comment by martinRenou** [comment]
We should improve the documentation maybe.

The first argument (being a positional argument only) can be named whatever you want, but I guess naming it `self` is not recommended. The other two arguments must be named `action` and `geo_json` though, but those being used as keyword arguments you can switch their places, it will still work.

We should document what ipyleaflet requests as callback function signature.

**Comment by martinRenou** [comment]
I opened an issue for that #528

**Comment by giswqs** [comment]
@martinRenou Thanks for the clarification. I copyied that `handle_draw()` function from this ipyleaflet example ([DrawControl.ipynb](https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/DrawControl.ipynb)). I mistaken thought that the first argument has to named `self`. Good to know that it is just a positional argument and can be named sometime else.

**Comment by martinRenou** [comment]
Mmh, maybe we should update that example and rename the first argument. It feels weird to see `self`  as the first argument for a free function.
