### ISSUE TITLE
Feature request: provide access to Leaflet's `fitBounds`

### ISSUE THREAD

**Issue by metasim** [jupyter-widgets/ipyleaflet#529]
Computing the bounds and maximum zoom level to render all of a layer is a surprisingly complex task, and one that's already implemented in Leaflet:

https://leafletjs.com/reference-1.6.0.html#map-fitbounds

Please consider providing access to this method in the Python API.

**Comment by davidbrochart** [comment]
That would be possible if there was only one view of the Map, but what does this even mean when you have several views that may have a different size (in pixels)?

**Comment by metasim** [comment]
I probably don't understand the architecture enough to answer that; I didn't know a map could have multiple views. Do you mean?:

```python
m = Map(...)
m.add_layer(...)
display(m)
display(m)
```

If so, I suppose each view would pan/zoom such that the given geometry was fully in view in each case.

Here's what I'm having to do now, where `zoom_for_poly_wgs84` does [some magic derived from gdal](https://github.com/OSGeo/gdal/blob/b0dfc591929ebdbccd8a0557510c5efdb893b852/gdal/swig/python/scripts/gdal2tiles.py).

```python
geo_df: GeoDataFrame = ...
# Compute zoom and center of results coverage
union = geo_df.unary_union
centroid = union.centroid
zoom = zoom_for_poly_wgs84(union)
map = Map(
       center=(centroid.y, centroid.x),
       zoom=zoom,
       basemap=basemaps.CartoDB.Positron,
)

```

What I'd rather do is:

```python
geo_df: GeoDataFrame = ...
union = geo_df.unary_union
map = Map(
    fit=union,
    basemap=basemaps.CartoDB.Positron,
)
map.add_layer(GeoData(geo_dataframe=geo_df))
```

Or more perhaps more imperitively:

```python
geo_df: GeoDataFrame = ...
union = geo_df.unary_union
map = Map(
    basemap=basemaps.CartoDB.Positron,
)
gd = GeoData(geo_dataframe=geo_df)
map.add_layer(gd)
map.fit_bounds(gd)
```

**Comment by luiztauffer** [comment]
Would access to the method grant control over spanning and zooming out of the boundaries of the map? I'm finding it difficult to do it with the currently available options

**Comment by davidbrochart** [comment]
The problem is rather that the function can't be applied to all views of the map if they have different sizes.

**Comment by luiztauffer** [comment]
Is the number of views stored in any internal variable? Would it be possible to unable fitBounds if n_views > 1 ?

**Comment by davidbrochart** [comment]
We evaluated this possibility, but decided to not go that path, sorry.

**Comment by luiztauffer** [comment]
@davidbrochart that's ok, thank you for the reply!
would you suggest any workaround to fix the map within maximum boundaries? I would like to avoid the escaping to outside the map (in latitude) and scrolling through map repetitions laterally (in longitude).

**Comment by davidbrochart** [comment]
I guess you could iteratively adjust the zoom level according to the `Map.bounds`, but even that doesn't make much sense. You can try it in Jupyter Lab: create a map, print its bounds, right-click on the map `Create New View for Output`, print the bounds again, and you will see it has changed.

**Comment by metasim** [comment]
> The problem is rather that the function can't be applied to all views of the map if they have different sizes.

Sorry to be naive, but I'm not sure I understand why this is... (something to do with the semantics of additional views?). If you called Leaflet's `fitToBounds` sequentially on each view, using the same parameters, why would that not fulfill the feature?

**Comment by martinRenou** [comment]
Because then each view will have a different zoom level and position, which we want to synchronize between views.
