### ISSUE TITLE
Options for Widget Control position

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#531]
Based on the [Widget Control documentation](https://ipyleaflet.readthedocs.io/en/latest/api_reference/widget_control.html), it seems the position can only be `bottomleft`, `bottomright`, `topleft`, or `topright`. Is it possible to add more options, such as `topcenter`, `bottomcenter`, or relative positon (e.g., %width, %height of the map) ? Thanks.

**Comment by martinRenou** [comment]
Those possible values are coming from LeafletJS https://leafletjs.com/reference-1.6.0.html#control-position. It might be possible to provide other options using some CSS.

**Comment by giswqs** [comment]
@martinRenou Thanks for the info. I have submit a [feature request](https://github.com/Leaflet/Leaflet/issues/7048) on LeafletJS directly.

**Comment by giswqs** [comment]
@martinRenou It turns out that `topcenter` and `bottomcenter` positions have been proposed before, but the [pull request](https://github.com/Leaflet/Leaflet/pull/6935) has not been merged into the master repo yet. I will wait and see.
