### ISSUE TITLE
Search Control

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipyleaflet#534]
We should add support for the [search control](https://github.com/stefanocudini/leaflet-search) in ipyleaflet.

This is use in a couple of applications like this map here, on the natural radioactivity in France https://cartoradon.irsn.fr/static/

**Comment by SylvainCorlay** [comment]
```
  var search_url = '/commune.py/communes/search/'+region+'/{s}?';
	var searchControl = new L.Control.Search({
			url: search_url,
			jsonpParam: 'json_callback',
			propertyName: 'display_name',
			propertyLoc: ['lat','lon'],
			//markerLocation: true,
			autoType: false,
			autoCollapse: false,
			minLength: 1,
         zoom:10,
         animateLocation:false,
         position:'topright'
      });
   map.addControl(searchControl);
   searchControl.expand();

   function onMapClick(e) {
      search_by_click(e.latlng);
   }
   map.on('click', onMapClick);
```

**Comment by giswqs** [comment]
This would be a very nice addition. The Search Control can search both place names and maker properties. [Here](https://labs.easyblog.it/maps/leaflet-search/examples/geocoding-nominatim.html) is another example using the Search Control.

**Comment by SylvainCorlay** [comment]
@giswqs do you want to take a stab at it?

**Comment by giswqs** [comment]
@SylvainCorlay I am not good at JavaScript, and I am still learning the ipyleaflet source code. It might take some time before I can contribute to the source code at this level. Could you elaborate a little bit more about the general workflow for adding a new control to ipyleaflet?

Using the `ZoomControl` as an example, it seems these are the steps: 

1. Add a `SearchControl.js` to [ipyleaflet/js/src/controls/](https://github.com/jupyter-widgets/ipyleaflet/tree/master/js/src/controls)
2. Modify [jupyter-leaflet.js](https://github.com/jupyter-widgets/ipyleaflet/blob/master/js/src/jupyter-leaflet.js) to include the SearchControl.
3. Modify [leaflet.py](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py) to include the SearchControl
4. Add a notebook example to the [examples](https://github.com/jupyter-widgets/ipyleaflet/tree/master/examples) folder. 

But I don't know how to incorporate the Search Control source code from [[leaflet-search/src/](https://github.com/stefanocudini/leaflet-search/tree/master/src)] into ipyleaflet.

**Comment by SylvainCorlay** [comment]
You pretty much got it already. Since there is a lot of patterns that you can get from other controls it may be a good way to get into it.

You will need to update the package.json file to add the dependency.

I recommend looking at some of the general material that exist to get some context on jupyter widgets and how they work.

**Comment by deeplook** [comment]
There's some prior work of mine here, but without any JS component: https://github.com/deeplook/ipymaps/

**Comment by sackh** [comment]
@SylvainCorlay - I would like to work on this, will you please assign this to me.

**Comment by giswqs** [comment]
I have implemented a search control in the [geemap](https://github.com/giswqs/geemap) package. Here is the [source code](https://github.com/giswqs/geemap/commit/73ffca710f933eaeddf9d91dd0be3379a4461083) I just committed.

![](https://i.imgur.com/UBYcN47.gif)

**Comment by martinRenou** [comment]
That looks super good

**Comment by martinRenou** [comment]
Let's close this, thanks @sackh !
