### ISSUE TITLE
Add support for popups

### ISSUE THREAD

**Issue by bensteers** [jupyter-widgets/ipyleaflet#54]
Additionally, I would like to be able to bind them to GeoJSON features where the data could be pulled via feature properties. This can be done through the Javascript interface using:

```javascript
var myLayer = L.geoJson(geojsonMD, {
     style: function (feature) {
         return feature.properties.style;
     },
     onEachFeature: function (feature, layer) {
         layer.bindPopup(feature.properties.name);
     }
 }
```

It would be nice if the 'style', 'onEachFeature', and 'filter' callbacks were implemented as well, but I understand if this is difficult to do over comm messages. I've tried to do it myself, but I haven't had any luck due to my poor knowledge of how ipywidgets work.

**Comment by sherl0cks** [comment]
If anyone else stumbles on this, be advised that [folium](https://github.com/python-visualization/folium) provides this feature, as seen [here](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb)

**Comment by SylvainCorlay** [comment]
This is now supported by ipyleaflet!

**Comment by samsammurphy** [comment]
Is there a working example in python somewhere??
