### ISSUE TITLE
basemaps.OpenStreetMap.BlackAndWhite completely grey

### ISSUE THREAD

**Issue by DummerJunge** [jupyter-widgets/ipyleaflet#540]
Hello, this basemap is  compleetely grey on https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html for me, thank you.

**Comment by DummerJunge** [comment]
Sorry, loading took more than five minutes, I was to impatient, sorry.

**Comment by martinRenou** [comment]
No worries, I would have been impatient too after 5 minutes waiting :P
