### ISSUE TITLE
basemaps.HikeBike.HikeBike completely grey

### ISSUE THREAD

**Issue by DummerJunge** [jupyter-widgets/ipyleaflet#541]
Hello, this basemap is  compleetely grey on https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html for me, thank you.

**Comment by VasavanThiru** [comment]
Hi DJ, I'm using Firefox and it works well .. 
Maybe it takes some time to load the page ..

**Comment by DummerJunge** [comment]
Thank you, loading took more than five minutes, I was to impatient, sorry.
