### ISSUE TITLE
"Error displaying widget: model not found" in Mundi Jupyter Notebook

### ISSUE THREAD

**Issue by unfassbarstephan** [jupyter-widgets/ipyleaflet#547]
I use Jupyter Notebook with ipyleaflet via Mundi Web Services (https://mundiwebservices.com/marketplace). Unfortunately the message 'Error displaying widget: model not found' appears and the widgets are not executed.

For example, this code is executed without problems.
`from ipywidgets import Button`
`Button()`

The following code sample causes the mentioned error.
`from ipyleaflet import *`
`m = Map(center=(52, 10), zoom=8, basemap=basemaps.Hydda.Full)`
`m`

After a request to the Mundi Helpdesk I should report this problem here and open an issue, because a browser conflict is suspected. However, the error occurs in different browser software (e.g. Edge, Firefox, Chrome).

This error message is shown in the chrome console:
```
manager-base.js:273 Could not instantiate widget
utils.js:119 Error: Could not create a model.
    at n (utils.js:119)
    at async _handleCommOpen (manager.js:61)
    at async v._handleCommOpen (default.js:994)
    at async v._handleMessage (default.js:1100)
default.js:1001 Exception opening new comm
default.js:127 Error: Module jupyter-leaflet, semver range ^0.12.3 is not registered as a widget module
    at k.loadClass (manager.js:305)
    at k.<anonymous> (manager-base.js:263)
    at l (manager-base.js:44)
    at Object.next (manager-base.js:25)
    at manager-base.js:19
    at new Promise (<anonymous>)
    at Rtm6.L (manager-base.js:15)
    at k.e._make_model (manager-base.js:257)
    at k.<anonymous> (manager-base.js:246)
    at l (manager-base.js:44)
```

The following versions are installed:
```
{{jovyan@jupyter-:~$ jupyter --version
jupyter core : 4.6.2
jupyter-notebook : 6.0.3
qtconsole : 4.6.0
ipython : 7.12.0
ipykernel : 5.1.4
jupyter client : 5.3.4
jupyter lab : 1.2.5
nbconvert : 5.6.1
ipywidgets : 7.5.1
nbformat : 5.0.4
traitlets : 4.3.3}}
```

**Comment by martinRenou** [comment]
Can you show me the output of:
```
jupyter nbextension list
```

**Comment by jasongrout** [comment]
This error indicates that the appropriate javascript for the widget has not be installed in the browser. What does `jupyter labextension list` give? Is the ipyleaflet jlab extension installed? See https://github.com/jupyter-widgets/ipyleaflet#installation

**Comment by jasongrout** [comment]
Is this in Jupyter Notebook or JupyterLab?

**Comment by unfassbarstephan** [comment]
> Can you show me the output of:
> 
> ```
> jupyter nbextension list
> ```

This is the output:
```
$ jupyter nbextension list
Known nbextensions:
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      bqplot/extension  enabled 
      - Validating: OK
      jupyter-leaflet/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by unfassbarstephan** [comment]
> jupyter labextension list

$ jupyter labextension list
JupyterLab v1.2.5
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK

**Comment by jasongrout** [comment]
Yes, it looks like the ipyleaflet JupyterLab extension has not been installed. Please follow the ipyleaflet installation instructions at https://github.com/jupyter-widgets/ipyleaflet#installation, including installing the jupyterlab extension.

**Comment by unfassbarstephan** [comment]
You were right, I had forgotten to install the jupyterlab extension.

Now `$ jupyter labextension list` gives:
```
JupyterLab v1.2.5
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyter-leaflet v0.12.3  enabled  OK
```

Now it works, what a stupid mistake of mine.

Thanks for the help!

**Comment by jasongrout** [comment]
Great!
