### ISSUE TITLE
Key error on Jupyter Notebook 

### ISSUE THREAD

**Issue by subhadipghorui** [jupyter-widgets/ipyleaflet#557]
Key error on Jupyter Notebook 
<img width="565" alt="qqqqq" src="https://user-images.githubusercontent.com/49529825/80128027-c2f91c80-85b2-11ea-88b1-f20d5bb5df3c.png">

**Comment by martinRenou** [comment]
Hum thanks for opening an issue but can you provide the code that you ran that got you into this error?

**Comment by subhadipghorui** [comment]
`from ipyleaflet import Map, Velocity, TileLayer, basemaps
import xarray as xr
import os

if not os.path.exists('wind-global.nc'):
  url = 'https://github.com/benbovy/xvelmap/raw/master/notebooks/wind-global.nc'
  import requests
  r = requests.get(url)
  wind_data = r.content
  with open('wind-global.nc', 'wb') as f:
      f.write(wind_data)

center = [0, 0]
zoom = 1
m = Map(center=center, zoom=zoom, interpolation='nearest', basemap=basemaps.CartoDB.DarkMatter)

ds = xr.open_dataset('wind-global.nc')
display_options = {
    'velocityType': 'Global Wind',
    'displayPosition': 'bottomleft',
    'displayEmptyString': 'No wind data'
}
wind = Velocity(data=ds,
                zonal_speed='u_wind',
                meridional_speed='v_wind',
                latitude_dimension='lat',
                longitude_dimension='lon',
                velocity_scale=0.01,
                max_velocity=20,
                display_options=display_options)
m.add_layer(wind)

m`

The whole error msg.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\file_manager.py in _acquire_with_cache_info(self, needs_lock)
    197             try:
--> 198                 file = self._cache[self._key]
    199             except KeyError:

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\lru_cache.py in __getitem__(self, key)
     52         with self._lock:
---> 53             value = self._cache[key]
     54             self._cache.move_to_end(key)

KeyError: [<function _open_scipy_netcdf at 0x000001C9020C3F28>, ('C:\\Users\\SUBHADIP\\Python JupyterNote Book\\wind-global.nc',), 'r', (('mmap', None), ('version', 2))]

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\scipy_.py in _open_scipy_netcdf(filename, mode, mmap, version)
     82     try:
---> 83         return scipy.io.netcdf_file(filename, mode=mode, mmap=mmap, version=version)
     84     except TypeError as e:  # netcdf3 message is obscure in this case

C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\netcdf.py in __init__(self, filename, mode, mmap, version, maskandscale)
    283         if mode in 'ra':
--> 284             self._read()
    285 

C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\netcdf.py in _read(self)
    608             raise TypeError("Error: %s is not a valid NetCDF 3 file" %
--> 609                             self.filename)
    610         self.__dict__['version_byte'] = frombuffer(self.fp.read(1), '>b')[0]

TypeError: Error: C:\Users\SUBHADIP\Python JupyterNote Book\wind-global.nc is not a valid NetCDF 3 file

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-7e64da0854b7> in <module>
     15 m = Map(center=center, zoom=zoom, interpolation='nearest', basemap=basemaps.CartoDB.DarkMatter)
     16 
---> 17 ds = xr.open_dataset('wind-global.nc')
     18 display_options = {
     19     'velocityType': 'Global Wind',

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\api.py in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, autoclose, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables, backend_kwargs, use_cftime)
    533 
    534     with close_on_error(store):
--> 535         ds = maybe_decode_store(store)
    536 
    537     # Ensure source filename always stored in dataset object (GH issue #2550)

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\api.py in maybe_decode_store(store, lock)
    448             decode_coords=decode_coords,
    449             drop_variables=drop_variables,
--> 450             use_cftime=use_cftime,
    451         )
    452 

C:\ProgramData\Anaconda3\lib\site-packages\xarray\conventions.py in decode_cf(obj, concat_characters, mask_and_scale, decode_times, decode_coords, drop_variables, use_cftime)
    568         encoding = obj.encoding
    569     elif isinstance(obj, AbstractDataStore):
--> 570         vars, attrs = obj.load()
    571         extra_coords = set()
    572         file_obj = obj

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\common.py in load(self)
    121         """
    122         variables = FrozenDict(
--> 123             (_decode_variable_name(k), v) for k, v in self.get_variables().items()
    124         )
    125         attributes = FrozenDict(self.get_attrs())

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\scipy_.py in get_variables(self)
    155     def get_variables(self):
    156         return FrozenDict(
--> 157             (k, self.open_store_variable(k, v)) for k, v in self.ds.variables.items()
    158         )
    159 

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\scipy_.py in ds(self)
    144     @property
    145     def ds(self):
--> 146         return self._manager.acquire()
    147 
    148     def open_store_variable(self, name, var):

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\file_manager.py in acquire(self, needs_lock)
    178         An open file object, as returned by ``opener(*args, **kwargs)``.
    179         """
--> 180         file, _ = self._acquire_with_cache_info(needs_lock)
    181         return file
    182 

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\file_manager.py in _acquire_with_cache_info(self, needs_lock)
    202                     kwargs = kwargs.copy()
    203                     kwargs["mode"] = self._mode
--> 204                 file = self._opener(*self._args, **kwargs)
    205                 if self._mode == "w":
    206                     # ensure file doesn't get overriden when opened again

C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\scipy_.py in _open_scipy_netcdf(filename, mode, mmap, version)
     92             """
     93             errmsg += msg
---> 94             raise TypeError(errmsg)
     95         else:
     96             raise

TypeError: Error: C:\Users\SUBHADIP\Python JupyterNote Book\wind-global.nc is not a valid NetCDF 3 file
            If this is a NetCDF4 file, you may need to install the
            netcdf4 library, e.g.,

            $ pip install netcdf4

**Comment by martinRenou** [comment]
Just like the error message is saying, you need to install netcdf4.

If you use conda: `conda install -c conda-forge netcdf4` or with pip: `pip install netcdf4`
