### ISSUE TITLE
Save to HTML

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipyleaflet#566]
It looks like one feature that is really missing compared to Folium is the ability to save the map to HTML. It seems to be searched the most in the documentation, according the the readthedocs search analytics.

It might be better implemented in ipywidgets directly though. As it might be a common request across widgets libraries. What do you think @maartenbreddels @jasongrout @SylvainCorlay ?

**Comment by giswqs** [comment]
I was searching for this feature as well. It would be a great addition to ipyleaflet. [Here](https://stackoverflow.com/questions/44800396/python-ipyleaflet-export-map-as-png-or-jpg-or-svg) is a relevant post on stackoverflow.

**Comment by martinRenou** [comment]
Thanks for the link :) I hate that the answer to "How to save the ipyleaflet map to HTML?" is "Use Folium" :P

**Comment by giswqs** [comment]
The [pydeck](https://deckgl.readthedocs.io/en/latest/) package has a `to_html()` function ([link](https://deckgl.readthedocs.io/en/latest/deck.html?highlight=to_html#pydeck.bindings.deck.Deck.to_html)), which might be worth looking into. 
```
r = pydeck.Deck(layers=[polygon, geojson], initial_view_state=INITIAL_VIEW_STATE)
r.to_html("geojson_layer.html", notebook_display=False)
```

![](https://i.imgur.com/XZKXvy7.png)

**Comment by maartenbreddels** [comment]
I don't think pydeck is using  the widget machinery here for the to_html. https://ipywidgets.readthedocs.io/en/latest/embedding.html#python-interface should do the job, which is an upstream port of what ipyvolume did, but a bit more low level.

https://github.com/maartenbreddels/ipyvolume/blob/159d0e3416734a6736fafe3fa8b3280ea3bc6501/ipyvolume/embed.py#L121 is much simpler to use (slightly ipyvolume specific), and can even download the js files next to it (so it is completely standalone).

I'd love to see a `some_dom_widget.to_html(...)`!

**Comment by martinRenou** [comment]
I did not know about the `embed_minimal_html`, thanks a lot Maarten.

**Comment by maartenbreddels** [comment]
I answered it at https://stackoverflow.com/questions/44800396/python-ipyleaflet-export-map-as-png-or-jpg-or-svg/61538586#61538586 
for html and png

**Comment by martinRenou** [comment]
Thanks a lot! We could either document this properly in ipyleaflet, or add a `.save` method like in Folium.

I would actually be in favor of adding the `.save` method, for feature parity with Folium,

**Comment by maartenbreddels** [comment]
just assign to DOMWidget.save :-D

**Comment by martinRenou** [comment]
:P I mean in ipyleaflet for now. But we could upstream it later if everybody agrees.

**Comment by giswqs** [comment]
It works like a charm!! Is it possible to specify the width and height (e.g., 100%) when saving the map to html? It seems the default height takes roughly 2/3 of the screen height. 

![](https://i.imgur.com/caWjc7e.gif)

**Comment by martinRenou** [comment]
It is possible. I wasn't sure if it was a good idea to expose it to the `.save` method.

But you can definitely do that changing the layout of the map: `m.layout.height = '100%'` or `m.layout.height = '1000px'`. I am not sure about the `100%` though. I agree it should take the entire screen though. I will give it a bit more thought.

**Comment by lorenae** [comment]
Hi! I'm new to ipyleaflet and it's really a great tool!!

I'd like to save to HTML not only the map but also other widgets included in the map. The [WealthOfNations map](https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/WealthOfNations.ipynb) is a good example of what I'd like to export and embed in an HTML page.

I've tried using the HTML provided by the "Embed widgets" option in the notebook,  but it doesn't refresh the graphics according to on_hover.

Any suggestions?
thanks in advance!
Lorena

**Comment by AyrtonB** [comment]
I've added full-screen control so will test automatically modifying the HTML afterwards. Thanks!

**Comment by AlexeyPechnikov** [comment]
I successfully saved the map, and the hover feature works as expected, but the popups don’t appear when I click on a feature. Is there a way to enable the popups? Without them, we’re losing significant interactivity with the map.

```
# Define the GeoJSON layer with embedded styles
geo_json = GeoJSON(
    data=geojson,
    style_callback=lambda feature: feature['properties']['style'],
    hover_style={'fillOpacity': 1},
    point_style={'weight': 0.5, 'fillOpacity': 0.5},
    ...
)
geo_json.on_click(on_click)
```

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/7b512354-6476-4636-ab05-974f7e57cbca">
