### ISSUE TITLE
Constructor arguments being ignored

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter-widgets/ipyleaflet#57]
When config args are passed to the classes they're not getting synced on the JS side (IIUC). This can be worked around by constructing the class first then setting the attributes afterwards. 

I believe this is the underlying reason for #51 (though there must be something else going on if `Circle` *does* work).

**Comment by mxndrwgrdnr** [comment]
This proposed workaround does not appear to be working. For example:
```
cm = CircleMarker()
cm.fill_color = '#800000'
m.add_layer(cm)
```
and the circle is still blue.

**Comment by SylvainCorlay** [comment]
This appears to behave correctly now.
