### ISSUE TITLE
Multiple Layer Groups do not work with Layer Control

### ISSUE THREAD

**Issue by JamesMaxwellHarrison** [jupyter-widgets/ipyleaflet#582]
When I create multiple layer groups, I am unable to control them properly from the Layer Control widget. There are two issues. 1) The name of the group is not displayed 2) The widget can only turn on/off the most recently created group.

Here is some example code.

from ipyleaflet import Map, Polyline, LayersControl, LayerGroup, basemaps

#Creating Map
m = Map(center = (42.5, -41), zoom =2)

#Creating 3 Polyline Layers
line = Polyline(
    locations=[[45, -122], [37.77, -122],[34, -118]],
    color="green" ,
    fill=False
)

line2 = Polyline(
    locations=[[46.51, -121.68], [38.77, -121.43], [35.04, -117.22]],
    color="red" ,
    fill=False
)

line3 = Polyline(
    locations=[
        [47.51, -120.68], [39.77, -120.43],[35.04, -116.22]],
    color="blue" ,
    fill=False
)

#Creating groups
group = LayerGroup(layers=(line,line2))
m.add_layer(group)

group2 = LayerGroup(layers=(line3,))
m.add_layer(group2)

#Enabling the LayersControl widget
control = LayersControl(position='topright')
m.add_control(control)

#Mapping
m

**Comment by martinRenou** [comment]
Try setting a name to the `LayersGroup`, like: `group = LayerGroup(name='group1', layers=(line,line2))` and `group2 = LayerGroup(name='group2', layers=(line3,))`

**Comment by JamesMaxwellHarrison** [comment]
Thanks! That worked to solve both problems. Just a heads up, I cannot find anything in the documentation that mentions the possibility of naming LayerGroups. It may be worth adding.

**Comment by martinRenou** [comment]
Good! Thanks for reporting back. It is actually documented here: https://ipyleaflet.readthedocs.io/en/latest/api_reference/layers_control.html

Do you think it should be made clearer in some ways?

**Comment by JamesMaxwellHarrison** [comment]
I think it would be clearer if you included similar language in the page for the layer group:
https://ipyleaflet.readthedocs.io/en/latest/api_reference/layer_group.html
or at least name one of the layer groups in the example to show that they can be named. I, probably unreasonably, assumed the layer group would not have the same attributes as individual layers and that they would be assigned the same name as the layer group object.

**Comment by martinRenou** [comment]
Actually it should be clear that the `LayerGroup` **is** a layer. It would be nice to generate a real API reference with inheritance/attributes/methods documentation.
