### ISSUE TITLE
map fail to load

### ISSUE THREAD

**Issue by ae86208** [jupyter-widgets/ipyleaflet#588]
```python
from ipyleaflet import Map, basemaps, basemap_to_tiles

m = Map(
    layers=(basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-04-08"), ),
    center=(52.204793, 360.121558),
    zoom=4
)

m
```

```zsh
Error Module jupyter-leaflet, semver range ^0.12.6 is not registered as a widget module

JupyterLab v1.2.4
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyter-leaflet v0.12.6  enabled  OK
        jupyterlab-drawio v0.6.0  enabled  OK
        jupyterlab_toastify v2.3.2  enabled  OK
        labview v0.1.0  enabled  OK
```

**Comment by martinRenou** [comment]
Do you have to stick with JupyterLab 1? Otherwise I would suggest updating to JupyterLab 2

**Comment by ae86208** [comment]
I have tried jupyterlab 2 in another environment, same error.

**Comment by ae86208** [comment]
JupyterLab v2.1.2
Known labextensions:
   app dir: /home/dujiahui/.local/share/jupyter/lab
        @arbennett/base16-one-dark v0.1.3  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.2.0  enabled  OK
        @jupyterlab/geojson-extension v2.0.1  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @krassowski/jupyterlab_go_to_definition v1.0.0  enabled  OK
        js v0.1.0  enabled  OK
        jupyter-leaflet v0.12.6  enabled  OK
        jupyter-vue v1.3.2  enabled  OK
        jupyter-vuetify v1.4.0  enabled  OK
        jupyterlab-theme-solarized-dark v1.0.1  enabled  OK

**Comment by martinRenou** [comment]
I doubt the error is coming from ipyleaflet.

What if you try a clean environment with JupyterLab 2 and ipyleaflet **only**? Some widgets labextension are not up-to-date with latest JupyterLab, and break other extensions like ipyleaflet. I saw that with ipyvolume last week.

**Comment by ae86208** [comment]
yet another environment

```zsh
node v10.19.0                                                                                                                                            
npm 6.14.4               
Python 3.8.2                                                                                                                                        
```
after running 
```zsh
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet
```
something happened ...

[jupyterlab-debug-i5u7mfcm.log](https://github.com/jupyter-widgets/ipyleaflet/files/4616991/jupyterlab-debug-i5u7mfcm.log)

**Comment by martinRenou** [comment]
You seem to have an old `node` version, even though your `npm` is up to date. I have no clue what is happening here. I feel like the important line is:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/typescript/-/typescript-3.7.5.tgz: unexpected end of file"
```
I've never seen this before.

**Comment by martinRenou** [comment]
I would suggest trying to update your node version if possible.

**Comment by ae86208** [comment]
> a clean environment with JupyterLab 2 and ipyleaflet only
This somehow finally works after upgrading my jupyterlab from v1.2.4 and with only ipyleaflet as extension.

**Comment by martinRenou** [comment]
Good. Happy it works for you now. It might be another extension that breaks ipyleaflet. I would try installing extensions one after the other if I were you, trying to find the extension that is causing this.
