### ISSUE TITLE
To make the float zoom levels useful for Vector Tile Layer

### ISSUE THREAD

**Issue by omanges** [jupyter-widgets/ipyleaflet#591]
Even though the zoom level trait has been made Float in the Vector Tile Layer support feature (https://github.com/jupyter-widgets/ipyleaflet/pull/544), the zoom only changes on a integer value, for example, map actually changes only on 1.0, 2.0, 3.0 ..., rather than changing on any floating zoom, as floating zoom levels are possible for Vector Tile.

**Comment by davidbrochart** [comment]
Looks like we need support for https://leafletjs.com/reference-1.6.0.html#map-zoomdelta

**Comment by martinRenou** [comment]
It should be straightforward to add expose this `zoom_delta` option to Python

**Comment by omanges** [comment]
@martinRenou  assign this to me, I can try this.

**Comment by omanges** [comment]
I think we should also implement the https://leafletjs.com/reference-1.6.0.html#map-zoomsnap, zoomsnap

**Comment by omanges** [comment]
Work for me now 
![image](https://user-images.githubusercontent.com/30625612/83386930-7b637d00-a409-11ea-89b0-e34596da8787.png)

**Comment by zxdawn** [comment]
Is it possible to make it also work for the scroll wheel?
