### ISSUE TITLE
Select and edit vector data in ipyleaflet 

### ISSUE THREAD

**Issue by AlexanderJuestel** [jupyter-widgets/ipyleaflet#599]
Dear community,

For the implicit open source geomodeling package GemPy (https://github.com/cgre-aachen/gempy) we are looking for a way to easily and interactively manipulate vector data/esri shape files (loading, plotting reprojection is no issue). 

We as Geologists mainly work with point data (e.g. orientation measurements of layers), line data (e.g. fault traces where indices have to be extracted) or polygons (e.g. geological maps where vertices of certain layer boundaries are needed). All of this is input data for our modeling package. In general, the modeling package only reads in point data and computes a model based on that. 

However, as we are visual people, we would like to visualize our (surface) data where we would like to use ipyleaflet for. In addition, we would like to perform very simple manipulations such as adding single points or removing points right away in python/Jupyter Notebooks instead of in a GIS software such as QGIS or ArcGIS.

Is this feature available in ipyleaflet somehow (e.g. With DrawControl) or does anyone know or can recommend any packeges (such as leaflet-geoman or geemap @giswqs) that can perform these basic tasks without leaving the ipyleaflet map environment?

Thanks for your help :)
Alex

**Comment by giswqs** [comment]
You can convert shapefiles to geojson, then you should be able to load the geojson to ipyleaflet and manipulate markers. Here are some relevant functions and examples:

- [shp_to_geojson()](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L2582)
- [ipyleaflet geojson example](https://github.com/jupyter-widgets/ipyleaflet/blob/stable/examples/GeoJSON.ipynb)
- [ipyleaflet DrawControl example](https://github.com/jupyter-widgets/ipyleaflet/blob/stable/examples/DrawControl.ipynb)

You can also try out geemap if you want to utilize the computational power of Earth Engine. Check out my [tutorials](https://github.com/giswqs/geemap/tree/master/examples):

- 5 Using drawing tools to interact with Earth Engine data 
- 6 Creating an interactive map with a marker cluster 

![](https://i.imgur.com/Lm5pDUr.gif)

![](https://i.imgur.com/GF4cOqh.gif)

**Comment by AlexanderJuestel** [comment]
Thanks for the quick response @giswqs! 

I will test it out and close the issue afterwards :)

**Comment by giswqs** [comment]
I just discovered that the ipyleaflet DrawControl has a `data` attribute. Basically, you can read a list features from a GeoJSON and assign it to the `data` attribute of the DrawControl. Then you can use the editing tool to edit shapes. Modifying attributes interactively might be possible as well, but it needs more work. I will see if I can implement it in leafmap next week. 
https://github.com/giswqs/leafmap/issues/179

![draw_control](https://user-images.githubusercontent.com/5016453/149437382-5cd069cc-5edc-4752-8c38-809bbe953401.gif)

**Comment by giswqs** [comment]
By integrating [ipysheet](https://github.com/QuantStack/ipysheet), it seems possible to edit vector data attributes interactively. 

![](https://github.com/QuantStack/ipysheet/blob/master/docs/source/ipysheet_slider.gif?raw=true)

**Comment by giswqs** [comment]
Thanks to the `data` attribute of the ipyleaflet DrawControl, [leafmap](https://github.com/giswqs/leafmap/) now supports loading, creating, editing, and saving vector data interactively without coding. 

https://user-images.githubusercontent.com/5016453/151687377-cb07c251-a048-40d7-86e5-9ff5b5f6ae98.mp4
