### ISSUE TITLE
Gray Basemaps

### ISSUE THREAD

**Issue by fng97** [jupyter-widgets/ipyleaflet#614]
Maps completely gray in [basemaps](https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html#basemaps-section):

- basemaps.Hydda.Full
- basemaps.Hydda.Base
- basemaps.MtbMap

![screenshot](https://user-images.githubusercontent.com/53615823/84392499-60a3bc00-abf2-11ea-80db-b7757e9cd845.png)

**Comment by davidbrochart** [comment]
Looks like their server is down, e.g.: http://c.tile.openstreetmap.se/hydda/base/5/15/11.png

**Comment by martinRenou** [comment]
Should we wait a bit more and not remove them yet? It might just be that they have low resources for fixing the servers :S

**Comment by davidbrochart** [comment]
I'm not sure it will be back to normal soon: https://github.com/karlwettin/carto-style-hydda/issues/3

**Comment by deeplook** [comment]
Would it not be nice to return some canned tile in such cases that better indicates a "broken service", like the infamous 404 pages...? ;)

**Comment by martinRenou** [comment]
This would be something to request to LeafletJS I guess

**Comment by HaudinFlorence** [comment]
The Hydda basemap has been removed from the examples https://github.com/jupyter-widgets/ipyleaflet/pull/966
