### ISSUE TITLE
Maps in grey from ipyleaflet

### ISSUE THREAD

**Issue by Carac0la** [jupyter-widgets/ipyleaflet#617]
Hi,

As you ask in you page https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html

I can´t see those maps, they are completely grey

Map(basemap=basemaps.Hydda.Full, center=center, zoom=zoom)
Map(basemap=basemaps.Hydda.Base, center=center, zoom=zoom)

![Captura](https://user-images.githubusercontent.com/61803590/84537924-fc1b5680-acf0-11ea-93b7-a7cae787714a.JPG)

**Comment by davidbrochart** [comment]
See #614
