### ISSUE TITLE
ImportError Velocity

### ISSUE THREAD

**Issue by MichielBbal** [jupyter-widgets/ipyleaflet#632]
Just installed (the wonderful) ipyleaflet.

Unfortunately I get an ImportError: 

from ipyleaflet import Map, Velocity, TileLayer, basemaps
import xarray as xr
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-32a7ed3fc090> in <module>
----> 1 from ipyleaflet import Map, Velocity, TileLayer, basemaps
      2 import xarray as xr

ImportError: cannot import name 'Velocity' from 'ipyleaflet' (/srv/conda/envs/notebook/lib/python3.7/site-packages/ipyleaflet/__init__.py)

**Comment by davidbrochart** [comment]
Velocity has moved, you need to import it with:
```python
from ipyleaflet.velocity import Velocity
```
See https://ipyleaflet.readthedocs.io/en/latest/api_reference/velocity.html.
