### ISSUE TITLE
SplitMap Control with transparent layers

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#635]
The SplitMap Control does not work properly for transparent layers. For example, when adding a WMS layer with transparency (i.e., NoData area is transparent), there is a background basemap on the left blocking the layer on the right. There is still a gray background on the left even when the basemap is cleared. Ideally, the left layer with transparency would be directly overlaid on the right layer without being interfered by the basemap or gray background.  

```
from ipyleaflet import Map, basemaps, basemap_to_tiles, SplitMapControl, WMSLayer

m = Map(center=(40, -100), zoom=4)
m.clear_layers()

right_layer = basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11")
# left_layer = basemap_to_tiles(basemaps.NASAGIBS.ModisAquaBands721CR, "2017-11-11")
naip_url = 'https://services.nationalmap.gov/arcgis/services/USGSNAIPImagery/ImageServer/WMSServer?'
left_layer = WMSLayer(url=naip_url, layers='0', name='NAIP Imagery', format='image/png')

control = SplitMapControl(left_layer=left_layer, right_layer=right_layer)
m.add_control(control)

m
```
![](https://i.imgur.com/7PmNSbG.gif)

**Comment by martinRenou** [comment]
I am not sure I understand the issue. Actually looking at the code and the result it looks to me that it's behaving correctly.

What behavior do you expect?

**Comment by giswqs** [comment]
Here is another example using geemap. I am trying to overlay the water extraction result (left layer) on the Landsat imagery (right layer). Note the gray background on the left is blocking the non-water area on the right. 

![](https://i.imgur.com/ghI7Blk.gif)

**Comment by giswqs** [comment]
This is what it looks like without the SplitMap control.

![](https://i.imgur.com/3etjdvI.gif)

**Comment by martinRenou** [comment]
Ok. So if I understand correctly what you want to do is the following:

```python
from ipyleaflet import Map, basemaps, basemap_to_tiles, SplitMapControl, WMSLayer

m = Map(center=(40, -100), zoom=4)

# Use default layer on the left, the ModisTerraTrueColorCR layer on the right
left_layer = m.layers[0]
right_layer = basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11")

control = SplitMapControl(left_layer=left_layer, right_layer=right_layer)
m.add_control(control)

# Overlay the WMSLayer
naip_url = 'https://services.nationalmap.gov/arcgis/services/USGSNAIPImagery/ImageServer/WMSServer?'
m.add_layer(WMSLayer(url=naip_url, layers='0', name='NAIP Imagery', format='image/png'))

m
```

But this code does not work, and I see lots of errors in the JavaScript console. IMO the SplitControl should be written from scratch, the code is really ugly and has plenty of issues, while it could really be simple and working well.

> Note the gray background on the left is blocking the non-water area on the right.

I don't understand this sentence.

**Comment by giswqs** [comment]
Sorry for the confusion! See below for what I can visualize in QGIS. Note the layer on top does not have a gray background. 

In QGIS
![](https://i.imgur.com/kp6FnaB.gif)

In ipyleaflet
![](https://i.imgur.com/ghI7Blk.gif)

**Comment by martinRenou** [comment]
Ok now I understand. So the code that should do what you want is:

```python
from ipyleaflet import Map, basemaps, basemap_to_tiles, SplitMapControl, WMSLayer

m = Map(center=(40, -100), zoom=4, layers=[basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11")])

naip_url = 'https://services.nationalmap.gov/arcgis/services/USGSNAIPImagery/ImageServer/WMSServer?'
left_layer = WMSLayer(url=naip_url, layers='0', name='NAIP Imagery', format='image/png')

control = SplitMapControl(left_layer=left_layer)
m.add_control(control)

m
```

But again, it does not work and lots of errors are appearing.

It looks like this works:

```python
from ipyleaflet import Map, basemaps, basemap_to_tiles, SplitMapControl, WMSLayer

m = Map(center=(40, -100), zoom=4, layers=[basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11")])

naip_url = 'https://services.nationalmap.gov/arcgis/services/USGSNAIPImagery/ImageServer/WMSServer?'
left_layer = WMSLayer(url=naip_url, layers='0', name='NAIP Imagery', format='image/png')

control = SplitMapControl(left_layer=left_layer, right_layer=basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11"))
m.add_control(control)

m
```

**Comment by giswqs** [comment]
Awesome! The second script works. Basically, it adds the right layer as the basemap so the right layer will always be under the left layer. Thanks a lot!

**Comment by martinRenou** [comment]
Yeah, although I would think the right solution is the first one I gave in my previous comment. This one:

```python
from ipyleaflet import Map, basemaps, basemap_to_tiles, SplitMapControl, WMSLayer

m = Map(center=(40, -100), zoom=4, layers=[basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11")])

naip_url = 'https://services.nationalmap.gov/arcgis/services/USGSNAIPImagery/ImageServer/WMSServer?'
left_layer = WMSLayer(url=naip_url, layers='0', name='NAIP Imagery', format='image/png')

control = SplitMapControl(left_layer=left_layer)
m.add_control(control)

m
```

What do you think?

**Comment by giswqs** [comment]
> Yeah, although I would think the right solution is the first one I gave in my previous comment. This one:
> 
> ```python
> from ipyleaflet import Map, basemaps, basemap_to_tiles, SplitMapControl, WMSLayer
> 
> m = Map(center=(40, -100), zoom=4, layers=[basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11")])
> 
> naip_url = 'https://services.nationalmap.gov/arcgis/services/USGSNAIPImagery/ImageServer/WMSServer?'
> left_layer = WMSLayer(url=naip_url, layers='0', name='NAIP Imagery', format='image/png')
> 
> control = SplitMapControl(left_layer=left_layer)
> m.add_control(control)
> 
> m
> ```
> 
> The basemap should always be visible in this case, but it's not.
> 
> What do you think?

This one does not work properly as the right layer does not show up.

**Comment by giswqs** [comment]
@martinRenou Thanks to your suggestion. I was able to make it work. Note that the script below is only a portion of a much longer Earth Engine script. Therefore, you won't be able to run it directly. 

```
layer_index = 0

water_image = ee.Image(water_images.toList(water_images.size()).get(layer_index))
landsat_image = ee.Image(landsat_images.toList(landsat_images.size()).get(layer_index))


left_layer = geemap.ee_tile_layer(water_image, water_vis, 'Water')
right_layer = geemap.ee_tile_layer(landsat_image, landsat_vis, 'Landsat')

Map = geemap.Map()
Map.addLayer(landsat_image, landsat_vis, 'Landsat')
Map.split_map(left_layer, right_layer)
Map
```
![](https://i.imgur.com/5e4JMWP.gif)

**Comment by martinRenou** [comment]
> This one does not work properly as the right layer does not show up.

Yes I saw that. What I mean is that it should be the right solution, and if it's not working it means it's a bug.

**Comment by martinRenou** [comment]
It looks great!

**Comment by giswqs** [comment]
> > This one does not work properly as the right layer does not show up.
> 
> Yes I saw that. What I mean is that it should be the right solution, and if it's not working it means it's a bug.

I agree. It is a bug.
