### ISSUE TITLE
branca dependency issue

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#638]
Does ipyleaflet require a specific version of `branca`? My [geemap](https://github.com/giswqs/geemap) package depends on ipyleaflet. During the pip installation of geemap with a fresh conda env, I got the following error every time. However, the package works fine even with this error. Is there a way to get rid of this error? Thanks. 

> ERROR: ipyleaflet 0.13.0 has requirement branca<0.4,>=0.3.1, but you'll have branca 0.4.1 which is incompatible.  
![](https://i.imgur.com/kImFycb.png)

**Comment by davidbrochart** [comment]
From `setup.py`: `branca>=0.3.1,<0.4`.
But I guess we could have `'branca>=0.3.1,<0.5'`, @martinRenou?

**Comment by martinRenou** [comment]
Yes I suppose we can require a larger version :) If the colormaps API did not change

**Comment by giswqs** [comment]
@davidbrochart @martinRenou Thanks a lot for your prompt action!

**Comment by martinRenou** [comment]
The fix is part of the new release `0.13.1`

**Comment by giswqs** [comment]
It seems the [ipyleaflet-feedstock](https://github.com/conda-forge/ipyleaflet-feedstock) is not updated yet. I will update geemap later once ipyleaflet-feedstock is updated. No rush. Thanks.

**Comment by davidbrochart** [comment]
It took some time but it's there: https://github.com/conda-forge/ipyleaflet-feedstock/pull/88
Unfortunately it failed because it's looking for a 0.13.0 JS file. We will probably need a 0.13.2 release, sorry for that.

**Comment by martinRenou** [comment]
No it simply required a fix on the recipe. Once it's fixed we can merge and get `0.13.1` on conda
