### ISSUE TITLE
Popup does not close properly using close()

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#641]
I'm adding a marker with a simple popup which I want to close programmatically via some callback. For simplicity this example does without callback. The issue is that while I can open the popup as expected by clicking the marker, I cannot fully close it programmatically, and there is an ugly "rest" of it when I execute some `close()` method of various objects, see below.
 
```python
from ipyleaflet import Map, Marker, Popup
from ipywidgets import HTML

m = Map(zoom=1)
marker = Marker(location=[0, 0])
marker.popup = Popup(
    child=HTML(str(marker.location)),
    close_button=True,
    auto_close=True,
    close_on_escape_key=True
)
m += marker
m
```

Any of these will only partially close the popup.

```python
marker.popup.child.close()
marker.popup.close()
marker.close()
```

![popup](https://user-images.githubusercontent.com/1001778/86210531-0eace100-bb75-11ea-9157-1fb29e69a0f1.gif)

**Comment by deeplook** [comment]
Same on the new version 0.13.1.

**Comment by martinRenou** [comment]
You should not use the `close` method this way, the `close` method is for closing the communication on the widget: https://github.com/jupyter-widgets/ipywidgets/blob/5170757c4e9b93731ac840640ebf5dd499f6d47c/ipywidgets/widgets/widget.py#L432. After calling `close` your widget might not be responsive anymore.

There is no way to close a Popup from Python currently.

**Comment by davidbrochart** [comment]
See also https://github.com/jupyter-widgets/ipyleaflet/issues/239

**Comment by deeplook** [comment]
Thanks for the quick response! Ok, I had searched for popup issues but missed #239. Anyway, it's almost what I expected. I guess when I click on a marker this is not communicated as an event that one could trigger otherwise, right?

**Comment by martinRenou** [comment]
> I guess when I click on a marker this is not communicated as an event that one could trigger otherwise, right?

You are right. When you close the popup with your mouse the Python back-end is not aware of it. And there is no way to trigger a close from Python in the current implementation.

**Comment by deeplook** [comment]
Ok, I'm closing this as #239 addresses the same and has been labeled "feature request"...
