### ISSUE TITLE
Heat map

### ISSUE THREAD

**Issue by msharky** [jupyter-widgets/ipyleaflet#65]
Hi there, apologies if this is not the right place to post, I should be grateful if someone could tell me where the best place would be, to direct my enquiry. 

I am using ipyleaflet for a project and I was wondering if there is any functionality to create a heat map on an ipyleaflet map from multiple latitude and longitude coordinates, because I don't see any examples of heatmaps in the examples folder. If there is no functionality for that, please could someone advise  how I could generate a heatmap. Thanks

**Comment by martinRenou** [comment]
`Heatmap` layers were added in a previous release, your issue should be fixed :)
