### ISSUE TITLE
Grey basemaps 

### ISSUE THREAD

**Issue by raziqraif** [jupyter-widgets/ipyleaflet#652]
The following basemap examples from https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html are not rendering properly.
![image](https://user-images.githubusercontent.com/42981908/87531196-5b0d1c00-c65f-11ea-9816-247f57ba2a1d.png)

**Comment by martinRenou** [comment]
Thanks for reporting. Closing as duplicate of #614
