### ISSUE TITLE
Basemaps on ipyleaflet.readthedocs.io are Grey

### ISSUE THREAD

**Issue by madisonwilson1** [jupyter-widgets/ipyleaflet#654]
Hello! Two of the basemaps on the docs website are currently grey.

https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html

Map(basemap=basemaps.Hydda.Full, center=center, zoom=zoom)
Map(basemap=basemaps.Hydda.Base, center=center, zoom=zoom)

**Comment by davidbrochart** [comment]
See #614
