### ISSUE TITLE
Cannot change the position of DrawControl

### ISSUE THREAD

**Issue by raziqraif** [jupyter-widgets/ipyleaflet#655]
As the title suggests, I can't seem to be able to change the position of DrawControl. It stays at the top-left corner of the map regardless of the specified position.

![image](https://user-images.githubusercontent.com/42981908/88226861-be3c1700-cc3a-11ea-90c8-d8410816b1b8.png)

Could be related to #649. 

ipyleaflet version: 0.13.0

**Comment by martinRenou** [comment]
Related to https://github.com/jupyter-widgets/ipyleaflet/pull/436 as well

**Comment by martinRenou** [comment]
Fixed by #656
