### ISSUE TITLE
Incorrect behaviour while updating the style callback of a GeoJSON layer

### ISSUE THREAD

**Issue by wxd** [jupyter-widgets/ipyleaflet#666]
Updating the style callback does something weird (see the GIF). It appears that a "new layer" with the new style gets drawn on the map, while the "old layer" gets hidden. However, the "new layer" seems to exist only in the JavaScript world, not in Python.

![ipyleaflet](https://user-images.githubusercontent.com/826826/89019805-2e732880-d31e-11ea-8cd8-273425c6dd90.gif)

May or may not be related to #657 and #658 .

#### Versions

- ipyleaflet==0.13.3
- ipykernel==5.3.2
- ipython==7.16.1
- traitlets==4.3.3
- Python 3.8.3
- Chrome 83.0.4103.116
- macOS Catalina 10.5.5

**Comment by wxd** [comment]
https://gist.github.com/wxd/8142eb1fb21a07d91073499263e06e0a

**Comment by martinRenou** [comment]
There is indeed a removal of the GeoJSON layer and a creation of a new one when updating the data (and a style update is actually a data update): https://github.com/jupyter-widgets/ipyleaflet/blob/master/js/src/layers/GeoJSON.js#L77-L83

The LayersControl might not actually like it, it might be the LayersControl being buggy. I wonder if there is a smarter way to update the data in LeafletJS without having to remove the layer and add it again.

**Comment by davidbrochart** [comment]
Fixed in #668
