### ISSUE TITLE
Return all markers created by the DrawControl

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#672]
The DrawControl has the `last_draw` property to return the last drawn object (e.g., marker, polygon, circle). Is there a way to return all the drawn objects? The DrawControl has methods such as `clear_markers()`, `clear_polygons()` to clear a specific type of drawn objects. It would be nice be able to return the info about a specific type of drawn objects, similar to the `last_draw` property but include all objects, not just the last one.

**Comment by 1kastner** [comment]
When you checn https://github.com/jupyter-widgets/ipyleaflet/blob/stable/examples/DrawControl.ipynb you see how to register a handler that keeps track of all the drawings. You can filter for the adjustments you are interested with and record them, or am I missing something?

**Comment by giswqs** [comment]
Yes, I am aware of the handler that can keeps tracks of all the drawings, which is the method I used in the [geemap](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L387) package. I was just wondering if there is a better way. Since the DrawControl has methods such as `clear_markers()`, `clear_polygons()` to clear a specific type of drawn objects, I assume that those objects are being tracked implicitly by the DrawControl. It would be nice to have methods, such as `get_markers()`, `get_polygons()`, to return a specific type of drawn objects. In this way, users don't have register a handler that keeps track of all the drawings and filter them by shape type.

**Comment by giswqs** [comment]
I discovered that the `data` attribute of the DrawControl stores the feature collection of all draw geometries.
