### ISSUE TITLE
Measure Control longitude coordinates bug

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#684]
When creating a map centered in the western world (e.g., US), if users pan the map to the eastern world (e.g., China), the longitude coordinates shown on the Measure Control are incorrect. For example, it is showing 259 W (-259), but it should be 101 E. 

```
import ipyleaflet

m = ipyleaflet.Map(center=[40, -100], zoom=4)

measure = ipyleaflet.MeasureControl(
    position='bottomleft',
    active_color='orange',
    primary_length_unit='kilometers'
)

m.add_control(measure)
m
```
![](https://i.imgur.com/C4B0pYF.gif)

**Comment by martinRenou** [comment]
Thanks for opening an issue. That might be something to report upstream (leafletjs measure control package) as it's not really ipyleaflet that implements this.
