### ISSUE TITLE
No 0.13.3 npm release

### ISSUE THREAD

**Issue by aliasmrchips** [jupyter-widgets/ipyleaflet#686]
The latest version on pypi is 0.13.3 but the latest on npm is 0.13.2

Is this intentional? Why is there not a 0.13.3 on npm?

**Comment by sackh** [comment]
Please see #670

**Comment by martinRenou** [comment]
It is intentional, it might be that 0.13.3 contained only bug fixes in Python, so we did not need a release for the JavaScript package.
