### ISSUE TITLE
SplitMap control has a horizontal line

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#693]
I noticed that the SplitMap control now has a horizontal line. Is this on purpose or is it a bug introduced in recent version updates?

https://ipyleaflet.readthedocs.io/en/latest/api_reference/split_map_control.html

![](https://i.imgur.com/OIq8BaG.gif)

**Comment by giswqs** [comment]
Interesting! It seems this horizontal line only appears in Google Chrome. No such issue with Microsoft Edge and Brave browser.  

![](https://i.imgur.com/j2GbcwG.gif)

**Comment by martinRenou** [comment]
Which ipyleaflet version are you using? It's odd, the splitmap control did not change in months. Can you replicate this issue with older ipyleaflet?

**Comment by giswqs** [comment]
This issue occurs when viewing the ipyleaflet readthedocs using Google Chrome. 


https://ipyleaflet.readthedocs.io/en/latest/api_reference/split_map_control.html

**Comment by davidbrochart** [comment]
I don't see the issue on Linux with either Chromium or Google Chrome.

**Comment by martinRenou** [comment]
Which Chrome version do you have @giswqs ?

**Comment by giswqs** [comment]
I am using Google Chrome Version 85.0.4183.102 (Official Build) (64-bit). The issue occurs on both Windows 10 and Manjaro Linux KDE. 

![](https://i.imgur.com/6z5OIOE.gif)

**Comment by martinRenou** [comment]
I don't see the issue with `Chromium: 85.0.4183.83 (Official Build) (64-bit)`. It might be due to the new chrome builds :S

**Comment by sackh** [comment]
It works fine on macOS, Google chrome - Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by martinRenou** [comment]
Thanks for your input @sackh 

@giswqs do you have a browser extension that could somewhat modify the CSS in the page?

**Comment by giswqs** [comment]
@martinRenou Good suggestion! It works fine when using the Chrome incognito mode without any extension. Let me test the extension one by one to see if I can find out which extension causes the issue. Thanks.

**Comment by martinRenou** [comment]
We might be able to workaround this by changing the CSS class names to be more scoped to Leaflet, so that it does not collide with your extension. Could you right click on the horizontal bar and inspect the CSS for this element?

**Comment by giswqs** [comment]
I found it. It is the [Nimbus Screenshot & Screen Video Recorder](https://chrome.google.com/webstore/detail/nimbus-screenshot-screen/bpconcjcammlapcogcnnelfmaeghhagj) extension causing issue.

**Comment by martinRenou** [comment]
I am fine closing this issue indeed. I looked at the splitmap CSS and all classes seem to start with `leaflet-`, so there is not much we can do about it I guess.

**Comment by giswqs** [comment]
@martinRenou I agree. It is not a general issue. It is not worth spending too much on this. Thank you for the hints. At least we found out extension causing this.
