### ISSUE TITLE
Map.save() doesn't keep ImageOverlay layer

### ISSUE THREAD

**Issue by sdxlzxjh** [jupyter-widgets/ipyleaflet#696]
I try to save a map to .html file. This map has two ImageOverlay layers (raster and legend) and a circle. After saving the map, the circle is there but the raster and legend are gone, like the following figures show:

Original map:

![image](https://user-images.githubusercontent.com/12840485/93460811-195d5380-f8e4-11ea-82a2-9741ac15299a.png)

Exported HTML:

![image](https://user-images.githubusercontent.com/12840485/93460938-4b6eb580-f8e4-11ea-8c45-201b73fd521b.png)

**Comment by sackh** [comment]
Already report issue here - https://github.com/jupyter-widgets/ipyleaflet/issues/592

**Comment by martinRenou** [comment]
Closing as duplicate, thanks for reporting
