### ISSUE TITLE
JupyterLab failed to build on Binder

### ISSUE THREAD

**Issue by banjaxedben** [jupyter-widgets/ipyleaflet#699]
When I try to build https://github.com/jupyter-widgets/ipyleaflet on [Binder](https://mybinder.org/):
`Building jupyterlab assets (build:prod:minimize)`
`An error occured.`
`RuntimeError: JupyterLab failed to build`
`See the log file for details:  /tmp/jupyterlab-debug-ileh7iey.log`
`Removing intermediate container ec463387576d`
`The command '/bin/sh -c ./postBuild' returned a non-zero code: 1`

I don't know how to debug this any further, as I don't have a local BinderHub server.
But I'm sure this used to work, right?

**Comment by martinRenou** [comment]
How do you install `nodejs`, which version is it? Try to pin the latest, `conda` seems to get a very old version if not pinned.

**Comment by banjaxedben** [comment]
Thanks for the fast response, but I don't understand.
I'm using the public hosted version of Binder. I have no control over the version of nodejs they use.
Or do I?
https://mybinder.readthedocs.io/en/latest/config_files.html

**Comment by martinRenou** [comment]
You do, by putting the constraint `nodejs=14.11` in the environment file

**Comment by banjaxedben** [comment]
Do you want me to create a PR for [https://github.com/jupyter-widgets/ipyleaflet/blob/master/environment.yml](https://github.com/jupyter-widgets/ipyleaflet/blob/master/environment.yml) ?

**Comment by martinRenou** [comment]
Oh sorry I thought you were building a binder from one of your repos that depend on ipyleaflet! Yes then it might make sense to open a PR and see if that fixes it.

**Comment by banjaxedben** [comment]
My forked branch (https://mybinder.org/v2/gh/banjaxedben/ipyleaflet/patch-1) with the new enviroment.yml file builds successfully on Binder.

I'm not sure how robust this is, but at least it works for now.
The whole Python/Javascript/Jupyter/Notebook/Lab/Binder/Colab mashup seems quite fragile to me!

**Comment by martinRenou** [comment]
> The whole Python/Javascript/Jupyter/Notebook/Lab/Binder/Colab mashup seems quite fragile to me!

I think this time it's conda's fault ;) I've seen this issue with conda installing a very old version of nodejs for no reason.

All of this will get better when JupyterLab 3 comes out. You should not need to install any labextension soon, it will be quite helpful.

Also you can put Colab out of the picture :P Because Colab does not yet support custom widgets.

**Comment by martinRenou** [comment]
Thanks for the PR!

**Comment by martinRenou** [comment]
Actually the stable branch is still not building. And I am realizing that conda is not used anymore, but mamba is!

**Comment by banjaxedben** [comment]
Hmm. When did Binder switch to mamba? I thought it was not stable yet.
At least that would explain why builds that previously worked have started failing.

**Comment by martinRenou** [comment]
It if actually quite stable, I've been using it on my machine since multiple months and did not have a single issue.

Maybe we should run the labextension install in debug mode to see the error message.

**Comment by martinRenou** [comment]
According to @jtpio we should try to run the labextension install with:

```
jupyter labextension install jupyter-leaflet --no-build
jupyter lab build --minimize=False
```

**Comment by jtpio** [comment]
Opened https://github.com/jupyter-widgets/ipyleaflet/pull/704 to add the `--minimize=False` flag.

**Comment by martinRenou** [comment]
Just for the record, this was apparently due to memory issues when building JupyterLab. Should be fixed when JupyterLab 3 is out, we won't need to build it anymore.
