### ISSUE TITLE
Feature Request: Add support for projections not supported by Leaflet

### ISSUE THREAD

**Issue by tylere** [jupyter-widgets/ipyleaflet#70]
The [Proj4Leaflet](http://kartena.github.io/Proj4Leaflet/) Javascript library adds support for additional projections in Leaflet, beyond the [standard projections](http://leafletjs.com/reference-1.1.0.html#projection). Could this also be added to IPyLeaflet so that non-standard projections could be requested? For example:

```
map = ipyleafletee.Map(
  crs='EPSG:3020',  # http://spatialreference.org/ref/epsg/wgs-84-antarctic-polar-stereographic/
  zoom=6,
  center=[0, 0],
  default_tiles=ipyleaflet.TileLayer(url=SOME_URL_THAT_RETURNS_PROJECTED_TILES)
)
map
```

**Comment by fabricebrito** [comment]
+1

**Comment by Juanlu001** [comment]
How to use the standard projections to begin with? https://leafletjs.com/reference-1.1.0.html#projection

**Comment by betolink** [comment]
I was going to open this issue but it's already open so, is there any reason why this is not supported? 
I think a lot of people work with non standard projections and it would be nice-to-have feature. I can work on it and send a PR for next week.

**Comment by davidbrochart** [comment]
There is no particular reason not to support it, and it would be great to have. I investigated the use of Proj4Leaflet with vector tiles (that we now have in ipyleaflet), which would have been really nice, but it doesn't seem to be possible (https://github.com/kartena/Proj4Leaflet/issues/173).
If you want to work on that, that would be awesome.

**Comment by betolink** [comment]
I guess we can resolve this issue on the next release =)

**Comment by davidbrochart** [comment]
Let's close it now, thank you!

**Comment by martinRenou** [comment]
Thanks again :)
