### ISSUE TITLE
Saving maps to HTML

### ISSUE THREAD

**Issue by itisthoughttobemaeri** [jupyter-widgets/ipyleaflet#703]
Maps save correctly, but when I open them, they are blank/empty.

**Comment by martinRenou** [comment]
It might be related to https://github.com/jupyter-widgets/ipyleaflet/issues/592 but I am not sure. 

What do you have on your Map widget? Could you share the HTML file?

**Comment by itisthoughttobemaeri** [comment]
They are showing now, don't know why it was not working, thanks anyway!

**Comment by martinRenou** [comment]
Maybe it was a network issue, the tiles still needs to be loaded online.
