### ISSUE TITLE
Remove class_name from all Widget classes

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipyleaflet#709]
Some widgets have a `class_name` property, this does not make sense to have and we should remove them.

Users can't provide custom CSS to the page without some hacks, so exposing this property is not good.

**Comment by deeplook** [comment]
I see only `Path` and `Popup` having that, right?

**Comment by martinRenou** [comment]
Yes :) It's also mentioned in the docs.

**Comment by deeplook** [comment]
Feel free to assign to me...

**Comment by martinRenou** [comment]
Thanks!

**Comment by martinRenou** [comment]
Fixed by #729
