### ISSUE TITLE
WMS Tile not loading completely 

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [jupyter-widgets/ipyleaflet#713]
I'm using this following demo but tile are not loading completely.
How can I debug this?

```
from ipyleaflet import Map, WMSLayer, basemaps, Heatmap
from random import uniform

wms = WMSLayer(
    url='https://www5.agr.gc.ca/atlas/services/imageservices/landuse_2010/ImageServer/WMSServer',
    layers='0',
    format='image/png',
    tile_size=100,
    opacity=0.1,
    transparent=True,
    attribution='Weather data © 2012 IEM Nexrad'
)

m = Map(basemap=basemaps.CartoDB.Positron, center=(45.289117, -74.231510), zoom=10)

m.add_layer(wms)
```
This is the result and I can never get a full map, even if I zoom or move

![image](https://user-images.githubusercontent.com/1645032/95663185-0f0d2e80-0b0b-11eb-8d13-3830710fcd8f.png)

**Comment by davidbrochart** [comment]
You can go to the Network analyzer, for instance by pressing F12 in Firefox. You will see a bunch of HTTP 400 status (bad request), for instance for this tile:
https://www5.agr.gc.ca/atlas/services/imageservices/landuse_2010/ImageServer/WMSServer?service=WMS&request=GetMap&layers=0&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=100&height=100&srs=EPSG%3A3857&bbox=-8312068.203843208,5636772.213862039,-8296780.798186173,5652059.619519074

**Comment by AlexandreBorowczyk** [comment]
Thanks it seems I had the wrong URL. This one 
`https://geoappext.nrcan.gc.ca/arcgis/services/FGP/canada_landcover_2015_en/MapServer/WMSServer?`

 worked better.
