### ISSUE TITLE
WidgetControl transparent background

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-widgets/ipyleaflet#716]
It would be nice to be able to insert a `WidgetControl` on the map without it having a frame and a solid background, so that we can see the map through.

**Comment by omanges** [comment]
@davidbrochart  are you looking for something like this?
![image](https://user-images.githubusercontent.com/30625612/96334192-7a677b00-108c-11eb-8fff-4c285d369e57.png)

**Comment by davidbrochart** [comment]
Yes, that would be awesome!

**Comment by omanges** [comment]
Cool, Can you please assign this issue to me?

**Comment by omanges** [comment]
@davidbrochart can we close this?

**Comment by martinRenou** [comment]
Yes thanks!
