### ISSUE TITLE
Proper selection tool

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-widgets/ipyleaflet#718]
`DrawControl` can be used to e.g. draw a rectangle and get the resulting bounding box, but it is not really meant for that.
We could use https://github.com/w8r/leaflet-area-select ?

**Comment by davidbrochart** [comment]
Another option is to use: https://github.com/heyman/leaflet-areaselect/

**Comment by deeplook** [comment]
See also https://github.com/jupyter-widgets/ipyleaflet/issues/596.

**Comment by davidbrochart** [comment]
@deeplook do you want to give it a try?

**Comment by martinRenou** [comment]
Let's close this one as it's a duplicate :)
