### ISSUE TITLE
Configuration directory for basemaps

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipyleaflet#741]
It may be nicer to populate the basemap bunch with JSON data from a `share/jupyter/leaflet/basemaps` directory...

Ideally this would be installed alongside the front-end bundle so that xleaflet can also pick it up...

**Comment by davidbrochart** [comment]
Maybe this could be done as part of the new library we want to create with @darribas?

**Comment by davidbrochart** [comment]
ref: https://github.com/geopandas/contextily/issues/153

**Comment by SylvainCorlay** [comment]
> Maybe this could be done as part of the new library we want to create with @darribas?
> ref: geopandas/contextily#153

Thanks!
I think this is a brilliant idea.

**Comment by jorisvandenbossche** [comment]
> JSON data from a share/jupyter/leaflet/basemaps directory...

To understand better, what would be the exact idea of the above? Is this something that already exists from the leaflet installation, or is it something that ipyleaflet (or another package) would generate and install, so it is usable by ipyleaflet itself and other packages like xleaflet?

It's to better understand a possible relation with the idea of https://github.com/geopandas/contextily/issues/153. For example, I think the idea over there was to make this a python package, but that might not necessarily work for other packages likes xleaflet?

**Comment by davidbrochart** [comment]
> is it something that ipyleaflet (or another package) would generate and install, so it is usable by ipyleaflet itself and other packages like xleaflet?

From what I understand it could be generated by https://github.com/geopandas/contextily/issues/153. Even though it would be a python package, it could install some JSON data files in `share/jupyter/leaflet/basemaps`, that xleaflet could use.

**Comment by martinRenou** [comment]
Continuing the discussion in geopandas  geopandas/contextily#153
