### ISSUE TITLE
ValueError: Thresholds are not sorted on Choropleth

### ISSUE THREAD

**Issue by mariepastora** [jupyter-widgets/ipyleaflet#742]
Hello,
I'm using ipyleaflet in jupyter notebook, and for some reason I'm unable to correctly display a choropleth map.
I have this as my choropleth layer code: 

```
layer = Choropleth(
    geo_data = new_json,
    choro_data = choro,
    key_on = 'index',
    )
```
 
with `new_json` a feature collection as such (`index` being the key i'm using):

```{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'properties': {'index': 'G4800010950100',
    'STATEFP': '48',
    'COUNTYFP': '001',
    'Estimates: Hispanic or Latino': 591},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-95.42217399950857, 32.04381799979256],
      [-95.4382209992762, 32.03561199967741],
      [-95.42410599971107, 32.018892999976096],]]},
   'index': 'G4800010950100'},
},
  ...]}
```

and `choro` a dictionary looking like this: 
```
{'G4800010950100': 20.236250968241677,
 'G4800010950401': 64.44991789819376,
 'G4800010950402': 65.51404345521993,
 'G4800010950500': 57.167870431166556,
 'G4800010950600': 34.147217235188506,
 'G4800010950700': 71.11738604275918,
 'G4800010950800': 45.43338108882522,
 'G4800010950901': 30.844005554698356,
...}
```

I am systematically getting a `ValueError: Thresholds are not sorted` error.

I've tried sorting the choro dictionary, but got no luck. I've tried a fair amount of iterations adding in a colormap argument like here: https://ipyleaflet.readthedocs.io/en/latest/api_reference/choropleth.html, and still can't figure out what I'm doing wrong.
(i've never opened an issue on GitHub so sorry if this is not the way to do so! thank you for reading :) )

**Comment by sackh** [comment]
@mariepastora - If possible please share the complete GeoJSON file and Choro dictionary, as the example given by you above works without any error.

**Comment by mariepastora** [comment]
Thanks for looking into it @sackh -- here are my files:
https://github.com/mariepastora/mariepastora.github.io/blob/master/choro.json
https://github.com/mariepastora/mariepastora.github.io/blob/master/new_json.json
Not sure what's wrong in them for it not to work

**Comment by mariepastora** [comment]
Found the problem: can't have NaN in the choropleth dictionary. It'd be great if there was a way to ignore errors in the Choropleth() options. Thanks!

**Comment by martinRenou** [comment]
Thanks for reporting back the actual issue :) So this is related to https://github.com/jupyter-widgets/ipyleaflet/issues/428
