### ISSUE TITLE
Help visualizing WMS layer

### ISSUE THREAD

**Issue by epifanio** [jupyter-widgets/ipyleaflet#746]
I am trying to render the following WMS layer into ipyleafle, but I can get it to workt:

```python
from owslib.wms import WebMapService
wms_url = 'http://nbstds.met.no/thredds/wms/NBS/S3A/2019/09/27/OLCI/S3A_OL_1_EFR____20190927T095206_20190927T095506_20190927T114949_0180_049_350_1800_LN1_O_NR_002.nc?'
wms = WebMapService(wms_url, version='1.3.0')

wms_layers = list(wms.contents)
"""
wms_layers
['Oa01_radiance',
 'Oa02_radiance',
 'Oa03_radiance',
 'Oa04_radiance',
 'Oa05_radiance',
 'Oa06_radiance',
 'Oa07_radiance',
 'Oa08_radiance',
 'Oa09_radiance',
 'Oa10_radiance',
 'Oa11_radiance',
 'Oa12_radiance',
 'Oa13_radiance',
 'Oa14_radiance',
 'Oa15_radiance',
 'Oa16_radiance',
 'Oa17_radiance',
 'Oa18_radiance',
 'Oa19_radiance',
 'Oa20_radiance',
 'Oa21_radiance',
 'altitude',
 'quality_flags'
"""

wms['Oa01_radiance'].crsOptions

"""
['EPSG:900913',
 'CRS:84',
 'EPSG:3408',
 'EPSG:27700',
 'EPSG:32661',
 'EPSG:32761',
 'EPSG:3409',
 'EPSG:3857',
 'EPSG:41001',
 'EPSG:4326']
"""

wms_layer = WMSLayer(url=wms_url, layers=wms_layers[21], format='image/png')

m = ipyleaflet.Map(zoom=5, center=(66, 8))
m.add_layer(wms_layer)
m
```

The wms loads correctly in GIS (e.g.: QGIS) this its [GetCapabilities](http://nbstds.met.no/thredds/wms/NBS/S3A/2019/09/27/OLCI/S3A_OL_1_EFR____20190927T095206_20190927T095506_20190927T114949_0180_049_350_1800_LN1_O_NR_002.nc?service=WMS&version=1.3.0&request=GetCapabilities)

I tried settings several options like `CRS` -  with no luck.
Do you have any advice on how to render one of its layer?

**Comment by davidbrochart** [comment]
It renders this on my side (although it takes a bit of time):
![image](https://user-images.githubusercontent.com/4711805/99084471-46b63d00-25c7-11eb-8f46-1db0f058fb10.png)

**Comment by epifanio** [comment]
That is the correct image, thank you for testing it. 
 I can't get it to render on my side, probably due to a slow connection and timeout. I will test from office with better connection to confirm it. Thank you for testing it!

**Comment by davidbrochart** [comment]
Should we close this issue?

**Comment by epifanio** [comment]
There are many problems on that server, it is now returning an internal error - so definitely was a server-side issue.
Perhaps a "still loading notification/debug message" or "raise a time-out error message" could improve user experience, but this should probably be handled on the leadlet.js side.

**Comment by davidbrochart** [comment]
Indeed, this would be on the LeafletJS side.
