### ISSUE TITLE
Several basemaps seem no longer working

### ISSUE THREAD

**Issue by phicat7856** [jupyter-widgets/ipyleaflet#753]
Hello,
Several basemaps do not work anylonger, such as "basemaps.NASAGIBS.ViirsTrueColorCR,", which returns a back picture since a few days.
Could you fix that?
Or give some path to get directly such weather basemaps? 
I should be very intersted in getting wind layers but as far now, I didn't manage.
Thank's

**Comment by davidbrochart** [comment]
> Several basemaps do not work anylonger, such as "basemaps.NASAGIBS.ViirsTrueColorCR,", which returns a back picture since a few days.

I just checked, it seems to work fine:
![image](https://user-images.githubusercontent.com/4711805/100492767-b08a2700-312f-11eb-93db-669285350b9c.png)

**Comment by phicat7856** [comment]
OK, thanks,  it also works fine for me now! 
Perhaps the problem came from the source, as the picture was black for a few days.
![image](https://user-images.githubusercontent.com/71965172/100494736-ceae5200-3144-11eb-89ce-abbb7fa2d22a.png)
