### ISSUE TITLE
Creating a widget similar to the LayerControl button

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#764]
I am trying to create a widget on the map that can respond to mouse hover event, similar to the LayerControl button (e.g., show/hide other widgets based on mouse hover). Can this be implemented using ipywidget? I tried the ToggleButton, but it seems it can only respond to click event, not hover. Any advice will be appreciated. 

![](https://i.imgur.com/OD6O8xy.gif)

**Comment by martinRenou** [comment]
You might be able to use [ipyevents](https://github.com/mwcraig/ipyevents) to get all kinds of mouse events on your widget.

**Comment by giswqs** [comment]
@martinRenou I will look into the ipyevents package. Thanks.

**Comment by martinRenou** [comment]
I would be interested in seeing what you come up with... IDK, it could be a good replacement for the current LayersControl, with stateful checkboxes that are really linked to the `visible` attributes of the layers.

**Comment by giswqs** [comment]
Let me try. Will keep you posted.

**Comment by giswqs** [comment]
My experiment using [ipyevents](https://github.com/mwcraig/ipyevents) to trigger mouse hover events. 

```
from ipyevents import Event 
from IPython.display import display
import ipywidgets as widgets

btn = widgets.Button(button_style="primary", icon="globe")
btn.layout.width = "36px"

chk1 = widgets.Checkbox(
    value=True,
    description='Layer 1',
    indent = False
)

chk2 = widgets.Checkbox(
    value=False,
    description='Layer 2',
    indent=False
)

vb = VBox([btn])
vb.layout.max_width = '100px'

d = Event(source=vb, watched_events=['mouseenter', 'mouseleave'])

def handle_event(event):   
    
    if event['type'] == 'mouseenter':
        vb.children = [btn, chk1, chk2]
    elif event['type'] == 'mouseleave': 
        vb.children = [btn]

d.on_dom_event(handle_event)

display(vb)
```
```
import geemap
from ipyleaflet import WidgetControl

Map = geemap.Map(ee_initialize=False)

control = WidgetControl(widget=vb, position="topright")
Map.add_control(control)

Map
```

![](https://i.imgur.com/16KKCQF.gif)
