### ISSUE TITLE
Unexpected position change to the LayersControl after adding new layers

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#765]
When creating a default map, the LayersControl is at the topright corner. However, whenever a new layer is added to the map, the LayersControl position changes and is positioned beneath other custom widgets. Is it possible to prevent this unexpected position change and always keep the LayersControl at the topright (i.e., above other custom widgets)?

```
from ipyleaflet import Map, WidgetControl, LayersControl, Marker
import ipywidgets as widgets

m = Map(center=[40, -100], zoom=4)

m.add_control(LayersControl(position="topright"))

btn_widget = widgets.ToggleButton(icon="wrench")
btn_widget.layout.width='40px'
btn_ctrl = WidgetControl(widget=btn_widget, position="topright")
m.add_control(btn_ctrl)

m

# when a new layer is added to the map, the LayersControl widget position is changed
m.add_layer(Marker(location=(52.204793, 360.121558)))

```

![](https://i.imgur.com/AA2SN9G.gif)

**Comment by martinRenou** [comment]
This is more related to LeafletJS, we might not be able to fix this here without hacking too much.

**Comment by giswqs** [comment]
Good to know. Thanks for the info.
