### ISSUE TITLE
Removed.

### ISSUE THREAD

**Issue by Newbie1392** [jupyter-widgets/ipyleaflet#766]
Removed.

**Comment by giswqs** [comment]
1. See https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/AntPath.ipynb

2. See https://github.com/jupyter-widgets/ipyleaflet/issues/62

**Comment by Newbie1392** [comment]
2. Do you know how can i change the color of the whole cluster, not the specific marker?
