### ISSUE TITLE
LocalTileLayer, Jupyter notebook and Voila

### ISSUE THREAD

**Issue by jifcon** [jupyter-widgets/ipyleaflet#767]
Dear team,

First, a big Thanks for your effort on widgets a ipyleaflet!

I have a problem (and probably an issue) with LocalTileLayer for offline maps. I'm using the grey openstreet basemap, that I previously downloaded in tiles for zoom 2 to 6. I found a problem when I try to open the basemap in Voila, but in Jupyter notebook is fine. I attach some screenshots of tests done. I tried several options but none of them work. 

On Jupyter Nb:

<img width="667" alt="Jupyter Nb Local" src="https://user-images.githubusercontent.com/38166748/102499995-207b3580-407c-11eb-9a5e-1c95bcb81d9a.PNG">

The same but changed to Voila:

On Voila:

![image](https://user-images.githubusercontent.com/38166748/102500479-a5664f00-407c-11eb-971c-7d81f076ca8a.png)
![image](https://user-images.githubusercontent.com/38166748/102500904-1a398900-407d-11eb-87d3-99d4b1ff47d8.png)

I tried other options with similar results like:

![image](https://user-images.githubusercontent.com/38166748/102501314-96cc6780-407d-11eb-8fdd-49e1d395d837.png)
![image](https://user-images.githubusercontent.com/38166748/102501459-c24f5200-407d-11eb-9684-8d6eaee027d1.png)

![image](https://user-images.githubusercontent.com/38166748/102501826-26721600-407e-11eb-86e7-fc8520ee02eb.png)
![image](https://user-images.githubusercontent.com/38166748/102501901-3db10380-407e-11eb-9d09-376ae4010fca.png)

I even tried with path="./tiles/{z}..." or adding the full local url "C:...." to the tiles but with similar results.

I think it is a problem with ipyleaflet but could be a problem with Voila (online maps work 10/10).

Thanks++

J.I.

**Comment by davidbrochart** [comment]
That is very strange, I don't see why you would have such a behavior.
It would be good to look at what tiles are loaded in the browser (in the network analyzer), and check that they are right.

**Comment by jifcon** [comment]
Thanks for your answer. 

I had a look at the network traffic and I realized that is caching the load of images, so taking old layers (whenever they were created) and displaying the old tiles instead of new ones. In fact I tried to change (overwriting directly) the tiles from the grey theme to the "sea" theme, also available for free in openstreetmaps, and jupyter - were was showing the old tiles.

So it was really weird that in order to show the new tiles I had to restart my PC and .. voilà! at the first try, the new tiles were there.

Since the solution is offline, I will use the same tiles always, but I'm looking for a way to refresh the jupyter - voila cache without restarting the PC.

Thanks++!

**Comment by davidbrochart** [comment]
Maybe clearing the browser cache is enough, e.g. on Google Chrome: https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by jifcon** [comment]
Well, in fact this was my first option, but I don't know why it didn't work. I tried then with this solution https://stackoverflow.com/questions/49568038/clear-cached-images-in-jupyter-notebook, but was suboptimal, refreshing some tiles but not others.. finally I restarted. Probably was a problem with the browser, anyway no is working perfectly! Thanks!

**Comment by davidbrochart** [comment]
Awesome, closing this issue then.
