### ISSUE TITLE
Basemaps missing (i.e. completely grey) from the ipyleaflet page

### ISSUE THREAD

**Issue by Helicopter9005** [jupyter-widgets/ipyleaflet#768]
Hello,

Firstly, thanks for your fantastic product - it is awesome to work with... :)

The following base maps are missing from this page: https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html

basemaps.Hydda.Full
basemaps.Hydda.Base
basemaps.Strava.All
basemaps.Strava.Ride
basemaps.Strava.Run
basemaps.Strava.Water
basemaps.Strava.Winter

They also do not work in Jupyter notebook...

Best Wishes,
Helic

**Comment by davidbrochart** [comment]
See #606
