### ISSUE TITLE
ipyleaflet v0.13.4 import error on Windows 10 

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#769]
The pip installation works fine on Windows 10. However,  `import ipyleaflet` is throwing an error due to the missing `geos_c.dll`. This is likely caused by the recently added dependency of shapely. 

![](https://i.imgur.com/OFDudk0.png)

**Comment by davidbrochart** [comment]
Have you tried one of the solutions in https://stackoverflow.com/questions/13144158/python-geos-and-shapely-on-windows-64 ?

**Comment by giswqs** [comment]
Downgrading shapely to v1.3.0 solved the problem. It seems shapely is only used by the `WKTLayer` class. It might be worth considering making shapely an optional dependency rather than a required one causing installation and importing errors. 
```
pip install Shapely==1.3.0
```
https://github.com/Toblerity/Shapely/blob/master/setup.py#L24

> On import, Shapely loads a GEOS shared library. GEOS is a run time
requirement. Additionally, the speedups and vectorized C extension
modules need GEOS headers and libraries to be built. Shapely versions
 >=1.3 require GEOS >= 3.3.
