### ISSUE TITLE
Issue with processPhosphorMessage method removal

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipyleaflet#773]
I removed the `processPhosphorMessage` method call and replaced it with `processLuminoMessage`, this was a mistake https://github.com/jupyter-widgets/ipyleaflet/pull/771/files#diff-2262554297993f82eed10102b4e6b1e0157de7d79505a0bc76369905ccd02d78L412. This would have been caught by TypeScript...

We need to patch this and release again.

**Comment by jasongrout** [comment]
Fixed by https://github.com/jupyter-widgets/ipyleaflet/pull/969
