### ISSUE TITLE
OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']

### ISSUE THREAD

**Issue by AK-1996** [jupyter-widgets/ipyleaflet#779]
I installed Ipyleaflet package using the 'pip install ipyleaflet' command as explained in the README.md section, but when I try to import the package in Jupyter notebook I continue to get this error:

OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']

I thought the problem was I hadn't installed 'geos' package and I tried to get it with 'pip install geos', but it wasn't the right way..
I forgot to mention my OS is MacOS Big Sur if it can help
Anyone could help me please?

**Comment by giswqs** [comment]
This is caused by the `shapely` dependency recently added to ipyleaflet. See https://github.com/jupyter-widgets/ipyleaflet/issues/769#issuecomment-752704272
```
pip install Shapely==1.3.0
```

**Comment by martinRenou** [comment]
We should maybe pin this version to the working one until this is fixed upstream

**Comment by AK-1996** [comment]
I have already tried with 'pip install Shapely==1.3.0' but still doesn't works

**Comment by giswqs** [comment]
@AK-1996 Try creating a new conda env, e.g., 

```
conda create -n leaflet python
pip install Shapely==1.3.0
pip install ipyleaflet
jupyter notebook
```

**Comment by AK-1996** [comment]
I tried to activate the new env using:
"conda activate leaflet"

and I get the following error:
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

I used the "conda init zsh" command as suggested but nothing changed

Should I do something else?

**Comment by davidbrochart** [comment]
You should probably open a new shell, in order to activate the change.

**Comment by AK-1996** [comment]
You were right, now I can activate the new Conda env, but the problem doesn't disappear.
I looked also for the 'library geos_c' file but I don't have it at all in /opt/local/lib/libgeos_c.dylib or in /Library/Frameworks/GEOS.framework/Versions/Current/GEOS as the error 
I can share with the error when I run the script:
`OSError                                   Traceback (most recent call last)
<ipython-input-1-2746d0f9e28c> in <module>
----> 1 import ipyleaflet
      2 import pandas as pd
      3 import ipaddress

~/opt/anaconda3/envs/leaflet/lib/python3.9/site-packages/ipyleaflet/__init__.py in <module>
      9 
     10 try:
---> 11     from .leaflet import *  # noqa
     12     from .basemaps import basemaps   # noqa
     13 except ImportError:

~/opt/anaconda3/envs/leaflet/lib/python3.9/site-packages/ipyleaflet/leaflet.py in <module>
     21 
     22 from branca.colormap import linear, ColorMap
---> 23 from shapely import geometry, wkt
     24 
     25 from ._version import EXTENSION_VERSION

~/opt/anaconda3/envs/leaflet/lib/python3.9/site-packages/shapely/geometry/__init__.py in <module>
      2 """
      3 
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~/opt/anaconda3/envs/leaflet/lib/python3.9/site-packages/shapely/geometry/base.py in <module>
      7 from ctypes import pointer, c_size_t, c_char_p, c_void_p
      8 
----> 9 from shapely.coords import CoordinateSequence
     10 from shapely.ftools import wraps
     11 from shapely.geos import lgeos, ReadingError

~/opt/anaconda3/envs/leaflet/lib/python3.9/site-packages/shapely/coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7 
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10 

~/opt/anaconda3/envs/leaflet/lib/python3.9/site-packages/shapely/geos.py in <module>
     69             '/opt/local/lib/libgeos_c.dylib',
     70         ]
---> 71     _lgeos = load_dll('geos_c', fallbacks=alt_paths)
     72     free = load_dll('c').free
     73     free.argtypes = [c_void_p]

~/opt/anaconda3/envs/leaflet/lib/python3.9/site-packages/shapely/geos.py in load_dll(libname, fallbacks)
     47                     pass
     48         # the end
---> 49         raise OSError(
     50             "Could not find library %s or load any of its variants %s" % (
     51                 libname, fallbacks or []))

OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']`

**Comment by davidbrochart** [comment]
Please use `conda install` instead of `pip install`.

**Comment by AK-1996** [comment]
Do you mean to install Shapely or the entire Ipyleaflet package?

**Comment by davidbrochart** [comment]
If you `conda install ipyleaflet` you don't need to install shapely, it will pull it in.

**Comment by AK-1996** [comment]
ok if I use the conda command:
"conda install -c conda-forge ipyleaflet"

it works, thank you

**Comment by davidbrochart** [comment]
Glad it helped!

**Comment by Moschi96** [comment]
Ive the same Problem but I'm still not have the solution for the Problem. It's even not possible to do Conda install ipyleaflet. 
With conda install -c conda-forge ipyleaflet I got the error:


`CondaVerificationError: The package for geos located at /Users/nilsmoschner/opt/anaconda3/pkgs/geos-3.8.1-h4a8c4bd_0
appears to be corrupted. The path 'lib/libgeos_c.1.dylib'
specified in the package manifest cannot be found.
`

**Comment by davidbrochart** [comment]
It looks like your environment is in a bad state, could you try reinstalling miniconda?

**Comment by Moschi96** [comment]
Well I did and I think the install worked but when I do `conda install ipyleaflet` that shows up


`(wetterdatenanlyse-share) nilsmoschner@Nilss-MBP wetterdatenanlyse-share % conda install ipyleaflet
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ipyleaflet

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page`

**Comment by davidbrochart** [comment]
Are you mixing channels? You should always use `conda install -c conda-forge`. It is also recommended to use `mamba` instead of `conda`:
```bash
conda install mamba -c conda-forge`
```
And then install packages with mamba:
```bash
mamba install ipyleaflet -c conda-forge
```
