### ISSUE TITLE
Search Control doesn't find anything

### ISSUE THREAD

**Issue by diego-rzo** [jupyter-widgets/ipyleaflet#787]
Hello,
The SearchControl in the maps stopped working since a while, there are no suggestions during the typing and no results after as there used to be.

![image](https://user-images.githubusercontent.com/30575231/107225383-037a3780-6a19-11eb-877d-74afb304b233.png)

Has there been any other issue on this topic?

Thanks in advance!

**Comment by sackh** [comment]
This is due to new version of `leaflet-search` is broken. I have raised PR #788 which will fix this.
