### ISSUE TITLE
DrawControl imported polygon

### ISSUE THREAD

**Issue by eironman3** [jupyter-widgets/ipyleaflet#789]
Hello guys, 

Is there any way to import a polygon shape into the map (from my database) and edit it using DrawControl?
I manage to create new polygons, export them, etc but I couldn't find a way to reshape an imported geometry.

I have been looking around and it looks like there was a discussion here #508. 
Do you guys know if there is a workaround for this?

Thanks a lot.

I really appreciate your help.

**Comment by martinRenou** [comment]
Hey.

There is a `transform` attribute that you can set to True on your `Polygon` instance, making it editable. Does that fit your needs?

**Comment by eironman3** [comment]
hi Martin, 

Thanks a lot for your answer. 
The transform option only allows you to change the size of the polygon + rotate it but I can't add/delete any additional points.

**Comment by martinRenou** [comment]
Indeed. There is currently no possible way to do that I guess. We might need to improve the DrawControl to provide this ability.

**Comment by dbergh** [comment]
I added PR #826 which should address this issue.

**Comment by giswqs** [comment]
The `data` attribute of the DrawControl implemented by @dbergh should resolve this issue. 

Alternatively, you can also use [leafmap](https://github.com/giswqs/leafmap/) to edit existing vector data interactively. 

https://user-images.githubusercontent.com/5016453/151687323-717d25bf-0c83-460c-bfb0-ab95c0e89671.mp4
