### ISSUE TITLE
Display properties (text-only labels) on the map

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#792]
Is there a way to display data properties as text-only labels on the map? The popup widget has a white bounding box, and the text size does not change according to zoom levels. Is there a better way to display text labels on the map?

https://ipyleaflet.readthedocs.io/en/latest/api_reference/popup.html
![Capture](https://user-images.githubusercontent.com/5016453/108564666-54f7b180-72b8-11eb-8a37-6141da80d36e.PNG)

**Comment by deeplook** [comment]
I have tried this with `DivIcon`, but I see the same white background.

```python
from ipyleaflet import Marker, DivIcon, Map, WidgetControl
from ipywidgets import HTML

center = (52.204793, 360.121558)

m = Map(center=center, zoom=10)
icon = DivIcon(html='''<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>''', bg_pos=[0, 0], icon_size=[150, 150])
mark = Marker(location=center, icon=icon)
m += Marker(location=center)
m += mark
m += WidgetControl(widget=HTML(icon.html))
m
```

**Comment by giswqs** [comment]
@deeplook Thanks for the example. See `transparent_bg=True` solves the issue. 

```
m += WidgetControl(widget=HTML(icon.html), transparent_bg=True)
```

![](https://i.imgur.com/yKUYjx2.jpg)

**Comment by deeplook** [comment]
Cool, I had not seen this! Thanks!

**Comment by giswqs** [comment]
I just realized the `WidgetControl` can not be used in this case as the position can be only at the four corners. The labels need to be displayed around the center of each polygon. The DivIcon should work, but it has a white background.
