### ISSUE TITLE
Creating multiple polygons without repeatedly clicking the DrawControl

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#795]
Is it possible to create multiple polygons without repeatedly clicking the DrawControl? I need to create many polygons as training samples. Currently, the DrawControl only allows creating one polygon at a time. Clicking the DrawControl repeatedly is inconvenient. Thanks. 

![](https://i.imgur.com/SIA8ThL.gif)

**Comment by davidbrochart** [comment]
> Is it possible to create multiple polygons without repeatedly clicking the DrawControl?

Not to my knowledge.

**Comment by giswqs** [comment]
> > Is it possible to create multiple polygons without repeatedly clicking the DrawControl?
> 
> Not to my knowledge.

Is there a way to listen to the DrawControl and find out which tool (e.g., marker, polygon) has been clicked?

**Comment by giswqs** [comment]
It turns out there is a `repeatMode` option. Setting `repeatMode=True` solves the issue. 

https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html

```
draw_control = DrawControl(
    marker={"shapeOptions": {"color": color.value}, "repeatMode": True},
    rectangle={"shapeOptions": {"color": color.value}, "repeatMode": True},
    polygon={"shapeOptions": {"color": color.value}, "repeatMode": True},
    circlemarker={},
    polyline={},
    edit=False,
    remove=False,
)
```

https://user-images.githubusercontent.com/5016453/109539505-621e5880-7a8f-11eb-9c5c-1e8a0a7fb7d1.mp4
