### ISSUE TITLE
Editable vertices on Paths/Polylines/Geojson/Geodata

### ISSUE THREAD

**Issue by AndrewAnnex** [jupyter-widgets/ipyleaflet#817]
I want to be able to load a geopandas dataframe into a ipyleaflet map, and be able to move/edit/drag vertices of the loaded geometries (in my case linestrings) on the ipyleaflet map. I also want to then take actions using the callbacks so I can have python code handle the specific geometry that was edited for external python processes to act on and so on (I edited the vertex of a geometry in the dataframe, I would want to know which row/geometry/ what the new geometry is/ etc).

I know this is possible with individual markers, but for more complicated geometries  it appears it may not be at the moment due to changes noted in #508 #789 #68.

Is there a way to get this functionality with the existing most recent release? If the change is trivial (or somewhat) I am happy to contribute.

**Comment by dbergh** [comment]
I added PR #826 to address #508. It does not give you quite what you want (using this you'd get an update of the whole geometry, but individual features are not tracked). Maybe you can use it for some kind of work around...

**Comment by AndrewAnnex** [comment]
thanks @dbergh, I actually found out the inner portion of my code was fast enough such that updating the whole geometry wouldn't be an issue. I ended up continuing my work in a qgis plugin, but since it's all python it shouldn't be too much work to migrate that effort back to ipyleaflet once it's merged and released. Closing the issue
