### ISSUE TITLE
'SearchControl' object has no attribute 'on_feature_found'

### ISSUE THREAD

**Issue by shnkn** [jupyter-widgets/ipyleaflet#834]
Hello,
I tried to run the Jupyter notebook example file on Github for SearchControl but I face this attached problem. Is this feature not active anymore?

Thanks

![image](https://user-images.githubusercontent.com/33637609/120638948-1ce43b00-c471-11eb-9052-ddf1ea1a6f25.png)

**Comment by sackh** [comment]
It works fine for me on the binder link.

**Comment by martinRenou** [comment]
Are you using latest ipyleaflet?

**Comment by shnkn** [comment]
I needed to update it to the newest version via conda. Now the problem is gone. Many thanks.
