### ISSUE TITLE
Saving map to html creates a blank webpage

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#841]
Saving the map to html runs without any issue. However, when opening the HTML, the page is blank (see this [link](https://spatial.utk.edu/mymap.html)). You can view the page source to see its content. Related issue https://github.com/giswqs/leafmap/discussions/23

```python
import ipyleaflet  #v0.13.6
m = ipyleaflet.Map()
m.save("mymap.html")
```

**Comment by helincao** [comment]
Just to add, here is the error msg from my Chrome console when a page is blank. 

![image](https://user-images.githubusercontent.com/18755763/121971636-0ae68000-cd2e-11eb-8b57-a3ab7b297ded.png)

**Comment by martinRenou** [comment]
Thanks for sharing the console! Indeed, this `Script error for "map-widget-for-jupyter"` happens in your example as well @giswqs. This error is very likely due to here-map-widget-for-jupyter, I suspect they didn't upload their package on npmjs, which prevents the HTML widget manager to download their package to render the map.

I would suggest opening an issue there, asking for publishing on npmjs.

**Comment by sackh** [comment]
`map-widget-for-jupyter` already is published on npmjs. - https://www.npmjs.com/package/@here/map-widget-for-jupyter
I think the main problem is that somehow ipywidgets is not able to identify npm packages with scopes. as the package is under `@here` scope hence it is not able to find it.  I have raised this issue for documentation also on jupyter sphinx - https://github.com/jupyter/jupyter-sphinx/issues/174.
I think I have the path correctly defined in `webpack.config.js` - https://github.com/heremaps/here-map-widget-for-jupyter/blob/5a6cdcbe8bdbd4cd7b86fd666f3c62cc0f43cff5/js/webpack.config.js#L110

**Comment by martinRenou** [comment]
ipywidgets should handle scopes properly, it uses a specific scope itself.

So maybe the issue comes from this? https://github.com/heremaps/here-map-widget-for-jupyter/blob/master/here_map_widget/map.py#L69

**Comment by sackh** [comment]
Thank you @martinRenou. I will change it to `@here/map-widget-for-jupyter`. and I will update here if this works.

**Comment by giswqs** [comment]
The latest version of HERE map widget has fixed this issue. The exported map can now render correctly. Thanks @sackh
