### ISSUE TITLE
basemaps.Hydda and Strava maps grey in documentation

### ISSUE THREAD

**Issue by Geo4Dev** [jupyter-widgets/ipyleaflet#848]
The maps using basemaps.Hydda and basemaps.Strava are all grey in the basemaps documentation: https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html

**Comment by StefanBrand** [comment]
Duplicate of #614?

**Comment by HaudinFlorence** [comment]
The Hydda basemap has been removed from the examples https://github.com/jupyter-widgets/ipyleaflet/pull/966
