### ISSUE TITLE
How to use the canvas renderer for plotting larger GeoJSON/GeoData dataset

### ISSUE THREAD

**Issue by ondrejsv** [jupyter-widgets/ipyleaflet#852]
I have a modest GeoJSON/GeoData dataset of point features. Currently I use the `point_style` attribute of the `GeoData` constructor to plot the points as circles. This renders the circles as SVG features which has performance issues with larger feature counts.
The Leaflet allows us to render using the canvas renderer in such cases, see https://leafletjs.com/reference-1.7.1.html#map-prefercanvas or https://stackoverflow.com/questions/43015854/large-dataset-of-markers-or-dots-in-leaflet.

**How can we force the Leaflet map to use the canvas renderer in the Jupyter notebook?**

My current code:
```
   m = ipyl.Map()
    layer = ipyl.GeoData(geo_dataframe = data_to_show,
                        point_style={'radius': 1, 'color': 'amber'})
    m.add_layer(layer)
    
```

**Comment by martinRenou** [comment]
Would you be willing to open a PR passing `preferCanvas = true` by default to the map widget?

**Comment by ondrejsv** [comment]
> Would you be willing to open a PR passing `preferCanvas = true` by default to the map widget?

I could do it but I want to ask if it is a good idea to always pass the `preferCanvas = true` or if we should leave the decision to the user and let him pass a similar option from the Jupyter Widget? What do you think?

**Comment by martinRenou** [comment]
> if we should leave the decision to the user and let him pass a similar option from the Jupyter Widget? What do you think?

That makes total sense to do that :)

**Comment by ondrejsv** [comment]
Please, check the PR #853.
