### ISSUE TITLE
Refactor basemap module on top of xyzservices

### ISSUE THREAD

**Issue by martinfleis** [jupyter-widgets/ipyleaflet#854]
Hi all,

I'd like to start a focused discussion as a follow-up of https://github.com/geopandas/contextily/issues/153 and https://github.com/jupyter-widgets/ipyleaflet/issues/741. 

We have built a new package called [`xyzservices`](https://github.com/geopandas/xyzservices) to serve as a unified place for XYZ tile management. The idea behind this is that other packages will depend on that instead of having their own system.

In the case of `ipyleaflet`, that means refactoring `basemaps` module in a way that does not contain any hard-coded data and only wraps what ``xyzservices` provides.

From a quick look, it could take the form of replacing your `Bunch` with `xyzservices.providers` Bunch and of small changes in https://github.com/jupyter-widgets/ipyleaflet/blob/c969f79da419aef39f63e6745d0f234493280f67/ipyleaflet/leaflet.py#L36 to match the `xyzservices` API (to get the proper form of URL (xref geopandas/xyzservices/pull/60) and attribution).

`xyzservices` itself does not have any dependencies which makes it a non-problematic dependency.

Some of you also mentioned you wanted the JSON stored in `share`. That also comes with `xyzservices` if you have a use case for that.

I am happy to do any changes in `xyzservices` needed to make it as useful for you as possible if that allows centralising maintenance of providers in one place.

What are your thoughts on this?

**Comment by giswqs** [comment]
Great idea for having a unified place for XYZ tiles rather than managing them in each individual package. I look forward to using it in geemap and leafmap. Would `xyzservices` consider adding `wmsservices` support? Or should it be another independent package?

A lot of WMS services can be found at https://apps.nationalmap.gov/services

**Comment by martinfleis** [comment]
>  Would xyzservices consider adding wmsservices support? Or should it be another independent package?

-> https://github.com/geopandas/xyzservices/issues/49#issuecomment-891856934 tldr: Yes, it sounds like a good addition.

**Comment by sackh** [comment]
@martinRenou, @davidbrochart If you guys agree I would like to work on this.
let me know your thoughts.

**Comment by davidbrochart** [comment]
I don't know if @giswqs is already on it?
I like that people are fighting to contribute to ipyleaflet :smile:

**Comment by giswqs** [comment]
I have not started yet. Maybe @sackh can refactor and basemap module first. Once his pull request is merged, I can work on the toolbar and basemap GUI.

**Comment by sackh** [comment]
I have the below questions:
1. There are NASAGIBS basemaps URLs where `%s` is replaced by date, how this should be handled ? if we remove this replacement logic then `def basemap_to_tiles(basemap, day='yesterday', **kwargs):`  `day` parameter is not required in this function. and it will be a breaking change.
2.  currently HERE basemaps are handled separately [here](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/external/here.py) shall we remove this ? again a breaking change.

**Comment by martinfleis** [comment]
> There are NASAGIBS basemaps URLs where %s is replaced by date, how this should be handled ? if we remove this replacement logic then def basemap_to_tiles(basemap, day='yesterday', **kwargs): day parameter is not required in this function. and it will be a breaking change.

You can map the same functionality onto `xyz.NASAGIBS` objects. 

Take `xyz.NASAGIBS.ModisTerraTrueColorCR` as an example. It has the following URL stored:

```
{'url': 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{max_zoom}/{z}/{y}/{x}.{format}',
'html_attribution': 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
'attribution': 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (ESDIS) with funding provided by NASA/HQ.',
'bounds': [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]], 
'min_zoom': 1, 
'max_zoom': 9, 
'format': 'jpg', 
'time': '', 
'tilematrixset': 'GoogleMapsCompatible_Level', 
'variant': 'MODIS_Terra_CorrectedReflectance_TrueColor', 
'name': 'NASAGIBS.ModisTerraTrueColorCR'}
```

The object itself has an empty attribute `time`, so you can create time-based URL as `xyz.NASAGIBS.ModisTerraTrueColorCR.build_url(time='2021-08-07')` which fills the correct place in the URL.

So instead of `url = url % day` you will pass `day` as `time` to `build_url`. That ensures that there's no breaking change (or no visible at all). Would that work?

> currently HERE basemaps are handled separately here shall we remove this ? again a breaking change.

I guess you can map those onto `xyz` objects as well to make it non-breaking.

**Comment by sackh** [comment]
Thanks, @martinfleis
