### ISSUE TITLE
NAD27 CRS support in ipyleaflet

### ISSUE THREAD

**Issue by wdmhouston** [jupyter-widgets/ipyleaflet#858]
I'm working in oil/gas industry, and the most common CRS datum used in USA is NAD27 instead of WGS84.   Stateplane and UTM are two major projections for map display.  

for example, 
EPSG:32040 : NAD27 / Texas South Central  https://epsg.io/32040
EPSG:26715:  NAD27 / UTM zone 15N https://epsg.io/26715

Can anybody tell me if it is possible to add NAD27 with stateplane/UTM CRS to ipyleaflet and how?

**Comment by davidbrochart** [comment]
@betolink added new projections in https://github.com/jupyter-widgets/ipyleaflet/pull/598, maybe he has ideas?

**Comment by betolink** [comment]
It should be possible, the ellipsoid is defined as the +datum parameter when we use Proj4js i.e. for EPSG:32040 

```python
# You should get your resolution values with something like 
# initialResolution =  projected_width / tile_size 
# zoom_levels = 14
# reolutions = [initialResolution ** (2*l) for l in range(zoom_levels) ]

EPSG_32040 = {
    'name': 'EPSG:32040',
    'custom': True,
    'proj4def': '+proj=lcc +lat_1=28.38333333333333 +lat_2=30.28333333333333 +lat_0=27.83333333333333 +lon_0=-99 +x_0=609601.2192024384 +y_0=0 +datum=NAD27 +units=us-ft +no_defs',
    'origin': [1934715.99110518, 505965.75122003],
    'bounds': [
        [60341.26161686, 30289.16709928],
        [3757196.70267378, 1073405.75104801]
    ],
    'resolutions': [
        8192.0,
        4096.0,
        2048.0,
        1024.0,
        512.0,
        256.0
    ]
}

m = Map(center=(-98, 28),
    zoom=0,
    max_zoom=6,
    layers=(wms_layer,),
    crs=EPSG_32040)
```

Note that I'm using regular grid resolutions, and `wms_layer` would be your base layer, guessing that you have WMS for it. At the end of that PR there is another example of how to define a WMS layer using a particular projection. Looks like NAD27 is in foot not meters so there is also an extra conversion there. 

I think we should have a projection helper method to get these values automatically with ipyleaflet like @epifanio was starting to implement at the end of that  #598 PR.

**Comment by wdmhouston** [comment]
Thanks. It's very helpful.  next question is: how to define origin, bounds and resolution? any suggestion?

**Comment by betolink** [comment]
The origin and bounds are already defined in the Proj4 definition above. Try using these values and see if they align.

**Comment by wdmhouston** [comment]
Thanks. The customized CRS works. Is it possible to specify CRS transformation method when adding basemap or other layers?

**Comment by betolink** [comment]
Yes and no, usually what works is that you tell your layer service (WMS is the most commonly used) on what projection you want a layer and they do the reprojection for you.

If your layer is in geojson leaflet will do the reprojection but base layers are usually rasters and `ipyleaflet` doesn't reproject rasters on the fly.

**Comment by wdmhouston** [comment]
I'll skip wms now.  I tried the workflow, but no go.

Here is my workflow,

define CRS:
EPSG_32040 = {
    'name': 'EPSG:32040',
    'custom': True,
    'proj4def': '+proj=lcc +lat_1=28.38333333333333 +lat_2=30.28333333333333 +lat_0=27.83333333333333 +lon_0=-99 +x_0=609601.2192024384 +y_0=0 +datum=NAD27 +units=us-ft +no_defs',
    'origin': [1934715.99110518, 505965.75122003],
    'bounds': [
        [60341.26161686, 30289.16709928],
        [3757196.70267378, 1073405.75104801]
    ],
    'resolutions': [
        8192.0,
        4096.0,
        2048.0,
        1024.0,
        512.0,
        256.0
    ]
}

create map,
m = Map(center=(497845.767,2306573.547), 
        zoom=4, 
        scroll_wheel_zoom=True,
        crs=EPSG_32040)
m.add_control(LayersControl(position='topright'))
m.add_control(FullScreenControl())
m

load a shape file,
import geopandas as gpd
file = 'xx.shp'
selDf = gpd.read_file(file)
selDf.head()
	TYPE	STATE	COUNTY	SNAME	CNAME	SHAPE_AREA	SHAPE_LEN	geometry
0	2.0	30	5	NM	CHAVES	1.524509	7.008728	POLYGON ((-103.94562 34.08263, -103.92830 34.0...
1	2.0	30	25	NM	LEA	1.095513	4.650699	POLYGON ((-103.25276 33.57043, -103.23540 33.5...
2	2.0	30	57	NM	TORRANCE	0.851955	4.110356	POLYGON ((-105.92329 34.25978, -105.92662 34.2...
3	2.0	30	9	NM	CURRY	0.358178	2.693328	POLYGON ((-103.04341 34.31678, -103.04334 34.3...
4	2.0	30	11	NM	DE BACA	0.592203	3.453959	POLYGON ((-103.94562 34.08263, -103.96314 34.0...

transform to projected crs:
geoDf = selDf.to_crs("EPSG:32040")
geoDf.head()
TYPE	STATE	COUNTY	SNAME	CNAME	SHAPE_AREA	SHAPE_LEN	geometry
0	2.0	30	5	NM	CHAVES	1.524509	7.008728	POLYGON ((497845.767 2306573.547, 503097.392 2...
1	2.0	30	25	NM	LEA	1.095513	4.650699	POLYGON ((701393.313 2111480.948, 706691.873 2...
2	2.0	30	57	NM	TORRANCE	0.851955	4.110356	POLYGON ((-98413.409 2401630.652, -99420.313 2...
3	2.0	30	9	NM	CURRY	0.358178	2.693328	POLYGON ((774711.951 2381504.453, 774554.350 2...
4	2.0	30	11	NM	DE BACA	0.592203	3.453959	POLYGON ((497845.767 2306573.547, 492528.687 2...

add to map,
geoData = GeoData(geo_dataframe=geoDf, name='xx')
m.add_layer(geoData)
m

No data show up in map. 
Which part might be wrong?

Thanks.

**Comment by betolink** [comment]
I think the map center should be in lat, lon coordinates (not projected) so if you're looking at data over Texas a good center would be `(36, -104)`.  You probably don't need to reproject the dataframe.

**Comment by wdmhouston** [comment]
I played again,
EPSG_32040 = {
    'name': 'EPSG:32040',
    'custom': True,
    'proj4def': '+proj=lcc +lat_1=28.38333333333333 +lat_2=30.28333333333333 +lat_0=27.83333333333333 +lon_0=-99 +x_0=609601.2192024384 +y_0=0 +datum=NAD27 +units=us-ft +no_defs',
    'origin': [1934715.99110518, 505965.75122003],
    'bounds': [
        [60341.26161686, 30289.16709928],
        [3757196.70267378, 1073405.75104801]
    ],
    'resolutions': [
        8192.0,
        4096.0,
        2048.0,
        1024.0,
        512.0,
        256.0
    ]
}

m = Map(center=(954373.300,1670354.224), 
        zoom=4, 
        scroll_wheel_zoom=True,
        crs=EPSG_32040)
m.add_control(LayersControl(position='topright'))
m.add_control(FullScreenControl())
m


from ipywidgets import Label
label = Label()
display(label)
def handle_interaction(**kwargs):
    if kwargs.get('type') == 'mousemove':
        label.value = str(kwargs.get('coordinates'))

m.on_interaction(handle_interaction)       
m

![image](https://user-images.githubusercontent.com/19333848/129493140-d872d0c0-5689-4055-a7b9-a207c19c51d9.png)


When I move mouse in map window, the label still shows lat/long values, and I can't zoom out any more(stuck in lat/long range).  This means "crs=EPSG_32040" doesn't work in my case. 
hope this will help for further investigation.

**Comment by betolink** [comment]
Can you post the file you're trying to visualize? I was able to use your projection with geojson and even a base layer but the way leaflet works is different from what you have. I've been using polar projections and when I get my coordinates they are in lat lon. Even if my map is projected, the same applies here.

**Comment by wdmhouston** [comment]
[nad27test.zip](https://github.com/jupyter-widgets/ipyleaflet/files/6994749/nad27test.zip)

Here it is.

**Comment by betolink** [comment]
@wdmhouston  Take a look at this revised notebook: https://github.com/betolink/ipyleaflet-projections/ 

Here is the direct link to execute it on Binder:
https://mybinder.org/v2/gh/betolink/ipyleaflet-projections/main?urlpath=lab%2Ftree%2Fnotebooks 

**ipyleaflet** can use non standard datums and state plane projections but it's a bit tricky. First you need to find the right projection parameters and then not all map services support non standard projections. Most of them only support the pseudo-mercator that's used by Google maps.

I hope this helps.

**Comment by wdmhouston** [comment]
> @wdmhouston Take a look at this revised notebook: https://github.com/betolink/ipyleaflet-projections/
> 
> Here is the direct link to execute it on Binder:
> https://mybinder.org/v2/gh/betolink/ipyleaflet-projections/main?urlpath=lab%2Ftree%2Fnotebooks
> 
> **ipyleaflet** can use non standard datums and state plane projections but it's a bit tricky. First you need to find the right projection parameters and then not all map services support non standard projections. Most of them only support the pseudo-mercator that's used by Google maps.
> 
> I hope this helps.

Thanks for the update. Unfortunately, for what I observed, the EPSG_32040 doesn't work. 
ipyleaflet map still reports lat/long values (in pseudo mercator projection, I guess).   

In any esri product(for example, ArcGIS), location will be returned correctly with x/y in us-ft when EPSG_32040 is selected as map crs.  Hope this will help.

**Comment by betolink** [comment]
I guess I didn't explain myself. **ipyleaflet** does support custom projections including EPSG:32040, however by default it only returns geographic coordinates (in this case NAD27). You can easily take those geographic coordinates and get the projected ones using pyproj. I updated the notebook to do this, here is a screenshot.

![ipyleaflet-projected](https://user-images.githubusercontent.com/717735/130013334-b3da2ee2-0ce6-486e-93e3-f3b2ff1f7be0.png)

**Comment by wdmhouston** [comment]
I see. This workaround works. Hope ipyleaflet reports x/y location in selected CRS directly in future release. Thanks.

**Comment by betolink** [comment]
I think this can be closed as resolved. @davidbrochart

**Comment by davidbrochart** [comment]
Thanks @betolink !
