### ISSUE TITLE
How to change ipywidget animation speed during animation

### ISSUE THREAD

**Issue by Oao2021** [jupyter-widgets/ipyleaflet#866]
I am using jupyter notebook to animate a marker that moves along an ant path. I am using ipyleaflet and ipywidgets. I have added a slider widget (speed_slider) to my map, to allow me change the speed of the animation. My animation is using a for loop code as shown in below code.

```
for i in ant_path.locations:
    mark.location = i
    sleep(speed_slider.value)
```

I am able to set the animation speed before running the cell that contains the above for loop code, but I am not able to change the speed during animation. Please any suggestions on how change the animation speed during the animation runtime, using the slider.

**Comment by martinRenou** [comment]
What is your animation loop code?

**Comment by Oao571** [comment]
```
for i in ant_path.locations:
    mark.location = i
    sleep(speed_slider.value)
```

**Comment by Oao571** [comment]
```
speed_slider = widgets.FloatSlider(description='Animation speed:', 
                                   min=0.01, max=1, step=0.01,
                                  continuous_update=True)
```

This is my slider widget. So with this slider I can set the animation speed before running the animation loop code. But I cannot change the animation speed once the animation has started, as I want to change the speed during the animation run time.

**Comment by martinRenou** [comment]
I guess you need to run your animation in a separate thread

**Comment by Oao2021** [comment]
Thanks Martin. I wonder how that would work? 
By the way what I am working on can be found here [https://github.com/Oao2021/simulation-edge-computing.git] Adjusting the simulation speed during the simulation runtime is what I am trying to achieve.

**Comment by Oao2021** [comment]
Thanks so much Martin. Implemented and working perfectly.
