### ISSUE TITLE
Very slow CircleMarker creation (?)

### ISSUE THREAD

**Issue by mangecoeur** [jupyter-widgets/ipyleaflet#881]
I'm creating a map with a "medium" number of CircleMarkers in JupyterLab and having some performance issues, it seems that just creating a CircleMarker is very slow, e.g:
```python
%%time
from ipyleaflet import CircleMarker
for i in range(1000):
    c = CircleMarker()
```
Takes 1.4seconds, I would not expect creating 1000 objects to be that slow (would expect timings in the milli or micro second range). Is there an explanation for this or a workaround?

I'm using latest JupyterLab via JupyterHub running on an Ubuntu server, the client is Firefox 94 on Windows 10.

**Comment by mangecoeur** [comment]
Deeper investigation suggests that this happens because every CircleMarker call instantiates a Widget with bidirectional comms between the kernel and the client. In my case I don't need this. It seems in Leaflet you can instantiate a MarkerCluster from geojson point data directly by adding it as a layer in MarkerCluster, which would be ideal since the geojson sync is very fast. However MarkerCluster widget side doesn't seem to allow this (?)

**Comment by martinRenou** [comment]
> call instantiates a Widget with bidirectional comms between the kernel and the client. In my case I don't need this

Would using a `GeoJSON` layer instead be an option?

**Comment by mangecoeur** [comment]
> Would using a GeoJSON layer instead be an option?

The problem is I want keep the cluster behavior of the MarkerCluster. In Leaflet it's possible to add a GeoJSON layer of points to a MarkerCluster, this would be exactly what I need. However, it is not possible in ipyleaflet to set the markers attribute to be a GeoJSON layer (trait type expects `tuple(Marker)`). I don't know if it would be possible to change this without a deeper re-working of MarkerCluster - I would love any hints on this point.

**Comment by martinRenou** [comment]
I see. Then I guess this would need a rework on the `MarkerCluster` logic in ipyleaflet as you suggested.

You're welcome to open a PR for this if you want to contribute :) I'd be happy to guide you a bit.

**Comment by mangecoeur** [comment]
Ok, I thought that might be the case. I think I could attempt this since it's really bugging me (I optimised the hell out of my calculation only to have it hang for 3 seconds while loading little circles ;)  I've had a glance at the widget doc but any pointer on where to start are very welcome!

**Comment by martinRenou** [comment]
I guess you would need to remove the fact that we enforce `markers` to be a tuple of `Marker`s here: https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L1021

Instead we could maybe have a `Any`, that way `markers` can be anything:
```python
markers = Any().tag(sync=True, **widget_serialization)
``` 

And you would need to have an `if` condition wrapping this: https://github.com/jupyter-widgets/ipyleaflet/blob/master/js/src/layers/MarkerCluster.js#L34-L53 adding support there for a list a `Marker` widgets **and** support for GeoJSON.

**Comment by martinRenou** [comment]
The dev installation documentation is outdated. You should follow the one from the README: https://github.com/jupyter-widgets/ipyleaflet#installation-from-sources

**Comment by mangecoeur** [comment]
Thanks for the pointers I will have a look. Ideally I can copy the pattern of LayerGroup so that you can instantiate a geojson layer and add it to the marker cluster.

**Comment by mangecoeur** [comment]
@martinRenou p.s. what's the best place to learn how to test while developing (e.g. getting console logs in JS), I don't really understand from the dev docs whether I need to run `jupyter labextension develop --overwrite ipyleaflet` on every change or what...

**Comment by mangecoeur** [comment]
Good news: I was able to make this work without any bizzaro code:  just made the MarkerCluster behave exactly like the LayerGroup which allows GeoJson layers to be added to marker clusters. Even better, allows to mix using Markers objects and GeoJson layers into the same MarkerCluster.

**Comment by mangecoeur** [comment]
Closing because the PR was merged
