### ISSUE TITLE
Constrain bounds of TileLayer

### ISSUE THREAD

**Issue by banesullivan** [jupyter-widgets/ipyleaflet#888]
Would it be possible to add a property to the `TileLayer` that will constrain its bounds? 

The lack of constraint poses a problem when accessing a tile server I have that serves individual rasters (small coverage, not global). The `TileLayer` continues to make requests from my tile server anytime I zoom out/view outside the data bounds, overloading my tile server which is just returning a bunch of transparent PNGs.

The logic I'm looking for:

```py
t = TileLayer(
    url="https://mytileserver.com/tiles/{z}/{x}/{y}.png?projection=EPSG:3857",
    # Do not request tile outside of these bounds (bottom, top, left, right)
    bounds=[37.40679, 38.080379, -122.759396, -122.065103],
)
```

From what I can tell, the leaflet JS tileLayer does have an option for `bounds` that is inherited from gridLayer but this does not seem to be wrapped in `ipyleaflet`. Ref https://leafletjs.com/reference.html#tilelayer

Example data:

<img width="970" alt="Screen Shot 2021-11-20 at 8 33 19 PM" src="https://user-images.githubusercontent.com/22067021/142748455-406ce5d5-75e8-4704-9c30-bfb58975804d.png">

-------

Additional context:

- https://github.com/banesullivan/flask-tileserver / https://github.com/jupyter-widgets/ipyleaflet/issues/234#issuecomment-974716145
- https://github.com/ResonantGeoData/ResonantGeoData/pull/603

**Comment by davidbrochart** [comment]
I think it could be useful, would you be interested in implementing that feature?
Otherwise, instead of returning transparent PNGs, you could also return a `404` HTTP response.

**Comment by banesullivan** [comment]
> I think it could be useful, would you be interested in implementing that feature?

I can certainly try though Jupyter widget development has proven challenging to me in the past.

@giswqs, perhaps you would be willing to give this a try since you have experience developing in this project and hope to use the `flask-tileserver`?

> Otherwise, instead of returning transparent PNGs, you could also return a 404 HTTP response.

Fair. However, my problem is with the onslaught of unnecessary requests rather than creating the PNGs

**Comment by giswqs** [comment]
I am not good at JavaScript. Not quite sure what changes should be made. 
https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L513

**Comment by banesullivan** [comment]
I started fiddling around with this and could not get anywhere close to figuring this out. Jupyter widgets always seem like magic to me

**Comment by davidbrochart** [comment]
@banesullivan is this something you still need? I can have a look at it.

**Comment by martinRenou** [comment]
This will probably be a one-liner:

```python
bounds = Tuple(allow_none=True).tag(sync=True, o=True)
```
?

**Comment by martinRenou** [comment]
@banesullivan If you still need this feature and cannot wait for a move from our side, you can probably do this:

```python
from traitlets import Tuple

class BoundTileLayer(TileLayer):
    bounds = Tuple(default_value=None, allow_none=True).tag(sync=True, o=True)

t = BoundTileLayer(
    url="https://mytileserver.com/tiles/{z}/{x}/{y}.png?projection=EPSG:3857",
    # Do not request tile outside of these bounds (bottom, top, left, right)
    bounds=[37.40679, 38.080379, -122.759396, -122.065103],
)
```

**Comment by davidbrochart** [comment]
Not quite, the bounds must be in the form:
```
((south, west), (north, east))
```
I'll open a PR.

**Comment by banesullivan** [comment]
Aha! That's awesome! I can confirm that `((south, west), (north, east))` works!

| before | after |
|---|---|
|<img width="940" alt="Screen Shot 2021-12-20 at 9 42 28 AM" src="https://user-images.githubusercontent.com/22067021/146801946-e54a6531-2f7c-422b-b97c-d4c53ad1e472.png">|<img width="943" alt="Screen Shot 2021-12-20 at 9 42 18 AM" src="https://user-images.githubusercontent.com/22067021/146801963-91cf852c-6b56-49ae-a56a-79d52f7f250e.png">|

There's a nifty "debug" tile server in `localtileserver` which is live here: `https://tileserver.banesullivan.com/tiles/debug/{z}/{x}/{y}.png?sleep=0`

```py
from ipyleaflet import Map, TileLayer
from traitlets import Tuple

class BoundTileLayer(TileLayer):
    bounds = Tuple(default_value=None, allow_none=True).tag(sync=True, o=True)

b = (23.564991210892646,
 25.550873767434343,
 -78.95864996539397,
 -76.57492370013779)

t = BoundTileLayer(
    url='https://tileserver.banesullivan.com/tiles/debug/{z}/{x}/{y}.png?sleep=0',
    # Do not request tile outside of these bounds ((south, west), (north, east))
    bounds=((b[0],b[2]), (b[1], b[3])),
)

m = Map(center=[31.092678045970622, -73.68000268936159], zoom=4)
m.add_layer(t)
m
```
