### ISSUE TITLE
fit_bounds() setting too low zoom level

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#902]
I find `map.fit_bounds()` mostly setting the resulting zoom level one number to low, but not always. This is some testing to illustrate. The notebook is available as a [gist](https://gist.github.com/deeplook/8452c3afa6cd692ed812364c189e8fd1).

![fit_bounds](https://user-images.githubusercontent.com/1001778/145454051-7ae07f64-ac3d-479c-9234-de939d64b0fb.gif)

**Comment by davidbrochart** [comment]
`map.fit_bounds()` works iteratively by [reading the bounds from the front-end](https://github.com/jupyter-widgets/ipyleaflet/blob/f48243afdd39110d768e6110edbf54ac58f59e28/ipyleaflet/leaflet.py#L2295), so it has to be called **after** the widget is displayed.
