### ISSUE TITLE
Opening a popup on clicking a GeoJSON object

### ISSUE THREAD

**Issue by PROgram52bc** [jupyter-widgets/ipyleaflet#912]
From the documentation on [popup](https://ipyleaflet.readthedocs.io/en/latest/api_reference/popup.html), it seems like popups can only be opened interactively with the marker element. 

I wonder if it can also be opened via a custom callback function attached to a `GeoJSON.on_click` method, adding something like `popup.open()` or `popup.close()` to the `Popup` class.

Seems to be related to #239. Any suggestions on how I should proceed from here?

**Comment by martinRenou** [comment]
> adding something like popup.open() or popup.close() to the Popup class

That sounds like a good idea :)

If you would like to implement this feature, I guess it will be similar to the `redraw` function the `TileLayer` class provides: https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L589-L595
It sends a comm message asking for a `redraw`, and the front-end handles it here: https://github.com/jupyter-widgets/ipyleaflet/blob/3273696bfe73d051fc7864f6731c8ed2198e6f68/js/src/layers/TileLayer.js#L76-L80
Don't hesitate to ask for more guidance :) 
Opening the popup in JS will look like the following I guess:
```javascript
this.map_view.el.openPopup(this.el);  // "this.el" is the Popup object at that point
```

**Comment by PROgram52bc** [comment]
Thanks! I will look into this sometime next week.

**Comment by PROgram52bc** [comment]
I installed the development environment following [this document](https://github.com/jupyter-widgets/ipyleaflet/blob/master/docs/source/installation.rst), but now the issue is that I cannot see changes that I made on the javascript side (e.g. adding a `console.log` statement to `js/src/leaflet.js`). I have a separate console running `npm run watch`, but webpack seems not to have seen the change I have made. Any suggestions? Is that the right way to set up the dev environment?

**Comment by martinRenou** [comment]
Are you developing on Jupyter Notebook or JupyterLab?

**Comment by PROgram52bc** [comment]
> Are you developing on Jupyter Notebook or JupyterLab?

I'm using jupyter notebook

**Comment by martinRenou** [comment]
Did you run the command:
```
jupyter nbextension install --py --symlink --sys-prefix --overwrite ipyleaflet
jupyter nbextension enable --py --sys-prefix ipyleaflet
```
?

The dev docs is missing the `--overwrite` option that you might need

**Comment by martinRenou** [comment]
Also after npm finished rebuilding, you need to refresh the web page in order to reload your JS code.

**Comment by PROgram52bc** [comment]
Yes, I did run the two commands to install the extensions.
Also, I refreshed the pages as well.
Are the generated files in the `dist` directory?

**Comment by PROgram52bc** [comment]
Although it is a little slow, I think I can see the changes now. Thanks for your help!

**Comment by PROgram52bc** [comment]
Any comments on #914?
