### ISSUE TITLE
Multiple maps in Basemaps documentation are grey

### ISSUE THREAD

**Issue by judafe** [jupyter-widgets/ipyleaflet#923]
Three maps in the [Basemaps documentation](https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html) are completely grey. 
They are...
- Map(basemap=basemaps.Gaode.Satellite, center=center, zoom=zoom)
- Map(basemap=basemaps.Hydda.Full, center=center, zoom=zoom)
- Map(basemap=basemaps.Hydda.Base, center=center, zoom=zoom)

**Comment by davidbrochart** [comment]
See #606 for the Hydda maps. The Gaode maps seem fine.
