### ISSUE TITLE
TileLayer: Simplify the max_zoom logic

### ISSUE THREAD

**Issue by banesullivan** [jupyter-widgets/ipyleaflet#925]
I'm hoping/thinking this might just be a user issue on my end, but it is currently appearing that TileLayer's `max_zoom` value is capped at 18 even after setting it to a higher value. For example, in this MyBinder demo's `example.ipynb`: https://mybinder.org/v2/gh/banesullivan/localtileserver-demo/HEAD which I have modified below:

```py
from localtileserver import examples, get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# Create a tile server from an raster URL
oam = TileClient('https://oin-hotosm.s3.amazonaws.com/59c66c5223c8440011d7b1e4/0/7ad397c0-bba2-4f98-a08a-931ec3a6e943.tif')

# Create ipyleaflet TileLayer from that server
# Please note that all extra kwargs are passed to `TileLayer`
oam_layer = get_leaflet_tile_layer(oam, max_zoom=24, show_loading=True)

# Create ipyleaflet map, add layers, add controls, and display
m = Map(center=oam.center(), zoom=20, max_zoom=100)
m.add_layer(oam_layer)
m
```

```py
>>> from ipyleaflet import TileLayer
>>> isinstance(oam_layer, TileLayer)
True
>>> oam_layer.max_zoom
24
```

No matter how much I zoom in, I can watch the network tab in the browser and see that the tile requests coming from that TileLayer never exceed zoom level 18, e.g., `.../proxy/41129/api/tiles/18/85161/117721.png`

![Screen Shot 2022-02-10 at 10 29 10 AM](https://user-images.githubusercontent.com/22067021/153463130-f9a36246-13d7-49e9-9e10-22b9fecc9a05.png)

I know that this image source has a max zoom level of `24` and `localtileserver` will continue serving tiles at whatever zoom level is requested regardless of the cap in the data source.

So I'm wondering what is missing here to make sure `TileLayer` can continue to fetch tiles beyond zoom level 18.

### Additional context

| ipyleaflet | CesiumJS |
|---|---|
| in the share mybinder | https://tileserver.banesullivan.com/?filename=https%3A%2F%2Foin-hotosm.s3.amazonaws.com%2F59c66c5223c8440011d7b1e4%2F0%2F7ad397c0-bba2-4f98-a08a-931ec3a6e943.tif |
| ![Screen Shot 2022-02-10 at 10 35 25 AM](https://user-images.githubusercontent.com/22067021/153464216-44984280-154e-4f00-aa2e-8a3cfe3cb74a.png) | ![Screen Shot 2022-02-10 at 10 35 45 AM](https://user-images.githubusercontent.com/22067021/153464238-430fa152-14c2-4b07-8446-dae1fd9a314a.png) |

This is very high resolution imagery and it'd be fantastic to visualize at full resolution with ipyleaflet

**Comment by davidbrochart** [comment]
`max_zoom` is [set to 18 by default](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L572).

**Comment by banesullivan** [comment]
Right, but if you try to increase that, it does not work

**Comment by davidbrochart** [comment]
[Map](https://github.com/jupyter-widgets/ipyleaflet/blob/c7384021fe3f4c5c8969dc06b869abdffe094b7a/ipyleaflet/leaflet.py#L2019) and [TileLayer](https://github.com/jupyter-widgets/ipyleaflet/blob/c7384021fe3f4c5c8969dc06b869abdffe094b7a/ipyleaflet/leaflet.py#L548) have a `max_zoom` set to 18 by default, so I guess you have to change both.

**Comment by banesullivan** [comment]
That is exactly what I did in the minimal example above. 

Both are set to 100.

**Comment by davidbrochart** [comment]
Ah, my bad.
A `TileLayer` also has the notion of "maximum native zoom level". Beyond this zoom level, new tiles won't be requested. Instead, the tiles at maximum zoom level will just be displayed bigger.
So you also need to pass `max_native_zoom=100` to the `TileLayer`. Each tile provider has this max native zoom (see [xyzservices](https://github.com/geopandas/xyzservices/blob/main/provider_sources/xyzservices-providers.json)).

**Comment by banesullivan** [comment]
Thanks for pointing out `max_native_zoom`. Having `max_zoom` and `max_native_zoom` set appropriately in the `TileLayer` with the same value set in the `Map` resolves this issue.

Could `max_native_zoom` and `max_zoom` be explained further in the docs: https://ipyleaflet.readthedocs.io/en/latest/api_reference/tile_layer.html

From reading up on leaflet.js' docs, I see the difference as:

- `max_zoom`: The maximum zoom level up to which this layer will be displayed (inclusive).
- `max_native_zoom`: Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than maxNativeZoom will be loaded from maxNativeZoom level and auto-scaled.

While I understand the use case for having these two, it feels a bit clunky... would it be possible to improve the usability of this within `ipyleaflet`? 

For example, 

- I think `max_zoom` of `TileLayer` should be set to None such that the tiles are never turned off by default when zooming passed them, instead the images should be scaled
- the `max_zoom` of the TileLayer` could, by default, match the `max_native_zoom`. This would prevent the tiles from disappearing before reaching the maximum zoom.
- the Map's `max_zoom` could be reset to the `TileLayer` in the `Map` with the highest zoom level if above 18.
- If setting `zoom` on `Map` to something greater than the default `max_zoom` of 18, `max_zoom` should be increased

Otherwise, for my original example, I have to set the `max_zoom` level in three different places, which isn't very "Pythonic".

**Comment by davidbrochart** [comment]
Agreed, do you want to open a PR? That would be awesome.

**Comment by giswqs** [comment]
I just ran into the same issue. Tile layer does not render with max_zoom >18. @XingongLi

![Peek 2022-02-21 22-16](https://user-images.githubusercontent.com/5016453/155056738-ee207cfa-8bce-4396-8704-a5b2084ba7fe.gif)

**Comment by XingongLi** [comment]
I see that same thing. When I zoomed in to certain level, the tile.tif just disappeared.

**Comment by HaudinFlorence** [comment]
@banesullivan Is it possible to use your example with the Martin's view, to clarify things related to max_zoom in a new version of the documentation (with a link to a note book for instance) Thanks ?

**Comment by banesullivan** [comment]
Absolutely! I've gone ahead and provided an example in `localtileserver`'s documentation that you can point to: https://localtileserver.banesullivan.com/user-guide/ipyleaflet_deep_zoom.html

Please feel free to contribute to that example!

**Comment by martinRenou** [comment]
Fixed by #965 ! Thanks!

**Comment by martinRenou** [comment]
@banesullivan you should not need to provide a `max_zoom` for the Map anymore, its value is `None` by default (like in LeafletJS) which means the map takes the max value of the tile layers max zoom automatically.

**Comment by banesullivan** [comment]
Fantastic! I'll give this a try and update the example in those localtileserver docs

**Comment by martinRenou** [comment]
By the way it would be great to add your project to https://ipyleaflet.readthedocs.io/en/latest/related_projects/index.html :)

**Comment by HaudinFlorence** [comment]
> Fantastic! I'll give this a try and update the example in those localtileserver docs

You can find an example based on one of the previous map and tile_layer youcprovided in the following notebook : examples/Max_zoom.ipynb
