### ISSUE TITLE
[Question / Feature] Adding multiple basemaps as leaflet control layers?

### ISSUE THREAD

**Issue by whudson** [jupyter-widgets/ipyleaflet#970]
In leaflet.js it is possible to have multiple basemaps that show up in radio boxes at the top of LayerControl by adding them as control layers:

http://bl.ocks.org/cccruzr/2be38431f91ff2adb9ded7c0e0950382

Is there any way to do this in IPyLeaflet?

**Comment by whudson** [comment]
Passing a dict of TileLayers into the Map() constructor results in no basemap being shown.

**Comment by whudson** [comment]
Adding TileLayers by Map.add_layer() is not ideal because they all load visible on the map.

**Comment by giswqs** [comment]
[Leafmap ](https://github.com/giswqs/leafmap) has some similar functionality. Not sure if it suits your needs. 

Notebook: https://leafmap.org/notebooks/02_using_basemaps
Demo: https://www.youtube.com/watch?v=-lOo-vxjrDM

**Comment by whudson** [comment]
Thanks. There sure are a lot of different options for mapping in Jupyter!

**Comment by martinRenou** [comment]
There is a LayerControl in ipyleaflet, if that's the question: https://ipyleaflet.readthedocs.io/en/latest/controls/layers_control.html

**Comment by whudson** [comment]
That was not my question. IPyLeaflet does not appear to support using multiple basemaps as shown in the linked leaflet.js example.

**Comment by martinRenou** [comment]
IIRC it does, if you add multiple tile layers to the map, giving a name to each tile layer

**Comment by whudson** [comment]
![Capture](https://user-images.githubusercontent.com/519003/164031779-f8eba9b8-763f-4945-b2c9-cbd9c84a7423.PNG)

In the leaflet example. the basemaps are grouped at the top of the later control and selectable using radio buttons. Only one is loaded at a time.

**Comment by whudson** [comment]
Example:
```
from ipyleaflet import Map, basemaps, basemap_to_tiles, LayersControl

m = Map(
    basemap=basemap_to_tiles(basemaps.OpenStreetMap.Mapnik),
    center=(48.204793, 350.121558),
    zoom=3
    )

layer = basemap_to_tiles(basemaps.OpenStreetMap.Mapnik)
layer.name = "Test Layer"
m.add_layer(layer)
m.add_control(LayersControl())
m
```

![Capture](https://user-images.githubusercontent.com/519003/164034845-29227cc9-4cf2-48b3-9de0-fb119edf4973.PNG)

**Comment by martinRenou** [comment]
You apparently need to set the `base` property to `True` as well:

```python
from ipyleaflet import *

mapnik = basemap_to_tiles(basemaps.OpenStreetMap.Mapnik)
mapnik.base = True
mapnik.name = 'Mapnik Layer'

toner = basemap_to_tiles(basemaps.Stamen.Toner)
toner.base = True
toner.name = 'Toner Layer'

bzh = basemap_to_tiles(basemaps.OpenStreetMap.BZH)
bzh.base = True
bzh.name = 'BZH layer'

m = Map(center=(52, 10), zoom=8, layers=[mapnik, toner, bzh])

m.add_control(LayersControl())

m
```

We could probably provide some APIs to make this simpler

**Comment by whudson** [comment]
Just to note- setting the name is not necessary for them to show up as base layers, only the base property needs to be set True.
