### ISSUE TITLE
Layer order not always respected

### ISSUE THREAD

**Issue by jfoster17** [jupyter-widgets/ipyleaflet#993]
In theory, the order of layers on a Map should be determined by the layers python tuple (https://github.com/jupyter-widgets/ipyleaflet/issues/28#issuecomment-367841675, https://github.com/jupyter-widgets/ipyleaflet/issues/843) but in practice this does not always work. Specifically, if I add a GeoJSON layer and a Heatmap layer, the GeoJSON layer is plotted on top of the Heatmap irrespective of the order the layers show up in Map.layers.  Am I doing something wrong?

```python
import os
import json
import requests
from ipyleaflet import Map, GeoJSON, Heatmap

if not os.path.exists('europe_110.geo.json'):
    url = 'https://github.com/jupyter-widgets/ipyleaflet/raw/master/examples/europe_110.geo.json'
    r = requests.get(url)
    with open('europe_110.geo.json', 'w') as f:
        f.write(r.content.decode("utf-8"))

with open('europe_110.geo.json', 'r') as f:
    data = json.load(f)

data['features'] = [data['features'][0]] # Trim to one country so printing layers is readable

m = Map(center=(40.9964, 19.9851), zoom=6)
geo_json = GeoJSON(
    data=data,
    style={
        'opacity': 1, 'dashArray': '9', 'fillOpacity': 0.9, 'weight': 1, 'fillColor': 'white',
    },
)

heatmap = Heatmap(
    locations=[[41.327,19.819],[40.73,19.562]],
    radius=5,
    blur=1,
    min_opacity=1,
    
)
m.add_layer(heatmap)

m.add_layer(geo_json)

m
```
Map looks like this:
![Screen Shot 2022-06-07 at 1 57 46 PM](https://user-images.githubusercontent.com/3639698/172450837-92942eed-0267-48be-b001-ebba22fd5bf4.png)

I have the GeoJSON layer in white and mostly opaque so you can see that the red points are behind/below it.

and `[type(x) for x in m.layers]` gives 

[ipyleaflet.leaflet.TileLayer,
 ipyleaflet.leaflet.Heatmap,
 ipyleaflet.leaflet.GeoJSON]

If I reorder the Heatmap and GeoJSON:

`m.layers = [m.layers[0], m.layers[2], m.layers[1]]`

`[type(x) for x in m.layers]` gives

[ipyleaflet.leaflet.TileLayer,
 ipyleaflet.leaflet.GeoJSON,
 ipyleaflet.leaflet.Heatmap]

as expected, but the map looks the same, with the white GeoJSON layer on top of the red points.

**Comment by jfoster17** [comment]
This problem might be specific to certain layer types. If I have two GeoJSON layers the above snippets work as expected -- exchanging the layer order exchanges the order they are drawn on the map.

**Comment by davidbrochart** [comment]
Thanks @jfoster17, I think this is more of a Leaflet issue, that can be solved using [panes](https://leafletjs.com/examples/map-panes). We don't currently support them in ipyleaflet, but I guess we need to if we want to solve layer ordering.

**Comment by davidbrochart** [comment]
I opened #999, this should now work if you add the following before displaying the map:
```py
m.panes = {"heatmap": {"zIndex": 650}}
```

**Comment by miguel-planet** [comment]
I am trying the same approach but using DrawControl. After creating a map and adding a rectangle with DrawControl, I am adding two polygons from GeoJSON, which always go on top of the drawn rectangle. Is there a way to ensure the layer created from DrawControl is always on top?
