### ISSUE TITLE
Release instructions

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipyleaflet#996]
How is ipyleaflet released these days? Are there release instructions documented somewhere?

I'm happy to help with a bugfix release solving #995 (and maybe also including #988, if it's deemed not risky?)

**Comment by martinRenou** [comment]
We release the wheel/sdist and npm package manually, though it would be nice to setup the jupyter-releaser with ipyleaflet.

**Comment by jasongrout** [comment]
In the meantime, could we write even just a short set of release instructions?

**Comment by martinRenou** [comment]
Sure :) I will push a PR

**Comment by jasongrout** [comment]
I added your release instructions (plus a few tweaks I found in the process) in 7a2b15d69b24efa6aa17e8c7f3c10974a059444f
